import assert from 'node:assert/strict';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { useWorkbenchWorkspaceCollectionState } from '../../src/features/workbench/useWorkbenchWorkspaceCollectionState.ts';
import { useWorkbenchWorkspacePersistenceResources } from '../../src/features/workbench/useWorkbenchWorkspacePersistenceResources.ts';
import { useWorkbenchDesktopExitState } from '../../src/features/workbench/useWorkbenchDesktopExitState.ts';
import { useWorkbenchHardSphereRuntimeResources } from '../../src/features/workbench/useWorkbenchHardSphereRuntimeResources.ts';
import { projectWorkbenchActiveFile, type WorkbenchActiveFileProjectionPorts } from '../../src/features/workbench/useWorkbenchFileCollectionProjection.ts';
import { createWorkbenchEditRestoreCleanup } from '../../src/features/workbench/workbenchEditRestoreCleanup.ts';
import { createWorkbenchDesktopNavigationActions, type WorkbenchDesktopNavigationPorts } from '../../src/features/workbench/workbenchDesktopNavigationActions.ts';
import { createDefaultStandardFile } from '../../src/features/workbench/workbenchFileState.ts';
import type { PromptConfirmationRequest } from '../../src/components/prompts/PromptConfirmDialog.tsx';
const renderHook = <T,>(useValue: () => T): T => { let value: T | undefined; const Probe = () => { value = useValue(); return null; }; renderToStaticMarkup(createElement(Probe)); assert.notEqual(value, undefined); return value as T; };
const first = createDefaultStandardFile(1), closed = [createDefaultStandardFile(2)]; let closedReads = 0;
const state = renderHook(() => useWorkbenchWorkspaceCollectionState({ initialSession: { files: [first], activeFileId: first.id, selectedPanel: 'preview' }, initialHeatCapacityRefreshSession: null, getInitialClosedFiles: () => { closedReads += 1; return closed; } }));
assert.equal(closedReads, 1); assert.strictEqual(state.filesRef.current, state.files); assert.strictEqual(state.closedFiles, closed); assert.strictEqual(state.closedFilesRef.current, closed); assert.deepEqual([...state.issuedWorkbenchFileIdsRef.current], [first.id, closed[0]!.id]); assert.equal(state.activeFileIdRef.current, first.id); assert.equal(state.selectedPanelRef.current, 'preview');
const resources = renderHook(() => ({ persistence: useWorkbenchWorkspacePersistenceResources(null), exit: useWorkbenchDesktopExitState(), runtime: useWorkbenchHardSphereRuntimeResources() }));
assert.equal(resources.persistence.scheduleWorkspacePersistenceRef.current(), false); assert.equal(await resources.persistence.flushWorkspacePersistenceRef.current(), false); assert.equal(await resources.persistence.persistWorkspaceLifecycleCheckpointRef.current(), false); assert.equal(resources.persistence.skipInitialConsoleScrollRef.current, false);
assert.equal(resources.exit.desktopExitQuiesced, false); assert.equal(resources.exit.desktopExitQuiescedRef.current, false); assert.equal(resources.exit.desktopExitAutoDemoClockRef.current, null); assert.equal(resources.exit.desktopExitQuiescedAtMsRef.current, null);
assert.deepEqual(resources.runtime.standardRuntimeRef.current, {}); assert.notStrictEqual(resources.runtime.standardRuntimeRef.current, resources.runtime.idealRuntimeRef.current);
const projectionEvents: string[] = []; const activeFileIdRef = { current: 'previous' }; const pending = { current: true };
const projection: WorkbenchActiveFileProjectionPorts = { activeFileId: first.id, activeFileIdRef, initialHeatCapacityRefreshSession: { activeHeatCapacityFileId: 'other' } as NonNullable<WorkbenchActiveFileProjectionPorts['initialHeatCapacityRefreshSession']>, disableHeatCapacityInitialSceneRestore: () => { assert.equal(activeFileIdRef.current, first.id); projectionEvents.push('disable-restore'); }, heatCapacityRefreshRestorePendingRef: pending, setSelectedFileId: id => { projectionEvents.push(`select:${id}`); } };
projectWorkbenchActiveFile(projection); assert.deepEqual(projectionEvents, ['disable-restore']); pending.current = false; projectWorkbenchActiveFile(projection); assert.deepEqual(projectionEvents, ['disable-restore', 'disable-restore', `select:${first.id}`]);
const cleanupEvents: string[] = []; const renameRef = { current: 'renaming' as string | null }; const mark = (name: string) => () => { cleanupEvents.push(name); };
createWorkbenchEditRestoreCleanup({ setParameterInputDrafts: mark('drafts'), setParameterErrors: mark('errors'), setIdealAdvancedSettingsOpen: mark('advanced'), setIdealAdvancedSettingsBodyVisible: mark('body'), setOpenFileMenuId: mark('menu'), setPendingDeleteFileId: mark('delete'), setPendingRemovePointId: mark('point'), setPendingClearRelationKey: mark('relation'), cancelPistonOscillationFreeSetup: mark('piston'), renamingFileIdRef: renameRef, setRenamingFileId: () => { assert.equal(renameRef.current, null); cleanupEvents.push('rename'); }, setRenameDraft: mark('rename-draft'), setOpenTopMenu: mark('top') }).clearEditRestoreTransientUi();
assert.deepEqual(cleanupEvents, ['drafts', 'errors', 'advanced', 'body', 'menu', 'delete', 'point', 'relation', 'piston', 'rename', 'rename-draft', 'top']);

const navigation: string[] = []; let allowed = false; let confirmation: PromptConfirmationRequest | null = null; const tutorialActiveRef = { current: false };
const navigationWindow = { open: (url: string) => { navigation.push(`open:${url}`); return null; }, close: () => { navigation.push('close'); }, hardSphereLabWindow: undefined, hardSphereLabUserGuide: undefined } as unknown as WorkbenchDesktopNavigationPorts['window'];
const nav = createWorkbenchDesktopNavigationActions({ window: navigationWindow, guardWorkbenchTutorialAction: () => allowed, setOpenTopMenu: () => { navigation.push('menu'); }, getFreshWorkbenchWindowUrl: () => 'fresh-local-window', tutorialActiveRef, settingsLanguagePreference: 'en', requestPromptConfirmation: request => { confirmation = request; } });
nav.openNewWorkbenchWindow(); assert.deepEqual(navigation, []); allowed = true; nav.openNewWorkbenchWindow(); assert.deepEqual(navigation, ['menu', 'open:fresh-local-window']);
nav.closeDesktopWindow(); assert.equal(navigation.at(-1), 'close'); tutorialActiveRef.current = true; const beforeClose = navigation.length; nav.closeDesktopWindow(); assert.equal(navigation.length, beforeClose); assert.ok(confirmation);
const request = confirmation as unknown as PromptConfirmationRequest; assert.equal(request.id, 'exit-unfinished-experiment-tutorial'); request.onConfirm(); assert.equal(navigation.at(-1), 'close');
navigationWindow.hardSphereLabWindow = { newWindow: async () => { throw Error('native window unavailable'); } } as unknown as NonNullable<WorkbenchDesktopNavigationPorts['window']['hardSphereLabWindow']>;
nav.openNewWorkbenchWindow(); await new Promise<void>(resolve => setImmediate(resolve)); assert.equal(navigation.at(-1), 'open:fresh-local-window');
nav.openUserGuide(); assert.ok(navigation.at(-1)?.startsWith('open:'));
console.log('Workbench collection identity, resource initialization, cleanup and desktop navigation tests passed.');
