import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const source = readFileSync(new URL('../../src/features/workbench/WorkbenchStudioPrototype.tsx', import.meta.url), 'utf8');
const ast = ts.createSourceFile('WorkbenchStudioPrototype.tsx', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
const calls = new Map<string, ts.CallExpression[]>();
const visit = (node: ts.Node) => { if (ts.isCallExpression(node) && ts.isIdentifier(node.expression)) { const list = calls.get(node.expression.text) ?? []; list.push(node); calls.set(node.expression.text, list); } ts.forEachChild(node, visit); }; visit(ast);
const call = (name: string) => { const matches = calls.get(name) ?? []; assert.equal(matches.length, 1, name + ' has one shell owner'); return matches[0]!.getText(ast); };
const files = call('createWorkbenchFileActions');
assert.match(files, /filesRef, closedFilesRef, activeFileIdRef, selectedPanelRef/);
assert.match(files, /commitWorkbenchFileCollections: \(nextFiles, nextClosedFiles, nextActiveId\) => commitWorkbenchFileCollections\(nextFiles, nextClosedFiles, nextActiveId\)/);
assert.match(files, /suspendActiveHeatCapacityModeForNavigation: \(\) => suspendActiveHeatCapacityModeForNavigation\(\)/);
assert.match(files, /activateHeatCapacityFileModeSession: \(fileId\) => activateHeatCapacityFileModeSession\(fileId\)/);
assert.match(files, /heatCapacityRefreshPersistRef, flushWorkspacePersistenceRef/);
const params = call('createWorkbenchParameterActions'); assert.match(params, /standardRuntimeRef, idealRuntimeRef, cancelRuntimeFrame, getStandardRuntime, getIdealRuntime/);
assert.match(params, /captureUndoSnapshot, updateActiveFile: \(update\) => updateActiveFile\(update\)/);
const rename = call('createWorkbenchFileRenameActions'); assert.match(rename, /getFiles: \(\) => files, getRenameDraft: \(\) => renameDraft/);
assert.match(rename, /filesRef, renamingFileIdRef, renameSelectionModeRef/);
const layout = call('createWorkbenchLayoutActions'); assert.match(layout, /createEditSnapshot, pushUndoSnapshot, captureUndoSnapshot/);
assert.match(layout, /updateActiveFile: \(update\) => updateActiveFile\(update\), setWorkbenchFiles: \(update\) => setWorkbenchFiles\(update\)/);
const scroll = call('createWorkbenchParameterScrollActions'); assert.match(scroll, /idealAdvancedScrollFrameRef/); assert.match(call('useWorkbenchParameterScroll'), /animateCurrentParametersScroll/);
assert.match(call('useWorkbenchFileMenuInteractions'), /commitRenameFileFromOutside/); call('useWorkbenchRenameFocus');
assert.match(call('createWorkbenchIdealExperimentActions'), /applyActiveFileParams: \(params\) => applyActiveFileParams\(params\)/);
console.log('Workbench action ownership wiring tests passed.');

assert.match(call('createWorkbenchHardSphereRuntimeRegistry'), /filesRef, standardRuntimeRef, idealRuntimeRef/);
assert.match(call('createWorkbenchHardSphereFrameLoop'), /desktopExitQuiescedRef, filesRef, standardRuntimeRef, idealRuntimeRef/);
assert.match(call('createWorkbenchExperimentRunActions'), /flushWorkspaceAfterRunStateCommit: \(\) => flushWorkspaceAfterRunStateCommit\(\)/);
call('useWorkbenchHardSphereRuntimeInitialization');
