import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../../src/features/workbench/WorkbenchStudioPrototype.tsx', import.meta.url), 'utf8');
const copySource = readFileSync(new URL('../../src/features/workbench/workbenchStudioCopy.ts', import.meta.url), 'utf8');
const realtimePanelSource = readFileSync(new URL('../../src/features/workbench/WorkbenchSimulationRealtimePanel.tsx', import.meta.url), 'utf8');
const verificationPanelSource = readFileSync(new URL('../../src/features/workbench/WorkbenchIdealVerificationPanel.tsx', import.meta.url), 'utf8');
const renderSource = `${source.slice(source.indexOf('const WorkbenchStudioPrototype: React.FC<WorkbenchStudioPrototypeProps>'))}\n${realtimePanelSource}\n${verificationPanelSource}`;

for (const copyField of [
  'standardRealtimeEmpty: string;',
  'undoAction: (label: string) => string;',
  'redoAction: (label: string) => string;',
  'editHistoryCleared: string;',
  'layoutSaveNeedsFile: string;',
  'layoutDefaultSaved: (name: string) => string;',
  'standardFinished: (name: string) => string;',
  'standardResultsReady: (name: string) => string;',
  'idealPointRecorded: (name: string, relation: string, value: string) => string;',
  'idealPointMissingSummary: (name: string) => string;',
  'controlledVariablesLocked: (name: string, relation: string, keys: string) => string;',
  'pauseBeforeEditingParameters: (name: string) => string;',
  'invalidParameter: (name: string, label: string, value: string) => string;',
  'pauseBeforeApplyingParameters: (name: string) => string;',
  'idealRuntimeAlreadyApplied: (name: string) => string;',
  'noSavedParameterChanges: (name: string) => string;',
  'idealRuntimeApplied: (name: string, relation: string, keys: string) => string;',
  'standardParametersApplied: (name: string, action: string) => string;',
  'runtimeCreateFailed: (name: string, kind: string) => string;',
  'standardStarted: (name: string) => string;',
  'idealStarted: (name: string, relation: string) => string;',
  'simulationPaused: (name: string, kind: string) => string;',
  'standardTerminated: (name: string) => string;',
  'idealTerminated: (name: string) => string;',
  'panelOpened: (name: string, panel: string) => string;',
  'panelClosed: (name: string, panel: string) => string;',
  'pauseBeforeSwitchingRelation: (name: string) => string;',
  'relationAlreadyActive: (name: string, relation: string) => string;',
  'relationSwitched: (name: string, relation: string) => string;',
  'pauseBeforeChangingSamplingPreset: (name: string) => string;',
  'pauseBeforeChangingScanVariable: (name: string) => string;',
  'confirmRemoveIdealPoint: (name: string, relation: string) => string;',
  'idealPointRemoved: (name: string) => string;',
  'relationHasNoPoints: (name: string, relation: string) => string;',
  'scanInputRequired: (key: string, format: string) => string;',
  'scanInputIntegerOnly: string;',
  'scanInputDecimalOnly: (key: string) => string;',
  'scanInputGreaterThanZero: (key: string) => string;',
  'scanInputStep: (label: string, step: string) => string;',
  'scanInputRange: (key: string, min: string, max: string) => string;',
  'formatPositiveInteger: string;',
  'formatDecimalNumber: string;',
]) {
  assert.ok(copySource.includes(copyField), `WorkbenchCopy should define localized ${copyField}`);
}

for (const requiredCall of [
  'workbenchCopy.results.standardRealtimeEmpty',
  'workbenchCopy.logs.standardFinished',
  'workbenchCopy.logs.standardResultsReady',
  'workbenchCopy.logs.idealPointRecorded',
  'workbenchCopy.logs.idealPointMissingSummary',
  'workbenchCopy.logs.controlledVariablesLocked',
  'workbenchCopy.logs.pauseBeforeEditingParameters',
  'workbenchCopy.logs.invalidParameter',
  'workbenchCopy.logs.pauseBeforeApplyingParameters',
  'workbenchCopy.logs.idealRuntimeAlreadyApplied',
  'workbenchCopy.logs.noSavedParameterChanges',
  'workbenchCopy.logs.idealRuntimeApplied',
  'workbenchCopy.logs.standardParametersApplied',
  'workbenchCopy.logs.runtimeCreateFailed',
  'workbenchCopy.logs.standardStarted',
  'workbenchCopy.logs.idealStarted',
  'workbenchCopy.logs.simulationPaused',
  'workbenchCopy.logs.standardTerminated',
  'workbenchCopy.logs.idealTerminated',
  'workbenchCopy.logs.panelOpened',
  'workbenchCopy.logs.panelClosed',
  'workbenchCopy.logs.pauseBeforeSwitchingRelation',
  'workbenchCopy.logs.relationAlreadyActive',
  'workbenchCopy.logs.relationSwitched',
  'workbenchCopy.logs.pauseBeforeChangingSamplingPreset',
  'workbenchCopy.logs.pauseBeforeChangingScanVariable',
  'workbenchCopy.logs.confirmRemoveIdealPoint',
  'workbenchCopy.logs.idealPointRemoved',
  'workbenchCopy.logs.relationHasNoPoints',
  'getLocalizedWorkbenchValidationErrors(validation.errors, settingsLanguagePreference)',
]) {
  const languageReactiveCall = requiredCall.replace('workbenchCopy.logs', 'workbenchCopies[language].logs');
  assert.ok(
    renderSource.includes(requiredCall) || renderSource.includes(languageReactiveCall),
    `${requiredCall} should be used by experiment UI/log logic`,
  );
}

for (const hardcodedText of [
  'Undo: ${snapshot.label}',
  'Redo: ${snapshot.label}',
  'Edit history cleared.',
  'Create or open a workbench file before saving layout defaults.',
  'Saved current ${activeFile.kind} workbench layout as the default.',
  'standard simulation finished and final chart data is ready.',
  'Results are ready. Open Results from the Panels list',
  'recorded ${getRelationLabel',
  'pressure summary was not ready for a point.',
  'controlled variables are locked while',
  'pause the simulation before editing parameters.',
  'must be a finite number.',
  'invalid parameter ${param.label}=',
  'pause the simulation before applying saved parameters.',
  'ideal runtime is already applied for the saved parameters.',
  'no saved parameter changes to apply.',
  'ideal runtime applied for',
  'runtime rebuilt and ready to run.',
  'failed to create a ${activeFile.kind} simulation runtime.',
  'standard simulation started with live 3D preview.',
  'sample run started.',
  '${activeFile.kind} simulation paused.',
  'standard simulation terminated and returned to its start state.',
  'ideal-gas simulation terminated and returned to its start state.',
  'standard runtime reset.',
  'ideal runtime reset for',
  'opened panel ${panel}',
  'closed panel ${panel}',
  'pause the current ideal run before switching relation.',
  'is already active.',
  'switched to ${getRelationLabel',
  'pause the current ideal run before changing sampling preset.',
  'pause the current ideal run before changing the scan variable.',
  'click Confirm Remove to remove this',
  'ideal experiment point removed.',
  'has no points to clear.',
  'Run the standard simulation to populate realtime chart data.',
  'Figure data',
  'prepared for desktop scientific export',
  '>{figure.status}</em>',
  'positive integer',
  'decimal number',
  'requires a ${formatName}.',
  'N only supports positive integer input.',
  'only supports ordinary decimal input.',
  'must be greater than 0.',
  "validation.errors.forEach((error) => pushLog(`${activeFile.name}: ${error}`, 'error'));",
  'minimum step is',
  'must stay between',
]) {
  assert.ok(!renderSource.includes(hardcodedText), `Experiment UI/log text should not be hardcoded as ${hardcodedText}`);
}

assert.ok(
  source.includes('const getLocalizedWorkbenchValidationErrors = ('),
  'Validation errors should have a language-aware mapping before reaching the UI and console',
);

console.log('workbenchExperimentLocalization tests passed');
