import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const appSource = readFileSync(new URL('../../src/app/App.tsx', import.meta.url), 'utf8');
const appEntrySource = readFileSync(new URL('../../src/app/index.tsx', import.meta.url), 'utf8');
const experienceSource = readFileSync(new URL('../../src/features/onboarding/FirstRunExperience.tsx', import.meta.url), 'utf8');
const introFlowSource = readFileSync(new URL('../../src/features/onboarding/WelcomeProductIntroFlow.tsx', import.meta.url), 'utf8');
const carouselSource = readFileSync(new URL('../../src/features/onboarding/ProductIntroCarousel.tsx', import.meta.url), 'utf8');
const workspaceDemoSource = readFileSync(new URL('../../src/features/onboarding/ProductIntroWorkspaceDemo.tsx', import.meta.url), 'utf8');
const modesDemoSource = readFileSync(new URL('../../src/features/onboarding/ProductIntroModesDemo.tsx', import.meta.url), 'utf8');
const modesVideoSource = readFileSync(new URL('../../src/features/onboarding/ProductIntroModesVideo.tsx', import.meta.url), 'utf8');
const modesCaptureSource = readFileSync(new URL('../../src/features/onboarding/ProductIntroGuideVideoCapturePage.tsx', import.meta.url), 'utf8');
const needsSource = readFileSync(new URL('../../src/features/onboarding/LearningNeedsPage.tsx', import.meta.url), 'utf8');
const consentSource = readFileSync(new URL('../../src/features/onboarding/MandatoryConsentDialog.tsx', import.meta.url), 'utf8');
const copySource = readFileSync(new URL('../../src/features/onboarding/firstRunCopy.ts', import.meta.url), 'utf8');
const cssSource = readFileSync(new URL('../../src/features/onboarding/FirstRunExperience.css', import.meta.url), 'utf8');
const settingsSource = readFileSync(new URL('../../src/features/workbench/WorkbenchGeneralSettingsWindow.tsx', import.meta.url), 'utf8');
const workbenchSource = readFileSync(new URL('../../src/features/workbench/WorkbenchStudioPrototype.tsx', import.meta.url), 'utf8');

assert.match(appSource, /resolveFirstRunEntryMode\(initialExperienceProfileLoad\)/);
assert.match(appSource, /entryMode === 'workbench'/);
assert.match(appSource, /<FirstRunExperience/);
assert.match(appSource, /commitFirstRunExperienceProfile\(nextProfile\)/);
assert.match(appSource, /initialTutorialEntryKind=\{tutorialEntryKind\}/);

assert.match(experienceSource, /page === 'language'/);
assert.match(experienceSource, /page === 'welcome'/);
assert.match(experienceSource, /page === 'product'/);
assert.match(experienceSource, /<WelcomeProductIntroFlow/);
assert.match(experienceSource, /<LearningNeedsPage/);
assert.match(experienceSource, /<MandatoryConsentDialog/);
assert.match(experienceSource, /welcomePlayed/);
assert.match(introFlowSource, /WELCOME_PRODUCT_REVEAL_MS = 1_420/);
assert.match(introFlowSource, /WELCOME_PRODUCT_TOTAL_MS = 1_900/);
assert.match(introFlowSource, /first-run-product-layer-visible/);
assert.match(introFlowSource, /event\.key !== 'Enter'/);

assert.match(carouselSource, /PRODUCT_INTRO_AUTOPLAY_MS/);
assert.doesNotMatch(carouselSource, /interactionPaused/);
assert.match(carouselSource, /visibilitychange/);
assert.match(carouselSource, /moveProductIntroCard\(activeIndex, nextDirection, cards\.length\)/);
assert.match(carouselSource, /phase: 'incoming' \| 'outgoing'/);
assert.match(carouselSource, /aria-pressed=\{userPaused\}/);
assert.match(carouselSource, /event\.key !== 'ArrowLeft'/);
assert.match(carouselSource, /cardIndex === 0/);
assert.match(carouselSource, /<ProductIntroWorkspaceDemo/);
assert.match(carouselSource, /<ProductIntroModesDemo/);
assert.match(carouselSource, /<ProductIntroModesVideo/);
assert.match(carouselSource, /language === 'zh-CN' && theme === 'light'/);
assert.match(carouselSource, /showWarmModesVideo/);
assert.match(carouselSource, /renderCardContent\(cards\[1\], 1, 'inactive'\)/);
assert.match(carouselSource, /first-run-product-card-header/);
assert.match(carouselSource, /first-run-product-card-heading-copy/);
assert.match(carouselSource, /first-run-product-card-body-\$\{bodyKind\}/);
assert.match(carouselSource, /data-product-intro-card-kind=\{bodyKind\}/);
assert.match(carouselSource, /first-run-product-card-details/);
assert.doesNotMatch(carouselSource, /first-run-product-heading/);
assert.match(workspaceDemoSource, /data-product-intro-workspace-demo="true"/);
assert.match(workspaceDemoSource, /PRODUCT_INTRO_WORKSPACE_DEMO_MS/);
assert.match(workspaceDemoSource, /HeatCapacityUltraInstrumentAsset/);
assert.match(workspaceDemoSource, /timelineRemainingRef = useRef\(PRODUCT_INTRO_WORKSPACE_DEMO_MS\)/);
assert.match(workspaceDemoSource, /data-product-intro-timeline-complete/);
assert.match(workspaceDemoSource, /PRODUCT_INTRO_MODEL_ROTATION_START_MS = 1_650/);
assert.match(workspaceDemoSource, /PRODUCT_INTRO_MODEL_ROTATION_DURATION_MS = 3_600/);
assert.match(workspaceDemoSource, /PRODUCT_INTRO_MODEL_ROTATION_ARC_RAD = \(60 \* Math\.PI\) \/ 180/);
assert.match(workspaceDemoSource, /window\.setInterval\(advanceRotation, 16\)/);
assert.match(workspaceDemoSource, /setModelRotationProgress\(nextProgress\)/);
assert.match(workspaceDemoSource, /data-product-intro-model-showcase-started/);
assert.match(workspaceDemoSource, /data-product-intro-model-showcase-complete/);
assert.match(workspaceDemoSource, /data-product-intro-model-rotation-progress/);
assert.match(workspaceDemoSource, /aria-hidden="true"/);
assert.match(modesDemoSource, /data-product-intro-modes-demo="true"/);
assert.match(modesDemoSource, /data-product-intro-guide-native-preview="true"/);
assert.match(modesDemoSource, /HeatCapacityInstrumentScene/);
assert.match(modesDemoSource, /className="studio-dock-header"/);
assert.match(modesDemoSource, /studio-heat-mode-control/);
assert.match(modesDemoSource, /studio-heat-guide-step-panel/);
assert.match(modesDemoSource, /data-heat-capacity-guide-step-row/);
assert.match(modesDemoSource, /HEAT_CAPACITY_STOPCOCK_OPEN_ANGLE_DEG/);
assert.match(modesDemoSource, /demoFocusControlId=\{focusedControlId\}/);
assert.match(modesDemoSource, /stepCompletedAtMs = \[1_360, 2_320, 3_460\]/);
assert.match(modesDemoSource, /atMs: 0, x: 58, y: 52/);
assert.match(modesDemoSource, /type ProductIntroMode = 'demo' \| 'guide' \| 'free'/);
assert.match(modesDemoSource, /mode\?: ProductIntroMode/);
assert.match(modesDemoSource, /demoCursorKeyframes/);
assert.match(modesDemoSource, /demoCursorHiddenAtMs = 650/);
assert.match(modesDemoSource, /mode === 'guide'\s*\? completedCount >= 1/);
assert.match(modesDemoSource, /<DemoStepPanel copy=\{copy\} stepIndex=\{demoStepIndex\} \/>/);
assert.match(modesDemoSource, /const getDemoCameraFocusState/);
assert.match(modesDemoSource, /mode: 'instrument', key: 1/);
assert.match(modesDemoSource, /mode: 'bottle', key: 2/);
assert.match(modesDemoSource, /mode: 'instrument', key: 3/);
assert.match(modesDemoSource, /const getFreeCameraFocusState/);
assert.match(modesDemoSource, /freePumpValveClickTimesMs = \[850, 3_650, 3_950\]/);
assert.match(modesDemoSource, /freePumpStrokeTimesMs = \[1_900, 2_300, 2_700, 4_820\]/);
assert.match(modesDemoSource, /demoCameraFocusMode=\{cameraFocusState\.mode\}/);
assert.match(modesDemoSource, /demoCameraFocusKey=\{cameraFocusState\.key\}/);
assert.match(modesDemoSource, /pumpPulseId=\{freePumpStrokeCount\}/);
assert.match(modesDemoSource, /controlledFocusPulseTimeSeconds/);
assert.match(modesDemoSource, /focusCueElapsedMs \/ 1_000\) \* 0\.62/);
assert.match(modesDemoSource, /PRODUCT_INTRO_MODES_DEMO_MS/);
assert.match(modesDemoSource, /elapsedRef\.current = Math\.min\(\s*PRODUCT_INTRO_MODES_DEMO_MS/);
assert.match(modesDemoSource, /data-product-intro-modes-demo-paused/);
assert.match(modesDemoSource, /hardSpherePaused=\{controlled \? false : paused \|\| !active\}/);
assert.match(modesDemoSource, /onSceneReady=\{\(\) => setSceneReady\(true\)\}/);
assert.doesNotMatch(modesDemoSource, /SharedModesRenderer|gl\.setScissor|<Canvas/);
assert.doesNotMatch(modesDemoSource, /sensor-preheat|5\s*s/);
assert.match(carouselSource, /theme=\{theme\}/);
assert.match(carouselSource, /key=\{`product-card-\$\{cardIndex\}`\}/);
assert.match(carouselSource, /const cardPlaybackActive = active/);
assert.match(carouselSource, /phase === 'outgoing' \|\| \(phase === 'incoming' && outgoingIndex === null\)/);
assert.match(carouselSource, /PRODUCT_INTRO_CONTENT_TRANSITION_MS = 450/);
assert.match(carouselSource, /transitionTimerRef\.current = window\.setTimeout/);
assert.doesNotMatch(carouselSource, /requestAnimationFrame\(advanceTransition\)/);
assert.match(carouselSource, /outgoingIndex !== null/);
assert.match(modesVideoSource, /product-intro-demo-guide\.zh-CN\.mp4/);
assert.match(modesVideoSource, /data-product-intro-modes-video-layout="demo-guide-free"/);
assert.match(modesVideoSource, /first-run-modes-video-captions/);
assert.match(modesVideoSource, /first-run-modes-learning-path/);
assert.match(modesVideoSource, /copy\.learningObserve/);
assert.match(modesVideoSource, /video\.pause\(\)/);
assert.match(modesVideoSource, /video\.play\(\)/);
assert.match(modesVideoSource, /video\.currentTime = 0/);
assert.match(modesVideoSource, /onEnded/);
assert.match(modesCaptureSource, /controlledElapsedMs=\{elapsedMs\}/);
assert.match(modesCaptureSource, /mode="demo"/);
assert.match(modesCaptureSource, /mode="guide"/);
assert.match(modesCaptureSource, /mode="free"/);
assert.match(appEntrySource, /import\.meta\.env\.DEV/);
assert.match(appEntrySource, /productIntroCapture/);
assert.match(appEntrySource, /import\('\.\.\/features\/onboarding\/ProductIntroGuideVideoCapturePage\.tsx'\)/);

assert.match(copySource, /您是否了解本软件绝热膨胀法实验的操作逻辑？/);
assert.doesNotMatch(copySource, /是否了解软件总体 UI/);
assert.doesNotMatch(copySource, /是否了解本软件.*活塞振动/);
assert.match(needsSource, /disabled=\{answer === null\}/);
assert.match(needsSource, /role="radiogroup"/);

assert.match(consentSource, /dismiss=\{\{ closeButton: false, escape: false, backdrop: false \}\}/);
assert.match(consentSource, /isMandatoryConsentReady/);
assert.match(consentSource, /document\.visibilityState === 'visible'/);
assert.match(consentSource, /activeMaterialId !== null/);
assert.match(consentSource, /mainScrollTopRef/);
assert.match(copySource, /不同意并退出/);
assert.match(copySource, /我已阅读并知悉/);

assert.match(cssSource, /border-radius: 4px/);
assert.match(cssSource, /@keyframes firstRunWelcomeReveal/);
assert.match(cssSource, /\.first-run-product-card-content-outgoing/);
assert.match(cssSource, /\.first-run-product-card-content-incoming \{\s*z-index: 1;/);
assert.match(cssSource, /\.first-run-product-card-content-outgoing \{\s*z-index: 2;/);
assert.match(cssSource, /\.first-run-product-card-header \{[\s\S]*height: 92px;/);
assert.match(cssSource, /\.first-run-product-card-heading-copy h2 \{[\s\S]*font-family: var\(--app-font-product-title\);/);
assert.match(cssSource, /\.first-run-product-card-body \{/);
assert.match(cssSource, /@keyframes firstRunWorkspaceCursor/);
assert.match(cssSource, /@keyframes firstRunWorkspaceLoadedEnter/);
assert.match(cssSource, /width: min\(1320px, calc\(100% - 8px\)\)/);
assert.match(cssSource, /\.first-run-product-card-body-text/);
assert.match(cssSource, /\.first-run-guide-native-demo/);
assert.match(cssSource, /\.first-run-guide-native-panel\.studio-dock-panel/);
assert.match(cssSource, /aspect-ratio: 7 \/ 5/);
assert.match(cssSource, /\.first-run-guide-native-checklist/);
assert.match(cssSource, /\.first-run-guide-native-cursor/);
assert.match(cssSource, /\.first-run-guide-native-click-ring/);
assert.match(cssSource, /\.first-run-guide-native-panel \.studio-heat-focus-panel-instrument/);
assert.match(cssSource, /\.first-run-guide-native-panel \.studio-heat-focus-panel-pump/);
assert.match(cssSource, /\.first-run-guide-video-surface/);
assert.match(cssSource, /\.first-run-modes-video-demo/);
assert.match(cssSource, /aspect-ratio: 1464 \/ 400/);
assert.match(cssSource, /\.first-run-modes-learning-path/);
assert.match(cssSource, /\.first-run-modes-learning-path-sequence/);
assert.match(cssSource, /@keyframes firstRunProductCardEnterNext/);
assert.match(cssSource, /@keyframes firstRunProductCardExitNext/);
assert.match(cssSource, /\.mandatory-consent-window/);
assert.doesNotMatch(cssSource, /linear-gradient/);

assert.match(settingsSource, /onReplayProductIntro/);
assert.match(settingsSource, /onReselectLearningNeeds/);
assert.match(settingsSource, /showSimulateFirstRun \?/);
assert.match(workbenchSource, /prepareDesktopExitQuiescenceRef\.current\(\)/);
assert.match(workbenchSource, /prepareDesktopExitQuiescenceRef\.current\(false\)/);
assert.match(workbenchSource, /if \(!desktopExitInputBlockedRef\.current\) return;/);
assert.match(workbenchSource, /aria-busy=\{desktopExitInputBlocked\}/);
assert.match(workbenchSource, /resumeDesktopExitQuiescenceRef\.current\(\)/);
assert.match(workbenchSource, /import\.meta\.env\.DEV/);
assert.match(workbenchSource, /APP_EXPERIENCE_PROFILE_STORAGE_KEY/);

console.log('firstRunExperienceUi tests passed');
