import { PRODUCT_INTRO_CONTENT_PLAYBACK_RATE } from './productIntroCarouselModel.ts';

export const PRODUCT_INTRO_OUTCOME_CALCULATION_PLAYBACK_RATE = PRODUCT_INTRO_CONTENT_PLAYBACK_RATE;
export const PRODUCT_INTRO_OUTCOME_REVIEW_PLAYBACK_MULTIPLIER = 1.3;
export const PRODUCT_INTRO_OUTCOME_REVIEW_PLAYBACK_RATE = Number(
  (
    PRODUCT_INTRO_OUTCOME_CALCULATION_PLAYBACK_RATE
    * PRODUCT_INTRO_OUTCOME_REVIEW_PLAYBACK_MULTIPLIER
  ).toFixed(2),
);

export const PRODUCT_INTRO_OUTCOME_TRANSITION_START_MS = 3_600;
export const PRODUCT_INTRO_OUTCOME_TRANSITION_DURATION_MS = 300;
export const PRODUCT_INTRO_OUTCOME_TRANSITION_END_MS = PRODUCT_INTRO_OUTCOME_TRANSITION_START_MS
  + PRODUCT_INTRO_OUTCOME_TRANSITION_DURATION_MS;
export const PRODUCT_INTRO_OUTCOME_REPORT_SCROLL_START_MS = 4_300;
export const PRODUCT_INTRO_OUTCOME_REPORT_SCROLL_END_MS = 6_500;
export const PRODUCT_INTRO_OUTCOME_REPORT_EXPAND_START_MS = 7_150;
export const PRODUCT_INTRO_OUTCOME_REPORT_EXPAND_END_MS = 7_950;
export const PRODUCT_INTRO_OUTCOME_FINAL_HOLD_MS = 1_550;
export const PRODUCT_INTRO_OUTCOME_DURATION_MS = PRODUCT_INTRO_OUTCOME_REPORT_EXPAND_END_MS
  + PRODUCT_INTRO_OUTCOME_FINAL_HOLD_MS;

export const getProductIntroOutcomePlaybackRate = (currentTimeSeconds: number) => (
  currentTimeSeconds >= PRODUCT_INTRO_OUTCOME_TRANSITION_END_MS / 1_000
    ? PRODUCT_INTRO_OUTCOME_REVIEW_PLAYBACK_RATE
    : PRODUCT_INTRO_OUTCOME_CALCULATION_PLAYBACK_RATE
);
