import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const componentPath = join(process.cwd(), 'components', 'heatCapacity', 'HeatCapacityInstrumentScene.tsx');
const leftPanelPath = join(process.cwd(), 'components', 'heatCapacity', 'HeatCapacityLeftPanel.tsx');
const workbenchPath = join(process.cwd(), 'components', 'WorkbenchStudioPrototype.tsx');
const statePath = join(process.cwd(), 'components', 'workbenchState.ts');
const stylePath = join(process.cwd(), 'components', 'WorkbenchStudioPrototype.css');

assert.equal(existsSync(componentPath), true, 'heatCapacity instrument scene component should exist');

const sceneSource = readFileSync(componentPath, 'utf8');
const leftPanelSource = readFileSync(leftPanelPath, 'utf8');
const stateSource = readFileSync(statePath, 'utf8');
const styleSource = readFileSync(stylePath, 'utf8');
assert.match(sceneSource, /@react-three\/fiber/);
assert.match(sceneSource, /@react-three\/drei/);
assert.doesNotMatch(sceneSource, /<Html[\s\S]*(TemperatureDisplay|PressureDisplay|FD-NCD-C|INPUT|PRESS IN)/, 'instrument panel labels should not use camera-facing Html overlays');
assert.match(sceneSource, /CanvasTexture/, 'instrument panel labels should use 3D canvas textures attached to the instrument face');
assert.match(sceneSource, /new THREE\.CanvasTexture\(canvas\)[\s\S]*\}, \[\]\)/, 'instrument panel text should create one stable CanvasTexture instead of recreating it for every readout change');
assert.match(sceneSource, /window\.setTimeout\(drawTexture, updateIntervalMs - elapsedMs\)/, 'instrument panel text should throttle canvas texture redraws');
assert.match(sceneSource, /performanceMode=\{props\.performanceMode\}/, 'heat-capacity scene content should receive the global performance mode');
assert.match(sceneSource, /performanceMode:\s*'standard' \| 'balanced' \| 'performance'/, 'heat-capacity scene should accept all three performance tiers');
assert.match(sceneSource, /props\.performanceMode === 'performance'\s*\?\s*\[1,\s*1\]/, 'performance tier should keep DPR at or above 1 to avoid blur');
assert.match(sceneSource, /props\.performanceMode === 'balanced'\s*\?\s*\[1,\s*1\.15\]/, 'balanced tier should reduce DPR mildly without obvious blur');
assert.match(sceneSource, /const panelTextUpdateIntervalMs = performanceMode === 'performance'[\s\S]*500[\s\S]*performanceMode === 'balanced'[\s\S]*350/, 'digital screen refresh should use three performance tiers');
assert.doesNotMatch(sceneSource, /\[0\.75,\s*1\]/, 'performance mode should no longer use sub-1 DPR that blurs the scene');
assert.match(sceneSource, /texture\.dispose\(\)/, 'instrument panel text should dispose GPU texture resources on unmount');
assert.match(sceneSource, /<planeGeometry args=\{\[0\.46, 0\.115\]\}/, 'instrument panel labels should be rendered as face-mounted planes');
assert.match(sceneSource, /onPowerToggle/);
assert.match(sceneSource, /interactionLocked: boolean/, 'instrument scene should receive an interaction lock during auto demo');
assert.match(sceneSource, /language: 'zh-CN' \| 'zh-TW' \| 'en'/, 'instrument scene should receive the current language');
assert.match(sceneSource, /heatCapacitySceneCopies/, 'instrument scene should localize its internal labels and hints');
assert.match(sceneSource, /getHeatCapacityInteractionHints\(focusMode, sceneCopy\)/, 'instrument hints should use localized copy');
assert.match(sceneSource, /getHeatCapacityHoverTooltip\(hoveredControl, props\.pumpValveOpen, sceneCopy\)/, 'hover tooltips should use localized copy');
assert.match(sceneSource, /demoFocusControlId/, 'instrument scene should receive the current auto-demo focus target');
assert.match(sceneSource, /onLockedInteraction/, 'instrument scene should surface locked user interaction attempts');
assert.match(sceneSource, /DemoFocusHalo/, 'auto demo should render a soft focus halo before operating controls');
assert.match(sceneSource, /onStopcockOpenChange/, 'instrument scene should expose a two-state stopcock open/closed action');
assert.doesNotMatch(sceneSource, /onStopcockAngleChange/, 'stopcock should no longer expose a continuous angle-change API to the UI');
assert.doesNotMatch(sceneSource, /onPressureZero\b/, 'pressure-zero knob should not expose a one-click zero action');
assert.match(sceneSource, /onPressureZeroFineAdjust/, 'instrument scene should expose pressure zero fine wheel adjustment');
assert.match(sceneSource, /onPressureZeroCoarseAdjust/, 'instrument scene should expose pressure zero coarse drag adjustment');
assert.match(sceneSource, /GLB replacement contract/i);
assert.match(sceneSource, /name="SensorStopperPort"/);
assert.match(sceneSource, /name="StopcockDownTube"/);
assert.match(sceneSource, /name="pumpAssembly"/, 'external pump assembly should have a stable GLB replacement root');
assert.match(sceneSource, /name="pumpPortOnStopper"/, 'stopper should expose an independent pump port');
assert.match(sceneSource, /name="pumpTube"/, 'pump tube should connect the stopper pump port to the external bulb');
assert.match(sceneSource, /name="pumpValve"/, 'pump valve should sit near the stopper-side pump route');
assert.match(sceneSource, /name="pumpValveHandle"/, 'pump valve should expose a handle for open/closed interaction');
assert.match(sceneSource, /name="pumpBulb"/, 'external pump bulb should exist');
assert.match(sceneSource, /name="pumpBulbHitbox"/, 'pump bulb should expose an independent click target');
assert.match(sceneSource, /name="pumpPortOnStopper" position=\{\[-1\.72, 0\.9, 0\.26\]\}/, 'pump port should move to the left side of the stopper');
assert.match(sceneSource, /name="pumpShortConnectorIn"/, 'pump route should include a short inlet connector before the inline valve body');
assert.match(sceneSource, /name="pumpShortConnectorOut"/, 'pump route should include a short outlet connector after the inline valve body');
assert.match(sceneSource, /name="pumpValveBody"/, 'pump valve body should be the fixed inline segment of the pump route');
assert.match(sceneSource, /name="pumpPortOnStopper"[\s\S]*name="pumpShortConnectorIn"[\s\S]*name="pumpValve"[\s\S]*name="pumpValveBody"[\s\S]*name="pumpShortConnectorOut"[\s\S]*name="pumpTube"/, 'pump route should read as stopper port -> inlet connector -> inline valve -> outlet connector -> tube');
assert.match(sceneSource, /name="pumpValve"[\s\S]*position=\{\[-1\.72, 0\.9, 0\.54\]\}/, 'inline valve should sit on the same local centerline as the stopper pump port and tube inlet');
assert.match(sceneSource, /name="pumpValveBody"[\s\S]*rotation=\{\[Math\.PI \/ 2, 0, 0\]\}/, 'inline valve body should be aligned with the pump tube axis rather than attached as a side decoration');
assert.match(sceneSource, /name="pumpValveHandle" position=\{\[0, 0, 0\]\} rotation=\{\[0, valveHandleAngle(?: \+ valveRollbackOffset)?, 0\]\}/, 'inline valve handle should rotate around the valve body center without moving the valve body');
assert.match(sceneSource, /name="pumpTube"[\s\S]*\[-1\.72, 0\.9, 0\.74\]/, 'pump tube should start from the inline valve outlet, not bypass the valve from the stopper port');
assert.match(sceneSource, /\[-2\.18, 0\.72, 0\.92\][\s\S]*\[-2\.18, -0\.3, 1\.52\][\s\S]*\[1\.66, -0\.98, 1\.08\]/, 'pump tube should route around the outside before reaching the bulb');
assert.match(sceneSource, /name="pumpTube"[\s\S]*lineWidth=\{8\}/, 'pump tube should be visibly thicker than temperature and pressure leads');
assert.match(sceneSource, /name="pumpValveBody"/, 'pump valve should use a recognizable metal ball-valve body');
assert.match(sceneSource, /name="pumpValveWingHandle"/, 'pump valve should use a wing or lever handle instead of a plain block');
assert.match(sceneSource, /name="pumpValveStateBadge"/, 'pump valve should expose a local open-closed status badge without repainting the whole body');
assert.match(sceneSource, /setValveHandleAngle/, 'pump valve handle should animate smoothly between open and closed states');
assert.match(sceneSource, /PUMP_VALVE_TRANSITION_MS = 420/, 'pump valve demo/manual animation should remain visibly smooth');
assert.match(sceneSource, /const scale = 1\.06 \+ pulse \* 0\.14/, 'auto demo focus halo should be more visible than the first subtle pass');
assert.match(sceneSource, /materialRef\.current\.opacity = 0\.24 \+ pulse \* 0\.28/, 'auto demo focus halo should breathe with a stronger opacity range');
assert.match(sceneSource, /name="pumpValveHandle" position=\{\[0, 0, 0\]\} rotation=\{\[0, valveHandleAngle(?: \+ valveRollbackOffset)?, 0\]\}/, 'pump valve handle should rotate around its own vertical center axis in a horizontal plane');
assert.match(sceneSource, /name="pumpValveWingHandle" position=\{\[0, 0\.18, 0\]\}/, 'pump valve wing should sit above the fixed inline body while rotating around the valve body center axis');
assert.doesNotMatch(sceneSource, /name="pumpValveHandle"[\s\S]{0,120}rotation=\{\[0, 0, valveHandleAngle\]\}/, 'pump valve handle should not flip around the screen-facing Z axis');
assert.match(sceneSource, /onPumpValveToggle/, 'instrument scene should receive pump valve state updates from the workbench');
assert.match(sceneSource, /onPumpBulbPress/, 'instrument scene should report pump bulb presses to the workbench state');
assert.match(sceneSource, /pumpPulseId: number/, 'pump bulb visual feedback should receive a UI-only retrigger signal');
assert.match(sceneSource, /pumpPulseId=\{props\.pumpPulseId\}/, 'pump pulse signal should reach the pump assembly without being persisted in experiment state');
assert.match(sceneSource, /focusMode=\{props\.focusMode\}/, 'pump assembly should know whether it is in pump focus mode');
assert.match(sceneSource, /onPointerDown=\{focusMode === 'pump' \? handlePumpBulbPointerDown : undefined\}/, 'pump focus mode should use pointer down for rapid pump clicks');
assert.match(sceneSource, /if \(focusMode === 'pump'\) return;/, 'pump focus mode click events should not be filtered by click detail or double count after pointer down');
assert.doesNotMatch(sceneSource, /name="pumpBulb"[\s\S]*onClick=\{\(event\) => \{[\s\S]*onPumpBulbPress\(\);[\s\S]*onDoubleClick/, 'single-clicking the pump bulb outside pump focus should not trigger an effective pump stroke');
assert.match(sceneSource, /focusMode === 'pump'/, 'double-clicking the pump assembly should enter a dedicated pump focus view');
assert.match(sceneSource, /name="pumpBulb"[\s\S]*onDoubleClick/, 'double-clicking the pump bulb should enter the pump focus panel directly');
assert.doesNotMatch(sceneSource, /name="pumpBulb"[\s\S]{0,260}nativeEvent as MouseEvent\)\.detail > 1[\s\S]{0,120}onPumpBulbPress/, 'pump focus mode should not lose rapid clicks through native click-detail filtering');
assert.match(sceneSource, /name="pumpValve"[\s\S]*onFocus\('pump'\)/, 'double-clicking the pump valve should enter the dedicated pump focus view');
assert.match(sceneSource, /data-heat-capacity-pump-valve-toggle="true"/, 'pump focus view should expose a direct pump valve toggle without using the stopcock handler');
assert.match(sceneSource, /setHoveredControl\('pumpBulb'\)/, 'pump bulb should expose hover feedback');
assert.match(sceneSource, /setHoveredControl\('pumpValve'\)/, 'pump valve should expose hover feedback');
assert.match(sceneSource, /setHoveredControl\('stopcock'\)/, 'stopcock handle should expose hover feedback for two-state switching');
assert.match(sceneSource, /setHoveredControl\('powerSwitch'\)/, 'power switch should expose hover feedback');
assert.match(sceneSource, /setHoveredControl\('pressureZero'\)/, 'pressure zero knob should expose hover feedback');
assert.match(sceneSource, /点击切换玻璃旋塞状态|Click to toggle the glass stopcock/, 'stopcock hover tooltip should describe only the two-state click interaction');
assert.match(sceneSource, /Pump valve: click to toggle|打气阀门：点击切换/, 'pump valve hover tooltip should name the control before explaining interaction');
assert.match(sceneSource, /Pump bulb: enter focus|打气球：聚焦/, 'pump bulb hover tooltip should name the control before explaining interaction');
assert.match(sceneSource, /Power switch: click to toggle power|电源开关：点击/, 'power switch hover tooltip should name the control before explaining interaction');
assert.match(sceneSource, /Pressure-zero knob: drag for coarse adjustment \/ wheel for fine adjustment|压力调零旋钮：拖拽粗调/, 'pressure zero hover tooltip should name the control before explaining coarse drag and fine wheel');
assert.match(sceneSource, /handlePressureZeroWheel/, 'pressure zero knob should support wheel fine adjustment');
assert.match(sceneSource, /startPressureZeroDrag/, 'pressure zero knob should support drag coarse adjustment');
assert.match(sceneSource, /PRESSURE_ZERO_FINE_ANGLE_STEP_DEG/, 'pressure zero fine adjustment should have a tunable angle step');
assert.match(sceneSource, /PRESSURE_ZERO_DRAG_DIRECTION = -1/, 'pressure zero drag should use an explicit direction factor for the current oblique view');
assert.doesNotMatch(sceneSource, /pressureZeroKnobAngle\s*%|pressureZeroKnobAngle[\s\S]{0,80}normalizeDisplayAngle/, 'pressure zero knob should not use modulo-style angle wraparound');
assert.match(sceneSource, /HEAT_CAPACITY_PRESSURE_ZERO_KNOB_ANGLE_MIN_DEG/, 'pressure zero scene interactions should import the physical lower stop');
assert.match(sceneSource, /HEAT_CAPACITY_PRESSURE_ZERO_KNOB_ANGLE_MAX_DEG/, 'pressure zero scene interactions should import the physical upper stop');
assert.match(sceneSource, /clampPressureZeroSceneKnobAngle/, 'pressure zero scene interactions should clamp visual interaction at physical stops');
assert.match(sceneSource, /const requestedKnobAngle = pressureZeroKnobAngle \+ requestedDelta/, 'pressure zero wheel interaction should calculate the requested physical knob angle');
assert.match(sceneSource, /const nextKnobAngle = clampPressureZeroSceneKnobAngle\(requestedKnobAngle\)/, 'pressure zero wheel interaction should stop dispatching once it reaches a physical stop');
assert.match(sceneSource, /const requestedKnobAngle = dragState\.startKnobAngle \+ dragState\.totalDelta/, 'pressure zero drag should derive requested angle from the drag start angle and continuous pointer delta');
assert.match(sceneSource, /const nextKnobAngle = clampPressureZeroSceneKnobAngle\(requestedKnobAngle\)/, 'pressure zero drag should clamp the requested angle before dispatching scene updates');
assert.match(sceneSource, /已到调节上限|Upper adjustment limit reached/, 'pressure zero interaction should show a restrained toast at the upper physical stop');
assert.match(sceneSource, /已到调节下限|Lower adjustment limit reached/, 'pressure zero interaction should show a restrained toast at the lower physical stop');
assert.match(sceneSource, /onLockedInteraction\(limitMessage\)/, 'pressure zero limit feedback should reuse the bottom-centered model-window toast path');
assert.doesNotMatch(sceneSource, /appliedDelta/, 'pressure zero drag should not use unbounded circular applied deltas');
assert.match(stateSource, /HEAT_CAPACITY_PRESSURE_ZERO_KNOB_ANGLE_MIN_DEG = -540/, 'pressure zero knob should expose a three-turn physical lower stop');
assert.match(stateSource, /HEAT_CAPACITY_PRESSURE_ZERO_KNOB_ANGLE_MAX_DEG = 540/, 'pressure zero knob should expose a three-turn physical upper stop');
assert.match(stateSource, /HEAT_CAPACITY_PRESSURE_ZERO_TOLERANCE_MV = 0\.1/, 'pressure zero readiness should use the strict +-0.1 mV tolerance');
assert.match(stateSource, /pressureInitialBiasMv/, 'heat-capacity state should keep the per-run initial zero bias');
assert.match(stateSource, /pressureZeroDisplayedSamples/, 'heat-capacity state should keep a displayed U_p zeroing window');
assert.match(stateSource, /createHeatCapacityInitialPressureBiasMv/, 'initial pressure-zero bias should be generated through one helper');
assert.match(stateSource, /isHeatCapacityPressureZeroWithinTolerance/, 'U0 readiness should be based on the displayed sample window');
assert.doesNotMatch(stateSource, /HEAT_CAPACITY_MANUAL_INITIAL_PRESSURE_BIAS_MV\s*=\s*0\.6/, 'manual experiments must not use the old fixed +0.6 mV zero bias');
assert.doesNotMatch(stateSource, /Math\.abs\(file\.pressureDisplayedPlaceholder\)\s*<=\s*0\.2/, 'U0 readiness must not use the old loose <=0.2 mV gate');
assert.match(stateSource, /clampHeatCapacityPressureZeroKnobAngle/, 'pressure zero knob angle changes should clamp at physical stops');
assert.match(stateSource, /getHeatCapacityPressureZeroOffsetForKnobAngle/, 'pressure zero offset should be derived from a continuous angle-to-offset mapping');
assert.match(sceneSource, /pressureZeroInteractionEnabled = focusMode === 'instrument'/, 'pressure zero knob should only rotate in instrument focus mode');
assert.match(sceneSource, /onPointerDown=\{pressureZeroInteractionEnabled \? startPressureZeroDrag : undefined\}/, 'pressure zero drag should be disabled outside instrument focus mode');
assert.match(sceneSource, /onWheel=\{pressureZeroInteractionEnabled \? handlePressureZeroWheel : undefined\}/, 'pressure zero wheel adjustment should be disabled outside instrument focus mode');
assert.match(sceneSource, /name="PressureZeroKnobBody"/, 'pressure zero knob should use a named industrial knob body');
assert.match(sceneSource, /name="PressureZeroKnobFace"/, 'pressure zero knob should expose a distinct front face');
assert.match(sceneSource, /name="PressureZeroKnobCenter"/, 'pressure zero knob should show a clear centered hub');
assert.match(sceneSource, /name="PressureZeroIndicatorLine"/, 'pressure zero knob should use one clear centered indicator line');
assert.match(sceneSource, /name="PressureZeroScaleTick"/, 'pressure zero knob should have simple fixed reference ticks around it');
assert.match(sceneSource, /name="PressureZeroIndicatorGroup" rotation=\{\[0, 0, THREE\.MathUtils\.degToRad\(pressureZeroKnobAngle(?: \+ pressureZeroRollbackOffsetDeg)?\)\]\}[\s\S]*name="PressureZeroIndicatorLine"/, 'pressure zero indicator line should rotate as one centered group');
assert.doesNotMatch(sceneSource, /name="PressureZeroDirectionMark"/, 'pressure zero knob should not keep the old second off-center direction mark');
assert.doesNotMatch(sceneSource, /pressureZeroed=\{props\.pressureZeroed\}/, '3D scene should not keep the obsolete pressureZeroed visual prop path');
assert.doesNotMatch(sceneSource, /setHoveredControl\('instrument'\)/, 'instrument front panel should not expose a hover prompt');
assert.match(sceneSource, /name="StopcockRodHandleHoverHalo"/, 'stopcock hover should use a soft halo instead of a stark white edge');
assert.match(sceneSource, /name="PowerSwitchHoverHalo"/, 'power switch hover should use a soft halo instead of a stark white edge');
assert.match(sceneSource, /name="PressureZeroHoverHalo"/, 'pressure zero hover should use a soft halo instead of a stark white edge');
assert.match(sceneSource, /NON_BULB_HOVER_EMISSIVE_INTENSITY = 0\.26/, 'non-bulb hover glow should be stronger than the first subtle pass');
assert.match(sceneSource, /NON_BULB_HOVER_HALO_OPACITY = 0\.22/, 'non-bulb hover halos should be visibly stronger than the first subtle pass');
assert.doesNotMatch(sceneSource, /name="InstrumentFaceHoverSheen"/, 'instrument front panel should not glow on hover');
assert.doesNotMatch(sceneSource, /hoveredControl === 'instrument'/, 'instrument front panel should not keep a hover state branch');
assert.doesNotMatch(sceneSource, /instrumentHovered \? <Edges color="#dbeafe"/, 'instrument hover should not rely on a stark edge outline');
assert.doesNotMatch(sceneSource, /powerSwitchHovered \? <Edges color="#ecfeff"/, 'power switch hover should not rely on a stark edge outline');
assert.doesNotMatch(sceneSource, /pressureZeroHovered \? <Edges color="#ecfeff"/, 'pressure zero hover should not rely on a stark edge outline');
assert.doesNotMatch(sceneSource, /stopcockHovered \? <Edges color="#ecfeff"/, 'stopcock hover should not rely on a stark edge outline');
assert.match(sceneSource, /getHeatCapacityInteractionHints/, '3D scene should show mode-specific interaction hints');
assert.match(sceneSource, /data-heat-capacity-interaction-hints="true"/, 'interaction hint panel should be rendered in the scene chrome');
assert.match(sceneSource, /getHeatCapacityHoverTooltip/, 'hovered controls should expose compact tooltips');
assert.match(sceneSource, /data-heat-capacity-hover-tooltip="true"/, 'hover tooltip should be rendered when an interactive control is hovered');
assert.doesNotMatch(sceneSource, /STOPCOCK_WHEEL_STEP_DEG/, 'stopcock wheel adjustment should be removed from user interaction');
assert.doesNotMatch(sceneSource, /handleStopcockWheel/, 'stopcock handle should not support wheel-based angle adjustment');
assert.doesNotMatch(sceneSource, /onWheel=\{handleStopcockWheel\}/, 'wheel events over the stopcock should no longer adjust the valve');
assert.match(sceneSource, /onStopcockOpenChange\(state !== 'open'\)/, 'clicking the stopcock should toggle the open/closed state directly');
assert.match(sceneSource, /HOVER_CLEAR_DELAY_MS = 220/, 'hover state should use a short grace period to avoid cursor flicker on projected 3D boundaries');
assert.match(sceneSource, /hoverClearTimerRef/, 'hover state should cancel pending hover clears when entering adjacent meshes');
assert.match(sceneSource, /setStableHoveredControl/, 'hover updates should go through a stable boundary helper');
assert.match(sceneSource, /raycast=\{DISABLE_RAYCAST\}/, 'decorative hover halos should not compete with interaction hitboxes');
assert.doesNotMatch(sceneSource, /name="HitboxStopcockHandle" visible=\{false\}/, 'stopcock hitbox should remain raycastable instead of being invisible to raycaster');
assert.match(sceneSource, /name="HitboxStopcockHandle"[\s\S]*<boxGeometry args=\{\[1\.02, 0\.72, 0\.34\]\}/, 'stopcock hitbox should stay tight enough not to overlap the pump valve hitbox');
assert.doesNotMatch(sceneSource, /name="HitboxPowerSwitch" visible=\{false\}/, 'power switch hitbox should remain raycastable instead of being invisible to raycaster');
assert.doesNotMatch(sceneSource, /name="HitboxPressureZeroKnob" visible=\{false\}/, 'pressure zero hitbox should remain raycastable instead of being invisible to raycaster');
assert.doesNotMatch(sceneSource, /name="pumpValveHitbox" visible=\{false\}/, 'pump valve hitbox should remain raycastable instead of being invisible to raycaster');
assert.doesNotMatch(sceneSource, /name="pumpBulbHitbox" visible=\{false\}/, 'pump bulb hitbox should remain raycastable instead of being invisible to raycaster');
assert.match(sceneSource, /pumpBulbScale/, 'pump bulb should animate through compression and release scale changes');
assert.match(sceneSource, /\? \[1\.08, 0\.7, 1\.06\][\s\S]*\? \[1\.02, 0\.92, 1\.01\]/, 'pump bulb should compress and reinflate without jelly-like overshoot');
assert.match(sceneSource, /name="pumpBulbStatusHalo"/, 'pump bulb active feedback should be an added halo, not a flat color replacement');
assert.doesNotMatch(sceneSource, /tooFast/, 'pump feedback must not introduce a too-fast state');
assert.match(sceneSource, /name="pumpValve"[\s\S]*onPointerDown=\{\(event\) => \{[\s\S]*stopImmediatePropagation/, 'pump valve pointer events should not bubble into neighboring controls');
assert.match(sceneSource, /name="pumpValve"[\s\S]*onClick=\{\(event\) => \{[\s\S]*onPumpValveToggle\(\)/, 'pump valve click path should only toggle the pump valve');
assert.doesNotMatch(sceneSource, /name="pumpValve"[\s\S]{0,420}onStopcockOpenChange/, 'pump valve click path must not call the stopcock action');
assert.match(
  sceneSource,
  /name="AnalogPressureGauge"[\s\S]*name="AnalogPressureGaugeDial"[\s\S]*rotation=\{\[Math\.PI \/ 2, 0, 0\]\}/,
  'analog pressure gauge dial should be vertical on the instrument face',
);
assert.match(sceneSource, /PRESSURE_GAUGE_TICKS/, 'analog pressure gauge should expose visible dial ticks');
assert.match(sceneSource, /PRESSURE_GAUGE_DANGER_MARKERS/, 'analog pressure gauge should render a threshold-derived danger area');
assert.match(sceneSource, /mapPressureGaugeValueToRotation/, 'analog pressure gauge should use a linear clamp mapping from pressure to angle');
assert.match(sceneSource, /getPressureGaugeNeedleRotation/, 'analog pressure gauge should derive needle rotation from pressure data');
assert.match(sceneSource, /gaugePressureMinKPa: number/, 'instrument scene should receive gauge min pressure for gauge data binding');
assert.match(sceneSource, /gaugePressureMaxKPa: number/, 'instrument scene should receive gauge max pressure for gauge data binding');
assert.match(sceneSource, /pressureSafetyThresholdKPa: number/, 'instrument scene should receive pressure safety threshold for warning and danger-area alignment');
assert.match(sceneSource, /useFrame[\s\S]*gaugeNeedlePivotRef\.current\.rotation\.z/, 'analog pressure gauge needle should smoothly track the mapped target angle');
assert.match(sceneSource, /name="TemperaturePositiveInputTerminal"/, 'instrument host should show the red temperature input terminal below the left display');
assert.match(sceneSource, /name="TemperatureNegativeInputTerminal"/, 'instrument host should show the black temperature input terminal below the left display');
assert.match(sceneSource, /name="PressureSensorInputPort"/, 'instrument host should show one central metal pressure sensor input below the pressure display');
assert.match(sceneSource, /name="TemperaturePositiveLead"/, 'temperature positive lead should connect the sensor area to the red terminal');
assert.match(sceneSource, /name="TemperatureNegativeLead"/, 'temperature negative lead should connect the sensor area to the black terminal');
assert.match(sceneSource, /name="PressureSensorLead"/, 'pressure sensor lead should connect the side gas/pressure area to the central pressure port');
assert.match(sceneSource, /name="ExternalTemperatureLeadAnchor"/, 'temperature leads should route outside the glass vessel before entering the stopper');
assert.match(sceneSource, /name="ExternalPressureLeadAnchor"/, 'pressure lead should route outside the glass vessel before reaching the side pressure pickup');
assert.match(sceneSource, /name="SharedServiceCablePort" position=\{\[0\.2, 1\.17, 0\.36\]\}/, 'temperature and pressure connections should share one small rear-right cable/service port on top of the stopper');
assert.match(sceneSource, /name="ServicePortBundleAnchor" position=\{\[-1\.1, 0\.92, 1\.1\]\}/, 'all external leads should first leave the bottle assembly through a shared rear route');
assert.doesNotMatch(sceneSource, /name="SensorRearCableOutlet"/, 'old dedicated sensor wire outlet should be replaced by the shared service port');
assert.doesNotMatch(sceneSource, /name="SensorSurfaceLeadGroove"/, 'old dedicated sensor surface groove should be replaced by the shared service port');
assert.match(sceneSource, /name="TemperaturePositiveLead"[\s\S]*\[-1\.1, 0\.89, 0\.36\][\s\S]*\[-1\.1, 0\.92, 1\.1\][\s\S]*\[1\.12, -0\.62, 0\.51\]/, 'positive temperature lead should run from the shared service port to the red host input');
assert.match(sceneSource, /name="TemperatureNegativeLead"[\s\S]*\[-1\.08, 0\.885, 0\.38\][\s\S]*\[-1\.1, 0\.92, 1\.1\][\s\S]*\[1\.3, -0\.62, 0\.51\]/, 'negative temperature lead should run from the shared service port to the black host input');
assert.match(sceneSource, /name="PressureSensorLead"[\s\S]*\[-1\.12, 0\.88, 0\.34\][\s\S]*\[-1\.1, 0\.92, 1\.1\][\s\S]*\[1\.77, -0\.63, 0\.51\]/, 'pressure tube should run from the shared service port to the central pressure input');
assert.match(sceneSource, /name="PressureSensorLead"[\s\S]*color="#cbd5e1"[\s\S]*lineWidth=\{4\}/, 'pressure tube should be lighter and thicker than the temperature wires');
assert.doesNotMatch(sceneSource, /clampStopcockAngle/, 'stopcock drag should no longer be clamped to a 0-90 degree range');
assert.match(
  sceneSource,
  /name="AnalogPressureGauge"[\s\S]*position=\{\[0\.58, 0\.05, 0\.52\]\}/,
  'pressure gauge should stay right-of-center instead of colliding with the far-right power switch',
);
assert.match(
  sceneSource,
  /name="PowerSwitch"[\s\S]*position=\{\[0\.98, -0\.14, 0\.56\]\}/,
  'power switch should be on the far right and separated from the circular pressure gauge',
);
assert.match(sceneSource, /name="CentralSensorStopperHole" position=\{\[0\.16, 1\.16, 0\.24\]\}/, 'sensor top hole should be offset toward the shared service port instead of being locked to the absolute center axis');
assert.match(sceneSource, /name="SensorStopperPort" position=\{\[0\.16, 0\.96, 0\.24\]\}/, 'sensor stopper port should follow the offset sensor axis while staying inside the bottle mouth area');
assert.match(sceneSource, /name="SensorRod" position=\{\[0\.16, 0\.52, 0\.24\]\}/, 'sensor rod should remain vertical but shift toward the shared service port');
assert.match(sceneSource, /name="SensorToServicePortTrace" position=\{\[0\.18, 1\.176, 0\.3\]\}/, 'a short top trace should clarify the sensor signal path into the shared service port');
assert.doesNotMatch(sceneSource, /name="SensorRod" position=\{\[0, 0\.52, 0\]\}/, 'sensor rod should no longer be forced onto the old central stopcock axis');
assert.match(sceneSource, /<cylinderGeometry args=\{\[0\.035, 0\.035, 0\.875, 16\]\}/, 'sensor rod length should be half of the 1.75-high vessel');
assert.match(sceneSource, /name="RubberStopper" position=\{\[0, 1\.02, 0\]\}[\s\S]*<cylinderGeometry args=\{\[0\.54, 0\.42, 0\.24, 40\]\}/, 'rubber stopper should be a frustum with the larger end on top and smaller end inserted into the bottle mouth');
assert.match(sceneSource, /name="BottleMouthNeck"/, 'glass vessel should include a bottle mouth neck that carries the stopper');
assert.match(sceneSource, /name="BottleMouthRim"/, 'glass vessel should include a visible mouth rim around the stopper');
assert.match(sceneSource, /name="StopcockBody"[\s\S]*<cylinderGeometry args=\{\[0\.16, 0\.16, 0\.76, 32\]\}/, 'horizontal stopcock body should be shorter and more compact');
assert.match(sceneSource, /name="StopcockSidePort"/, 'stopcock assembly should expose a side handle/end cap distinct from the vertical gas path');
assert.match(sceneSource, /name="StopcockTopVentOutlet"/, 'stopcock assembly should expose a top vent outlet to atmosphere');
assert.match(sceneSource, /name="StopcockTopVentOutlet" position=\{\[0, 0\.25, 0\]\}[\s\S]*<cylinderGeometry args=\{\[0\.043, 0\.048, 0\.36, 24\]\}/, 'top vent outlet should be half as long and half as thick as the previous skeleton');
assert.match(sceneSource, /name="StopcockRotatingCore"[\s\S]*rotation=\{\[angleRad, 0, 0\]\}/, 'stopcock rotating core should pivot around the horizontal stopcock body axis');
assert.match(sceneSource, /name="StopcockRotatingCore"[\s\S]*name="StopcockRotatingFlowChannel"[\s\S]*name="StopcockRodHandle"/, 'rotating flow channel and rod handle should be rigidly attached in the rotating core group');
assert.match(sceneSource, /name="StopcockRotatingFlowChannel" position=\{\[0, 0, 0\]\}[\s\S]*<cylinderGeometry args=\{\[0\.03, 0\.03, 0\.24, 16\]\}/, 'rotating gas channel should align with the stopcock handle axis while staying constrained inside the glass core');
assert.doesNotMatch(sceneSource, /name="StopcockRotatingFlowChannel" position=\{\[0, 0, 0\]\} rotation=\{\[Math\.PI \/ 2, 0, 0\]\}/, 'rotating gas channel should not keep the old perpendicular channel rotation');
assert.match(sceneSource, /state === 'open' \? '#22c55e' : '#334155'/, 'stopcock rotating channel should visibly distinguish open and closed states');
assert.doesNotMatch(sceneSource, /getPointerAngleOnValvePlane/, 'stopcock should not keep the old drag plane angle solver');
assert.doesNotMatch(sceneSource, /new THREE\.Raycaster\(\)/, 'stopcock should not cast pointer rays for continuous angle dragging');
assert.doesNotMatch(sceneSource, /setFromCamera/, 'stopcock drag projection should be removed');
assert.doesNotMatch(sceneSource, /angleOffsetRef/, 'stopcock should not preserve pointer-to-valve angle offsets because dragging is removed');
assert.doesNotMatch(sceneSource, /clientX - startX/, 'stopcock drag should not use screen-space mouse delta to accumulate angle');
assert.match(sceneSource, /depthTest=\{false\}/, 'internal rotating tube should remain visible through the transparent stopcock shell');
assert.match(sceneSource, /name="StopcockVentFlowArrow"/, 'open stopcock state should show a green vent flow arrow');
assert.doesNotMatch(sceneSource, /name="StopcockCoaxialFlowChannel"/, 'controlled gas path should not be a fixed coaxial channel in the stopper or vent outlet');
assert.doesNotMatch(sceneSource, /name="StopcockFlowSlot"/, 'stopcock should not use the old offset rotating slot as the internal gas path');
assert.match(sceneSource, /name="StopcockRodHandle"/, 'stopcock control should be a rod-shaped glass handle');
assert.doesNotMatch(sceneSource, /name="StopcockRotatingCore"[\s\S]*name="StopcockTopVentOutlet"/, 'top vent outlet should remain fixed and outside the rotating core');
assert.doesNotMatch(sceneSource, /name="StopcockRotatingCore"[\s\S]*name="StopcockDownTube"/, 'down tube should remain fixed and outside the rotating core');
assert.doesNotMatch(sceneSource, /name="SideGasStopperHole"/, 'stopper should not reserve a separate offset side gas hole for the stopcock path');
assert.match(sceneSource, /name="StopcockDownTube" position=\{\[0, -0\.36, 0\]\}/, 'glass stopcock down tube should align with the central bottle-mouth axis');
assert.match(sceneSource, /const controlsRef = useRef<.*OrbitControls/, '3D preview should keep a control ref so the view can be reset');
assert.match(sceneSource, /enablePan=\{true\}/, '3D preview should allow moving the model view');
assert.match(sceneSource, /enableZoom=\{true\}/, '3D preview should allow scaling the model view with zoom');
assert.match(sceneSource, /frameloop: 'demand'/, 'heat-capacity 3D scene should render on demand instead of continuously');
assert.match(sceneSource, /\[1, 1\.25\]/, 'standard Heat Capacity 3D mode should keep the current DPR cap');
assert.match(sceneSource, /shadows: false/, 'heat-capacity 3D scene should disable shadow rendering');
assert.doesNotMatch(sceneSource, /castShadow|receiveShadow/, 'heat-capacity 3D scene should not keep mesh shadow flags when shadows are disabled');
assert.match(sceneSource, /onStart=\{onInteractionStart\}/, 'orbit controls should enter a reduced-quality interaction state when dragging starts');
assert.match(sceneSource, /onEnd=\{onInteractionEnd\}/, 'orbit controls should leave the reduced-quality interaction state when dragging ends');
assert.match(sceneSource, /onChange=\{\(\) => invalidate\(\)\}/, 'orbit controls should invalidate demand rendering only when the camera changes');
assert.match(sceneSource, /interactionQualityReduced \? 1000 : 250/, 'standard instrument display refresh should slow down while orbit controls are being dragged');
assert.match(sceneSource, /const DEFAULT_CAMERA_POSITION: \[number, number, number\] = \[4\.15, 2\.9, 8\.25\]/, 'default heat-capacity camera should start farther away so the initial model appears smaller');
assert.match(sceneSource, /const ORBIT_MIN_DISTANCE = 2\.7;/, 'heat-capacity preview should allow closer zoom-in than before');
assert.match(sceneSource, /const ORBIT_MAX_DISTANCE = 11\.5;/, 'heat-capacity preview should allow wheel zoom-out from the default view');
assert.match(sceneSource, /focusMode/, '3D preview should track focused operation mode');
assert.match(sceneSource, /viewResetKey/, 'default view resets should use a local key to trigger the smooth camera rig');
assert.match(sceneSource, /triggerSmoothDefaultView/, 'default view resets and auto-demo resets should share the smooth reset path');
assert.doesNotMatch(sceneSource, /controlsRef\.current\?\.reset\(\)/, 'default view reset should not jump the camera through OrbitControls.reset');
assert.doesNotMatch(sceneSource, /name="StopcockRotatingCore"[\s\S]{0,260}onDoubleClick/, 'direct stopcock double-click focus should be removed so clicking only toggles the two-state valve');
assert.match(sceneSource, /onFocus\('instrument'\)/, 'double-clicking the host should enter instrument focus mode');
assert.match(sceneSource, /focusMode === 'stopcock'[\s\S]*nextPosition\.set\(1\.02, 2\.04, 2\.64\);[\s\S]*nextTarget\.set\(-1\.27, 0\.79, 0\.07\);/, 'stopcock and pump-valve focus view should keep the corrected angle while shifting the projected model left and down so the green vent arrow remains fully visible');
assert.match(sceneSource, /focusMode === 'instrument'[\s\S]*nextPosition\.set\(2\.18, 0\.18, 3\.42\);[\s\S]*nextTarget\.set\(2\.02, -0\.76, 0\.34\);/, 'instrument focus view should shift the host upward and clear of the lower-right panel while keeping the left display visible');
assert.doesNotMatch(sceneSource, /className="studio-heat-focus-exit"/, 'focused modes should not use a separate top-right exit button');
assert.match(sceneSource, /data-heat-capacity-focus-panel="stopcock"/, 'stopcock focus mode should expose a compact lower-right focus panel');
assert.match(sceneSource, /data-heat-capacity-focus-panel="pump"/, 'pump focus mode should expose its own lower-right focus panel');
assert.match(sceneSource, /data-heat-capacity-focus-panel="instrument"/, 'instrument focus mode should expose its own lower-right focus panel');
assert.match(sceneSource, /data-heat-capacity-focus-exit="true"/, 'each focus panel should include the unified exit focus control');
assert.match(sceneSource, /const poweredInstrumentReadout = \(displayValue: string\) => props\.powerOn \? displayValue : sceneCopy\.unpowered/, 'instrument focus panel should hide instrument readouts while powered off');
assert.match(sceneSource, /const poweredInstrumentNumber = \(displayValue: string\) => props\.powerOn \? displayValue : '--'/, 'instrument focus panel should hide numeric placeholders while powered off');
assert.match(sceneSource, /<strong>\{poweredInstrumentReadout\(temperatureDisplay\)\}<\/strong>/, 'instrument focus U_T should be guarded by power state');
assert.match(sceneSource, /<strong>\{poweredInstrumentReadout\(pressureDisplay\)\}<\/strong>/, 'instrument focus U_P should be guarded by power state');
assert.match(sceneSource, /<strong>\{poweredInstrumentNumber\(`\$\{formatPanelNumber\(props\.pressureDisplayedPlaceholder, 2\)\} mV`\)\}<\/strong>/, 'instrument focus displayed pressure should not leak values while powered off');
assert.match(sceneSource, /<strong>\{poweredInstrumentNumber\(`\$\{formatPanelNumber\(props\.pressurePlaceholder, 2\)\} kPa`\)\}<\/strong>/, 'instrument focus placeholder pressure should not leak values while powered off');
assert.match(sceneSource, /getPumpBulbDisplayLabel/, 'pump bulb display state should be mapped for user-facing UI');
assert.match(sceneSource, /props\.pumpValveOpen \? sceneCopy\.focus\.opened : sceneCopy\.focus\.closed/, 'shared stopcock focus panel should show pump valve open-closed state');
assert.doesNotMatch(sceneSource, /snapNearestOpen|吸附|磁吸|magnetic/i, 'stopcock focus panel should not expose magnetic snap controls');
assert.match(sceneSource, /enabled=\{focusMode === 'none' && !props\.interactionLocked\}/, 'orbit controls should lock while focusing an instrument control area and during auto demo');
assert.match(sceneSource, /data-heat-capacity-view-reset="true"/, '3D preview should expose a reset-default-view control');
assert.match(styleSource, /\.studio-heat-focus-panel \{[\s\S]*right: 14px;[\s\S]*bottom: 14px;/, 'focus panels should sit in the lower-right corner');
assert.doesNotMatch(styleSource, /\.studio-heat-stopcock-panel \{[\s\S]*left: 14px;/, 'stopcock focus panel should no longer sit in the lower-left corner');
assert.match(styleSource, /\.studio-heat-interaction-hints \{[\s\S]*border: 1px solid rgba\(100, 116, 139/, 'lower-left interaction hints should use the same restrained engineering panel frame');
assert.match(styleSource, /\.studio-heat-interaction-hints strong::before/, 'lower-left interaction hints should use a compact status-dot heading');
assert.match(styleSource, /\.studio-heat-focus-panel \{[\s\S]*border: 1px solid rgba\(100, 116, 139/, 'lower-right focus panel should use the engineering panel frame');
assert.match(styleSource, /\.studio-heat-focus-title \{[\s\S]*font-family: "JetBrains Mono"/, 'focus panel title should read like an engineering status header');
assert.match(styleSource, /\.studio-heat-focus-panel-pump \{[\s\S]*pointer-events: none;/, 'pump focus panel should not steal rapid pump clicks from the bulb behind non-control panel areas');
assert.match(styleSource, /\.studio-heat-focus-panel-pump \.studio-heat-focus-panel-actions button \{[\s\S]*pointer-events: auto;/, 'pump focus panel exit button should remain clickable when the panel body passes pointer events through');
assert.match(sceneSource, /className="studio-heat-focus-instrument-columns"/, 'instrument focus panel should organize readouts into explicit left and right columns');
assert.match(styleSource, /\.studio-heat-focus-panel-instrument \{[\s\S]*width: min\(390px, calc\(100% - 28px\)\);/, 'instrument focus panel should be wide enough for aligned readout values without moving from the lower-right corner');
assert.match(styleSource, /\.studio-heat-focus-instrument-columns \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/, 'instrument focus readouts should use balanced two-column groups');
assert.match(styleSource, /\.studio-heat-focus-panel-instrument \.studio-heat-focus-panel-row \{[\s\S]*grid-template-columns: 64px minmax\(0, 1fr\);/, 'instrument focus rows should use fixed label and value columns');
assert.match(styleSource, /\.studio-heat-focus-panel-instrument \.studio-heat-focus-panel-row strong \{[\s\S]*white-space: nowrap;[\s\S]*overflow: hidden;/, 'instrument focus values should keep number and unit on one line without spilling outside the panel');
assert.match(styleSource, /\.studio-heat-interaction-hints \{[\s\S]*position: absolute;[\s\S]*left: 12px;[\s\S]*bottom: 12px;/, 'interaction hints should sit in a low-interference corner');
assert.match(styleSource, /\.studio-heat-hover-tooltip \{[\s\S]*pointer-events: none;/, 'hover tooltip should not steal canvas interactions');
assert.match(styleSource, /\.studio-heat-demo-step-panel \{[\s\S]*right: 14px;[\s\S]*top: 48px;/, 'auto demo step panel should sit inside the heat model window upper-right area');
assert.match(styleSource, /\.studio-heat-demo-step-panel \{[\s\S]*width: min\(330px, calc\(100% - 28px\)\);/, 'auto demo step panel should stay compact and avoid covering the model window');
assert.match(styleSource, /\.studio-heat-demo-step-panel div:not\(\.studio-heat-demo-step-kicker\) \{[\s\S]*grid-template-columns: 58px minmax\(0, 1fr\);/, 'step panel should keep the original compact field layout');
assert.match(styleSource, /\.studio-heat-preview-mount \{[\s\S]*overflow: hidden;/, 'heat preview mount should clip the step panel as it slides out to the right');
assert.match(styleSource, /\.studio-heat-demo-step-panel-visible \{[\s\S]*animation: heatDemoStepPanelIn 560ms/, 'auto demo step panel should slide in and fade in when the demo starts');
assert.match(styleSource, /\.studio-heat-demo-step-panel-exiting \{[\s\S]*animation: heatDemoStepPanelOut 560ms/, 'auto demo step panel should slide right and fade out when the demo ends or is terminated');
assert.match(styleSource, /\.studio-heat-pressure-warning \{[\s\S]*left: 50%;[\s\S]*top: 50%;[\s\S]*background: rgba\(10, 15, 23, 0\.9/, 'pressure warning should use a centered engineering alert panel inside the heat model window');
assert.match(styleSource, /\.studio-heat-pressure-warning-kicker \{[\s\S]*font-family: "JetBrains Mono"/, 'pressure warning should expose a compact engineering status kicker');
assert.match(styleSource, /\.studio-heat-manual-step-hint \{[\s\S]*left: 50%;[\s\S]*bottom: 18px;[\s\S]*background: rgba\(15, 23, 42, 0\.8/, 'heat-capacity manual toast queue should use one bottom-centered engineering notification panel');
assert.match(styleSource, /\.studio-heat-manual-step-hint-warning \{[\s\S]*border-color: rgba\(245, 158, 11, 0\.7\)/, 'heat-capacity toast queue should expose a warning level style');
assert.match(styleSource, /\.studio-heat-manual-step-hint-danger \{[\s\S]*border-color: rgba\(248, 113, 113, 0\.75\)/, 'heat-capacity toast queue should expose a danger level style');
assert.match(styleSource, /\.studio-heat-demo-complete-toast \{[\s\S]*left: 50%;[\s\S]*top: 50%;[\s\S]*background: rgba\(10, 15, 23, 0\.9/, 'normal auto demo completion should use a centered engineering notification panel');
assert.match(styleSource, /\.studio-heat-toast-kicker \{[\s\S]*font-family: "JetBrains Mono"/, 'toast overlays should use compact engineering kicker labels');
assert.doesNotMatch(styleSource, /@keyframes heatDemoFocusPulse/, 'unused CSS keyframes should not remain after Three.js-driven focus halos');

const workbenchSource = readFileSync(workbenchPath, 'utf8');
assert.match(workbenchSource, /HeatCapacityInstrumentScene/);
assert.match(workbenchSource, /type ManualHeatCapacityStep =[\s\S]*openStopcockForZeroRequired[\s\S]*recordU0Required[\s\S]*recordU1Required[\s\S]*recordU2Required[\s\S]*nextTrialRequired[\s\S]*calculateRequired/, 'manual heat-capacity workflow should model stopcock-zeroing, U0/U1/U2 recording, and multi-trial continuation as required steps');
assert.match(workbenchSource, /guardManualHeatCapacityAction/, 'manual heat-capacity controls should pass through one shared guard');
assert.match(workbenchSource, /manualHeatCapacityActiveFileId/, 'manual heat-capacity tutorial should have an explicit active file binding');
assert.match(workbenchSource, /manualHeatCapacityActiveFileId !== activeFile\.id\) return true/, 'manual guards should not constrain users before the manual tutorial is started');
assert.match(workbenchSource, /data-heat-capacity-manual-step-hint="true"/, 'manual heat-capacity guard should surface a top-centered step hint in the 3D preview');
assert.match(workbenchSource, /studio-heat-record-controls-pulse/, 'manual heat-capacity guard should pulse the record entry when recording is the next required action');
assert.match(workbenchSource, /const recordHeatCapacityManualSample = \(kind: HeatCapacityManualRecordKind\)[\s\S]*const latestStep = getHeatCapacityManualStep\(file\)[\s\S]*latestStep !== requiredStep/, 'direct record buttons should revalidate against the latest manual workflow step');
assert.match(workbenchSource, /kind === 'u0'[\s\S]*captureHeatCapacityWorkbenchSample\(file, 'zeroedSample', now\)/, 'direct U0 recording should write the zeroed sample through the shared sample structure');
assert.match(workbenchSource, /manualHeatCapacityActiveFileId === activeFile\.id[\s\S]*recordU0Required[\s\S]*recordU1Required[\s\S]*recordU2Required/, 'manual mode should only show the record button required by the current workflow step');
assert.doesNotMatch(workbenchSource, /manualHeatCapacityActiveFileId === activeFile\.id && activeFile\.powerOn[\s\S]*recordU0Required/, 'record buttons should not depend on a second powerOn gate once the manual workflow has reached a record step');
assert.match(workbenchSource, /const isManualU1RecordReady =/, 'manual U1 record readiness should be centralized in a stable-window helper');
assert.match(workbenchSource, /const isManualU2RecordReady =/, 'manual U2 record readiness should be centralized in a stable-window helper');
assert.match(workbenchSource, /const getActiveHeatCapacityTrial =/, 'manual multi-trial flow should read the current active heat-capacity trial');
assert.match(workbenchSource, /const hasActiveTrialU1 =/, 'manual U1 completion should be scoped to the active trial instead of the whole trial table');
assert.match(workbenchSource, /const hasActiveTrialU2 =/, 'manual U2 completion should be scoped to the active trial instead of the whole trial table');
assert.match(workbenchSource, /const isActiveTrialComplete =/, 'manual next-trial transition should require the active trial to be complete');
assert.match(workbenchSource, /const getActiveTrialRecordedU1Mv =/, 'manual U2 readiness should use the active trial U1 value');
assert.match(workbenchSource, /const getManualHeatCapacityDecisionPressureMv =[\s\S]*pressureSignalTargetMv/, 'manual record readiness should prefer target pressure over display jitter');
assert.match(workbenchSource, /const getManualHeatCapacityDecisionTemperatureMv =[\s\S]*temperatureSignalTargetMv/, 'manual record readiness should prefer target temperature over display jitter');
assert.match(workbenchSource, /const isManualHeatCapacityTemperatureAtAmbient =/, 'manual U1/U2 readiness should verify U_T has returned near room temperature');
assert.match(workbenchSource, /const isManualHeatCapacityReleaseCompleteForU2 =/, 'manual U2 flow should verify quick release is complete before allowing stopcock closure and recovery');
assert.match(workbenchSource, /if \(file\.heatCapacityPhase === 'recovering'\) return true;/, 'manual U2 release completion should remain true after the process has entered recovery');
assert.match(workbenchSource, /if \(recordedU1Mv !== null\) return recordedU1Mv \* \(1 - 1 \/ file\.theoreticalGamma\);/, 'manual U2 readiness should derive the target from the recorded U1 before falling back to profile defaults');
assert.match(workbenchSource, /const isManualU1RecordReady =[\s\S]*isManualHeatCapacityTemperatureAtAmbient\(file\)/, 'U1 recording should require temperature recovery to the room baseline');
assert.match(workbenchSource, /const isManualU2RecordReady =[\s\S]*isManualHeatCapacityTemperatureAtAmbient\(file\)/, 'U2 recording should require temperature recovery to the room baseline');
assert.match(workbenchSource, /const isManualU2RecordReady =[\s\S]*const recordedU1Mv = getActiveTrialRecordedU1Mv\(file\)/, 'U2 readiness should not borrow U1 from a previous completed trial');
assert.match(workbenchSource, /if \(!releaseComplete\) return 'openStopcockReleaseRequired';[\s\S]*if \(stopcockState === 'open'\) return 'closeStopcockAfterReleaseRequired'/, 'manual release flow should keep the stopcock open until U_p has dropped near zero');
assert.match(workbenchSource, /const u1Ready = isManualU1RecordReady\(file\)/, 'manual workflow should use the U1 stable-window helper');
assert.match(workbenchSource, /const u2Ready = isManualU2RecordReady\(file\)/, 'manual workflow should use the U2 stable-window helper');
assert.match(workbenchSource, /const hasU1 = hasActiveTrialU1\(file\)/, 'manual workflow should decide U1 completion from the active trial only');
assert.match(workbenchSource, /const hasU2 = hasActiveTrialU2\(file\)/, 'manual workflow should decide U2 completion from the active trial only');
assert.match(workbenchSource, /const recordedU1Mv = getActiveTrialRecordedU1Mv\(file\)/, 'manual workflow should derive release state from the active trial U1 only');
assert.match(workbenchSource, /isActiveTrialComplete\(file\) && completedTrialCount < file\.heatCapacityExpectedTrialCount/, 'manual workflow should show next-trial only after the active trial is complete');
assert.doesNotMatch(workbenchSource, /const hasU1 = file\.heatCapacityTrials\.some\(\(trial\) => trial\.U1Mv !== null\)/, 'manual workflow must not use global U1 presence to advance the active trial');
assert.doesNotMatch(workbenchSource, /const hasU2 = file\.heatCapacityTrials\.some\(\(trial\) => trial\.U2Mv !== null\)/, 'manual workflow must not use global U2 presence to advance the active trial');
assert.doesNotMatch(workbenchSource, /file\.heatCapacityTrials\.find\(\(trial\) => trial\.U1Mv !== null\)\?\.U1Mv/, 'manual workflow must not borrow recorded U1 from earlier trials');
assert.doesNotMatch(workbenchSource, /const u1Ready =[\s\S]*pressureValue >= 80[\s\S]*!file\.pressureOverLimit/, 'manual U1 record readiness should not depend on the old single 80 mV threshold');
assert.doesNotMatch(workbenchSource, /expectedU1 \* 0\.62/, 'manual U1 readiness should not reintroduce the too-strict platform threshold');
const u1ReadyBlock = workbenchSource.match(/const isManualU1RecordReady =[\s\S]*?const isManualU2RecordReady =/)?.[0] ?? '';
assert.doesNotMatch(u1ReadyBlock, /file\.heatCapacityPhase === 'recovering'/, 'U1 readiness must not treat the post-release recovery phase as before-release stability');
assert.match(workbenchSource, /const isManualU0ZeroReady =/, 'manual U0 recording should have a dedicated zero-ready helper');
assert.match(workbenchSource, /const isManualU0ZeroAttempted =/, 'manual zero guidance should distinguish no adjustment from an incomplete adjustment');
assert.match(workbenchSource, /recordU0Required:\s*\['adjustPressureZero',\s*'recordU0'\]/, 'U0 recording stage should still allow continued pressure-zero adjustment');
assert.match(workbenchSource, /if \(!isManualU0ZeroReady\(file\)\) return 'zeroAdjustRequired'/, 'manual workflow should not advance to U0 recording until the pressure-zero value is actually acceptable');
assert.doesNotMatch(workbenchSource, /if \(!file\.pressureZeroAdjusted\) return 'zeroAdjustRequired';\s*return 'recordU0Required';/, 'manual workflow should not treat any pressure-zero adjustment as a successful zero');
assert.doesNotMatch(workbenchSource, /kind === 'u0'[\s\S]*Math\.abs\(zeroReferenceMv\) > 1\.5[\s\S]*recordU0Warning/, 'record U0 click should not run a second, looser validation after the workflow already exposes the button');
assert.doesNotMatch(workbenchSource, /pressureValue\s*[<>]=?\s*80/, 'manual U1 flow should not keep the old fixed 80 mV transition threshold');
assert.doesNotMatch(workbenchSource, /不建议记录 U₀|不建議記錄 U₀|U₀ recording is not recommended/, 'U0 guidance should not imply optional recording after the workflow exposes the record button');
assert.match(workbenchSource, /--heat-record-focus-offset/, 'manual record controls should use a measured focus-panel offset');
assert.doesNotMatch(styleSource, /studio-heat-record-controls-focus-raised \{[\s\S]*translateY\(-122px\)/, 'manual record controls should not use one fixed lift value for every focus panel');
assert.match(workbenchSource, /openStopcockForZeroRequired:\s*\['openStopcock'\]/, 'manual workflow should require opening the stopcock before pressure zeroing');
assert.match(workbenchSource, /openStopcockReleaseRequired:\s*\['openStopcock'\]/, 'manual workflow should block release until the U1 step has been satisfied');
assert.match(workbenchSource, /nextTrialRequired:\s*\['startNextTrial'\]/, 'manual workflow should expose a guarded next-trial action after each completed trial before the final one');
assert.match(workbenchSource, /getHeatCapacityCompletedTrialCount\(file\.heatCapacityTrials\)[\s\S]*file\.heatCapacityExpectedTrialCount[\s\S]*return 'nextTrialRequired'/, 'manual workflow should require starting the next trial until expected trial count is complete');
assert.match(workbenchSource, /const startNextHeatCapacityManualTrial =[\s\S]*getHeatCapacityNextActiveTrialIndex[\s\S]*heatCapacityProcessSamples: \{\}/, 'starting the next heat-capacity trial should preserve completed trials while clearing current process samples');
assert.match(workbenchSource, /data-heat-capacity-next-trial="true"[\s\S]*startNextHeatCapacityManualTrial/, '3D preview should render a dedicated next-trial button during the nextTrialRequired step');
assert.match(workbenchSource, /calculateRequired:\s*\['calculate'\]/, 'manual workflow should make calculation an explicit final step');
assert.doesNotMatch(workbenchSource, /const animateHeatCapacityStopcockAngle =/, 'auto demo stopcock actions should not use the old continuous angle writer that fights the scene-level two-state animation');
assert.match(workbenchSource, /const setHeatCapacityStopcockOpenByFileId =[\s\S]*getHeatCapacityStopcockTargetAngle\(nextOpen\)[\s\S]*glassPistonState: nextOpen \? 'open' : 'closed'/, 'auto demo stopcock actions should write the same open/closed target state used by manual interaction');
assert.match(workbenchSource, /closeStopcockForPumping' \|\| action === 'closeStopcockForRecovery'[\s\S]*setHeatCapacityStopcockOpenByFileId\(fileId, false\)/, 'auto demo close-stopcock actions should use the two-state stopcock helper');
assert.match(workbenchSource, /openStopcockForRelease' \|\| action === 'openStopcockForZero'[\s\S]*setHeatCapacityStopcockOpenByFileId\(fileId, true\)/, 'auto demo open-stopcock actions should use the two-state stopcock helper');
assert.match(workbenchSource, /MANUAL_HEAT_CAPACITY_IDLE_HINT_DELAY_MS = 1000/, 'manual workflow idle hint should use the temporary 1s validation delay');
assert.match(workbenchSource, /scheduleManualIdleHint\(MANUAL_HEAT_CAPACITY_IDLE_HINT_REPEAT_MS\)/, 'manual workflow hints should repeat while the user stays on the same step');
assert.match(workbenchSource, /activeHeatCapacityManualStep/, 'manual idle hint scheduling should depend on a stable manual step value instead of the whole active file object');
assert.doesNotMatch(workbenchSource, /useEffect\(\(\) => \{[\s\S]*manualHeatCapacityIdleTimerRef[\s\S]*\}, \[\s*activeFile,/, 'manual idle hint timer must not depend on the full activeFile object that ticks every 100ms');
assert.match(workbenchSource, /setManualHeatCapacityActiveFileId\(activeFile\.id\)/, 'starting a manual heat-capacity experiment should activate the tutorial state machine');
assert.match(workbenchSource, /setManualHeatCapacityActiveFileId\(null\)/, 'starting auto demo should disable the manual tutorial state machine');
assert.match(styleSource, /\.studio-heat-manual-step-hint/, 'manual heat-capacity step hints should have a dedicated overlay style');
assert.match(styleSource, /@keyframes studio-heat-manual-record-pulse/, 'recording guidance should use a restrained pulse animation');
assert.match(workbenchSource, /adjustHeatCapacityPressureZeroFine/, 'workbench should route pressure zero wheel changes to heatCapacity state');
assert.match(workbenchSource, /adjustHeatCapacityPressureZeroCoarse/, 'workbench should route pressure zero drag changes to heatCapacity state');
assert.match(workbenchSource, /const \[heatCapacityPumpPulseId, setHeatCapacityPumpPulseId\]/, 'workbench should keep pump pulse as local UI-only state');
assert.match(workbenchSource, /setHeatCapacityPumpPulseId\(\(pulseId\) => pulseId \+ 1\)/, 'each pump press should retrigger local visual feedback');
assert.match(workbenchSource, /pumpPulseId=\{heatCapacityPumpPulseId\}/, 'workbench should pass local pump pulse signal into the 3D scene');
assert.match(workbenchSource, /pressureKPa={activeFile\.pressureKPa}/, 'workbench should pass current pressureKPa into the 3D gauge');
assert.match(workbenchSource, /pressureLimitKPa={activeFile\.pressureLimitKPa}/, 'workbench should pass pressureLimitKPa into the 3D gauge');
assert.match(workbenchSource, /gaugePressureMinKPa=\{activeFile\.gaugePressureMinKPa\}/, 'workbench should pass gauge pressure min into the 3D pressure gauge');
assert.match(workbenchSource, /gaugePressureMaxKPa=\{activeFile\.gaugePressureMaxKPa\}/, 'workbench should pass gauge pressure max into the 3D pressure gauge');
assert.match(workbenchSource, /pressureSafetyThresholdKPa=\{activeFile\.pressureSafetyThresholdKPa\}/, 'workbench should pass safety threshold into the 3D pressure gauge');
assert.match(workbenchSource, /pressureOverLimit=\{activeFile\.pressureOverLimit\}/, 'workbench should pass pressure over-limit state into the 3D pressure gauge');
assert.match(workbenchSource, /data-heat-capacity-pressure-warning="true"/, 'workbench should render a centered red pressure warning from pressureOverLimit');
assert.match(workbenchSource, /studio-heat-pressure-warning-kicker/, 'pressure warning markup should include an engineering status kicker');
assert.match(workbenchSource, /temperatureSignalMv={activeFile\.temperatureSignalMv}/, 'instrument screens should read the display-response temperature channel');
assert.match(workbenchSource, /pressureSignalMv={activeFile\.pressureSignalMv}/, 'instrument screens should read the display-response pressure channel');
assert.match(sceneSource, /name="TemperatureDisplayChannelLabelText"[\s\S]*U_T \/ mV/, 'instrument host should label the left screen as the temperature signal channel');
assert.match(sceneSource, /name="PressureDisplayChannelLabelText"[\s\S]*U_p \/ mV/, 'instrument host should label the pressure screen as the pressure signal channel');
assert.match(workbenchSource, /updateHeatCapacityPower/);
assert.match(workbenchSource, /updateHeatCapacityStopcockOpen/);
assert.doesNotMatch(workbenchSource, /const updateHeatCapacityStopcockAngle/, 'Workbench should not keep the continuous stopcock angle updater');
assert.doesNotMatch(workbenchSource, /zeroHeatCapacityPressure/, 'workbench should not keep the old one-click pressure-zero path');
assert.doesNotMatch(workbenchSource, /setHeatCapacityPressureZeroOffset\(file,\s*file\.pressureRawPlaceholder/, 'pressure-zero action must not directly jump the displayed pressure to zero');
assert.doesNotMatch(workbenchSource, /captureHeatCapacityWorkbenchSample\(zeroedFile,\s*'zeroedSample'\)/, 'auto demo must not bypass U0 zero readiness by directly capturing after one-click zero');
assert.match(workbenchSource, /updateHeatCapacityPumpValve/);
assert.match(workbenchSource, /pressHeatCapacityPumpBulb/);
assert.match(workbenchSource, /pumpFrequencyStatus/);
assert.match(workbenchSource, /createHeatCapacityAutoDemoSteps/, 'workbench should wire the one-shot heat capacity auto demo script');
assert.match(workbenchSource, /getHeatCapacityAutoDemoTimeline/, 'workbench should schedule semantic auto demo highlight/action/observe stages');
assert.match(workbenchSource, /HEAT_CAPACITY_AUTO_DEMO_RESET_MS/, 'heat capacity auto demo should reserve a reset phase before step 1 starts');
assert.match(workbenchSource, /Initializing auto demo|初始化自动演示|初始化自動演示/, 'auto demo start should show a centered automatic initialization message before running');
assert.match(workbenchSource, /resetting controls|自动复位控件|自動復位控制項/, 'auto demo start should describe automatic reset instead of asking the user to reset manually');
assert.match(workbenchSource, /setAutoDemoStepTitle\(['"`](Preparing demo|准备演示|準備演示)/, 'auto demo reset phase should not show stale completion copy in the step panel');
assert.match(workbenchSource, /timelineItem\.atMs < startFromElapsedMs/, 'auto demo timeline should not skip the first zero-time step after the reset delay');
assert.match(workbenchSource, /scheduleHeatCapacityAutoDemoTimeline\(demoFileId, timeline, 0, HEAT_CAPACITY_AUTO_DEMO_RESET_MS\)/, 'auto demo timeline should start after the default reset phase');
assert.match(workbenchSource, /timelineItem\.stage === 'preview'/, 'auto demo should update the step panel one second before the next highlight');
assert.match(workbenchSource, /autoDemoInteractionLocked/, 'workbench should lock user actions while auto demo is running');
assert.match(workbenchSource, /autoDemoPaused/, 'heat capacity auto demo should keep an explicit paused state');
assert.match(workbenchSource, /pauseHeatCapacityAutoDemo/, 'heat capacity pause button should pause the demo instead of showing a future-batch warning');
assert.match(workbenchSource, /terminateHeatCapacityAutoDemo/, 'heat capacity stop button should terminate the demo instead of showing a future-batch warning');
assert.match(workbenchSource, /terminateHeatCapacityAutoDemo[\s\S]*markHeatCapacityDemoComplete/, 'terminating heat capacity auto demo should reset controls through the same default-state path as normal completion');
assert.doesNotMatch(workbenchSource, /future batch|后续批次|後續批次/, 'heat capacity pause and stop controls should now have real behavior');
assert.match(workbenchSource, /showHeatCapacityAutoDemoLockedToast/, 'workbench should show a single locked-interaction toast');
assert.match(workbenchSource, /Cannot operate during demo|演示中无法操作|演示中無法操作/, 'locked heat capacity preview clicks should show the required toast text');
assert.match(workbenchSource, /studio-heat-toast-kicker/, 'toast markup should include engineering status kicker labels');
assert.match(workbenchSource, /Demo complete|演示完成|演示完成/, 'normal heat capacity demo completion should show a centered completion message');
assert.match(workbenchSource, /onFocusModeChange=\{\(mode\) => \{[\s\S]*heatCapacityFocusModeRef\.current = mode/, 'workbench should know when the scene is in a heat-capacity focus mode');
assert.match(workbenchSource, /setHeatCapacityFocusResetKey\(\(key\) => key \+ 1\);[\s\S]*heatCapacityFocusModeRef\.current = 'none'/, 'auto demo should reset the heat scene to the default view before starting');
assert.match(workbenchSource, /setAutoDemoStepCount\(steps\.length\)/, 'auto demo should prepare the current step count before the reset phase');
assert.match(workbenchSource, /autoDemoStepPanelMode/, 'workbench should keep the auto demo step panel mounted long enough to animate in and out');
assert.match(workbenchSource, /hideHeatCapacityAutoDemoStepPanel\(\)/, 'normal completion and termination should slide the auto demo step panel out instead of leaving it pinned');
assert.match(workbenchSource, /timelineItem\.focusControlId/, 'auto demo timeline should support per-highlight focus targets inside one semantic step');
assert.match(workbenchSource, /renderScientificText/, 'visible heat-capacity labels should render U variables with real subscripts');
assert.match(workbenchSource, /studio-heat-stopcock-mini-readout/, 'manual stopcock focus should render a compact host-readout mirror');
assert.match(workbenchSource, /heatCapacityFocusMode === 'stopcock' && !autoDemoRunning && !autoDemoPaused && !autoDemoInteractionLocked/, 'stopcock mini readout should only appear in manual stopcock focus mode');
assert.match(workbenchSource, /activeFile\.temperatureSignalMv/, 'stopcock mini readout should mirror the displayed temperature channel');
assert.match(workbenchSource, /activeFile\.pressureSignalMv/, 'stopcock mini readout should mirror the displayed pressure channel');
assert.match(workbenchSource, /activeFile\.pressureGaugeNeedleAngle/, 'stopcock mini gauge should mirror the shared pressure gauge needle angle');
assert.match(workbenchSource, /studio-heat-stopcock-mini-statusbar/, 'stopcock mini readout should use a compact engineering status bar');
assert.match(workbenchSource, /studio-heat-stopcock-mini-readout-row/, 'stopcock mini readout should use aligned instrument readout rows');
assert.match(workbenchSource, /GAUGE kPa/, 'stopcock mini gauge should include an engineering gauge label');
assert.match(workbenchSource, /LIMIT|WARN|SAFE|OFFLINE/, 'stopcock mini readout should show compact engineering status text');
assert.match(styleSource, /\.studio-heat-stopcock-mini-readout \{[\s\S]*left: 12px;[\s\S]*top: 12px;/, 'stopcock mini readout should sit inside the model window upper-left corner');
assert.match(styleSource, /\.studio-heat-stopcock-mini-readout \{[\s\S]*pointer-events: none;/, 'stopcock mini readout should not steal glass stopcock interactions');
assert.match(styleSource, /\.studio-heat-stopcock-mini-statusbar \{/, 'stopcock mini readout should style the engineering status bar');
assert.match(styleSource, /\.studio-heat-stopcock-mini-readout-row \{[\s\S]*grid-template-columns:/, 'stopcock mini readout rows should align labels, values, and units');
assert.match(styleSource, /\.studio-heat-stopcock-mini-gauge-label \{/, 'stopcock mini gauge should style the compact gauge label');
assert.match(workbenchSource, /autoDemoStepTitle/, 'workbench should drive the right-top auto demo step panel');
assert.match(workbenchSource, /studio-heat-demo-step-panel/, 'preview should render the auto demo step panel inside the model window');
assert.match(workbenchSource, /data-heat-capacity-toast="true"/, 'preview should render locked interaction feedback through the unified heat-capacity toast queue');
assert.match(workbenchSource, /heatCapacityToastCurrentRef/, 'manual heat-capacity toasts should track the currently displayed message');
assert.match(workbenchSource, /heatCapacityToastPendingRef/, 'manual heat-capacity toasts should retain only one pending message');
assert.match(workbenchSource, /HEAT_CAPACITY_TOAST_DISPLAY_DURATION_MS = 2000/, 'manual heat-capacity toasts should display each visible message for two seconds');
assert.match(workbenchSource, /setHeatCapacityToastPendingState\(nextMessage\)/, 'new manual heat-capacity toasts should update the pending message without interrupting current text');
assert.doesNotMatch(workbenchSource, /autoDemoToastMessage|manualHeatCapacityHintMessage/, 'old independent heat-capacity toast states should not remain');
assert.match(workbenchSource, /prepareHeatCapacityAutoDemoStart/, 'auto demo should initialize with a non-zero pressure display bias without changing gas pressure');
assert.doesNotMatch(stateSource, /prepareHeatCapacityAutoDemoStart[\s\S]*stopcockAngleDeg:\s*HEAT_CAPACITY_STOPCOCK_OPEN_ANGLE_DEG/, 'auto demo start must not silently open the stopcock during the power-on step');
assert.match(workbenchSource, /setHeatCapacityStopcockOpenByFileId\(fileId, true\)/, 'auto demo should request open stopcock movement through the shared two-state helper');
assert.match(workbenchSource, /setHeatCapacityStopcockOpenByFileId\(fileId, false\)/, 'auto demo should request closed stopcock movement through the shared two-state helper');
assert.doesNotMatch(workbenchSource, /animateHeatCapacityStopcockAngle/, 'auto demo should not write continuous stopcock angles that fight the scene-level smooth two-state animation');
assert.match(workbenchSource, /animateHeatCapacityPressureZero/, 'auto demo should rotate the pressure-zero knob smoothly');
assert.match(workbenchSource, /data-heat-capacity-auto-demo/, 'preview header should expose a heat capacity auto demo button');
assert.match(workbenchSource, /stepHeatCapacityWorkbenchFile/, 'workbench should step the heat capacity process model from the shared file state');
assert.match(workbenchSource, /captureHeatCapacityWorkbenchSample/, 'workbench should capture process sample placeholders without formal p0/p1/p2 records');
assert.match(workbenchSource, /heatCapacityPumpAnimationRef/, 'pump bulb animation should be retriggerable instead of locked by old timers');
assert.match(workbenchSource, /clearHeatCapacityPumpAnimationTimers/, 'new pump clicks should clear stale release and idle timers before scheduling fresh feedback');
assert.doesNotMatch(workbenchSource, /pumpBulbState === 'compressing'[\s\S]{0,80}return/, 'rapid pump clicks should not be ignored while the bulb is compressing');
assert.doesNotMatch(workbenchSource, /pumpBulbState === 'releasing'[\s\S]{0,80}return/, 'rapid pump clicks should not be ignored while the bulb is releasing');
assert.match(workbenchSource, /setInterval[\s\S]*refreshHeatCapacityPumpFrequency/, 'pump frequency should refresh on a sliding window even after clicking stops');
assert.match(workbenchSource, /data-heat-capacity-realtime-header="true"/, 'fixed realtime window should have a dedicated monitor header');
assert.match(workbenchSource, /data-heat-capacity-live-readings="true"/, 'fixed realtime window should group live readings');
assert.match(workbenchSource, /data-heat-capacity-operation-status="true"/, 'fixed realtime window should group safety and operation status');
assert.doesNotMatch(workbenchSource, /data-heat-capacity-live-charts="true"/, 'fixed realtime window should not mount Heat Capacity realtime charts');
assert.match(workbenchSource, /data-heat-capacity-current-hint="true"/, 'fixed realtime window should expose a concise current hint');
assert.match(workbenchSource, /getHeatCapacityPhaseLabel/, 'fixed realtime window should map internal heat-capacity phase ids to readable labels');
assert.match(workbenchSource, /getHeatCapacityRealtimeCopy/, 'fixed realtime Heat Capacity copy should be localized outside the render body');
assert.match(workbenchSource, /settingsLanguagePreference/, 'fixed realtime Heat Capacity panel should read the current language preference');
assert.match(workbenchSource, /const heatCapacityHeaderBadges = \[/, 'fixed realtime header should render a compact dynamic badge list');
assert.match(workbenchSource, /label: `\$\{heatCapacityRealtimeCopy\.stagePrefix\}\$\{phaseLabel\}`/, 'fixed realtime header should keep stage as the only always-visible localized badge');
assert.match(workbenchSource, /demoComplete:\s*'演示结束'/, 'fixed realtime copy should label the final auto-demo state as a demo ending in zh-CN');
assert.match(workbenchSource, /demoComplete:\s*'Demo ended'/, 'fixed realtime copy should include an English terminal auto-demo label');
assert.doesNotMatch(workbenchSource, /phase === 'demoComplete'[\s\S]{0,80}return '实验完成'/, 'fixed realtime header should not call the auto-demo terminal phase formal experiment completion');
assert.match(workbenchSource, /demoComplete:\s*'自动演示已结束，可重新开始或查看后续数据处理结果。'/, 'fixed realtime hint should keep the demoComplete copy in the auto-demo context');
assert.match(workbenchSource, /if \(activeFile\.heatCapacityPhase === 'demoComplete'\) return heatCapacityRealtimeCopy\.hints\.demoComplete;[\s\S]*if \(!activeFile\.powerOn/, 'fixed realtime hint should check demoComplete before the powered-off fallback');
assert.match(workbenchSource, /autoDemoPaused\s*\?\s*heatCapacityRealtimeCopy\.demoPaused[\s\S]*autoDemoRunning\s*\?\s*heatCapacityRealtimeCopy\.demoRunning[\s\S]*heatCapacityRealtimeCopy\.demoReady/, 'fixed realtime header should show localized automation badges only for active demo states');
assert.match(workbenchSource, /label: heatCapacityRealtimeCopy\.operationLocked/, 'fixed realtime header should show localized lock status only when interaction is locked');
assert.match(workbenchSource, /heatCapacityHeaderBadges\.map\(\(badge\)/, 'fixed realtime header should render badges from the compact display model');
assert.doesNotMatch(workbenchSource, /const powerLabel = activeFile\.powerOn \? '宸插紑鏈? : '鏈紑鏈?/, 'fixed realtime header should not keep a separate always-visible power badge');
assert.doesNotMatch(workbenchSource, /const modeLabel = [^\n]*'手动'/, 'fixed realtime header should not keep a default manual-mode badge');
assert.doesNotMatch(workbenchSource, /const lockLabel = [^\n]*'鍙搷浣?/, 'fixed realtime header should not keep a default actionable badge');
assert.doesNotMatch(workbenchSource, /\{powerLabel\}|\{modeLabel\}|\{lockLabel\}/, 'fixed realtime header should not render the removed static power/mode/lock labels');
assert.match(workbenchSource, /currentDeltaPKPa[\s\S]*activeFile\.pressureSignalMv[\s\S]*activeFile\.pressureSensitivityMvPerKPa/, 'fixed realtime window should derive current delta pressure from displayed U_p and the shared sensitivity');
assert.match(styleSource, /\.studio-heat-operation-status \{[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/, 'operation status should stay as one row of three control states');
assert.match(styleSource, /\.studio-realtime-panel-heat \{[\s\S]*grid-template-rows: auto auto auto auto;/, 'heat realtime panel should only reserve rows for header, readings, operation status, and hint');
assert.match(workbenchSource, /Air Heat Capacity Ratio Experiment|空气比热容比实验|空氣比熱容比實驗/);
assert.match(workbenchSource, /pressureStatus|Pressure status|压力状态|壓力狀態/);
assert.match(workbenchSource, /pumpValve|Pump valve|打气阀门|打氣閥門/);
assert.match(workbenchSource, /glassStopcock|Glass stopcock|玻璃旋塞/);
assert.match(workbenchSource, /zeroStatusLabel|pressureZero|Pressure zero|压强调零|壓強調零/);
assert.match(workbenchSource, /currentHint|Current hint|当前提示|目前提示/);
assert.doesNotMatch(workbenchSource, /<div><span>閲囨牱璁板綍<\/span>/, 'fixed realtime window should not show the full process-sample table entry');
assert.doesNotMatch(workbenchSource, /<div><span>鐩爣 \{renderScientificText\('U_T'\)/, 'fixed realtime window should not show target temperature debug fields');
assert.doesNotMatch(workbenchSource, /<div><span>鐩爣 \{renderScientificText\('U_p'\)/, 'fixed realtime window should not show target pressure debug fields');
assert.doesNotMatch(workbenchSource, /<div><span>闆剁偣鍋忕Щ<\/span>/, 'fixed realtime window should not show pressure-zero offset as a constant debug field');
assert.doesNotMatch(workbenchSource, /<div><span>压强余量<\/span>/, 'fixed realtime window should not show pressure headroom as a constant debug field');
assert.doesNotMatch(workbenchSource, /<div><span>压力安全<\/span>/, 'operation status should not repeat pressure safety under the safety card');
assert.match(workbenchSource, /U_T \/ mV/);
assert.match(workbenchSource, /U_p \/ mV/);
assert.match(workbenchSource, /ΔP \/ kPa/, 'fixed realtime window should use the delta symbol for pressure difference');
assert.doesNotMatch(workbenchSource, /heatCapacityTrace/, 'Heat Capacity should not keep realtime chart trace in the workbench component');
assert.doesNotMatch(workbenchSource, /<polyline points=\{points\} \/>/, 'Heat Capacity realtime polyline renderer should be removed');
assert.doesNotMatch(styleSource, /studio-heat-trace|studio-heat-live-chart/, 'Heat Capacity realtime chart CSS should be removed');
assert.doesNotMatch(workbenchSource, /bezierCurveTo|quadraticCurveTo|studio-heat-trace-glow|heatCapacityRuntimeStore/, 'heat-capacity realtime chart should not reintroduce the later complex chart/runtime implementation');
assert.equal(existsSync(join(process.cwd(), 'components', 'heatCapacity', 'HeatCapacityTraceChart.tsx')), false, 'this stable-version optimization should not add the later standalone trace chart component');
assert.match(workbenchSource, /renderHeatCapacityMaterialsWindow/, 'Heat Capacity should have a browser-style materials/results window');
assert.match(workbenchSource, /openAllHeatCapacityMaterialsTabs/, 'double-clicking the Heat Capacity materials group should open all child tabs');
assert.match(workbenchSource, /recordHeatCapacityU1/, 'Heat Capacity should support U1 / UT1 trial recording');
assert.match(workbenchSource, /recordHeatCapacityU2/, 'Heat Capacity should support U2 / UT2 trial recording');
assert.match(workbenchSource, /calculateHeatCapacityMeanResult/, 'Heat Capacity data processing should calculate trial gamma and mean gamma');
assert.match(workbenchSource, /createHeatCapacityTrialFromAutoDemoSamples/, 'auto demo completion should import one complete trial from process samples');
assert.match(workbenchSource, /heatCapacityExpectedTrialCount:\s*1[\s\S]*heatCapacityExpectedTrialCountMode:\s*'custom'/, 'auto demo completion should force a single imported trial table');
assert.match(workbenchSource, /activeHeatCapacityTabId:\s*'processing'[\s\S]*heatCapacityProcessingCalculated:\s*processingResult\.calculated/, 'auto demo completion should open data processing and show calculated results');
assert.match(workbenchSource, /startManualExperiment:\s*'开始手动实验'/, 'auto-demo completion should expose a Simplified Chinese manual reset action');
assert.match(workbenchSource, /startManualExperiment:\s*'開始手動實驗'/, 'auto-demo completion should expose a Traditional Chinese manual reset action');
assert.match(workbenchSource, /startManualExperiment:\s*'Start Manual Trial'/, 'auto-demo completion should expose an English manual reset action');
assert.match(workbenchSource, /data-heat-capacity-manual-reset="true"/, 'preview should render a manual-experiment reset button after demo completion');
assert.match(workbenchSource, /manualHeatCapacityActiveFileId !== activeFile\.id \? \([\s\S]*data-heat-capacity-manual-reset="true"/, 'preview should expose the manual experiment entry before demo completion when the manual tutorial is inactive');
assert.match(workbenchSource, /resetHeatCapacityForManualExperiment/, 'Workbench should use the dedicated Heat Capacity manual reset helper');
assert.match(workbenchSource, /nextPowerOn && source === 'user'[\s\S]*heatCapacityPhase === 'demoComplete'[\s\S]*runState === 'finished'[\s\S]*resetHeatCapacityForManualExperiment/, 'direct power-on after auto demo should defensively reset stale demo pressure state');
assert.match(workbenchSource, /pressureSignalTargetMv/, 'right realtime panel should retain target pressure signal separately from displayed pressure');
assert.match(workbenchSource, /temperatureSignalTargetMv/, 'right realtime panel should retain target temperature signal separately from displayed temperature');
assert.doesNotMatch(workbenchSource, /打气过快|tooFast|频率偏高/, 'workbench should not show or calculate a too-fast pump state');
assert.match(workbenchSource, /zeroStatusLabel/, 'fixed realtime window should still expose pressure-zero status in the operation group');
assert.match(workbenchSource, /temperatureSignalValue/, 'fixed realtime window should still expose the live temperature signal');
assert.match(workbenchSource, /pressureSignalValue/, 'fixed realtime window should still expose the live pressure signal');
assert.match(workbenchSource, /realtimePanelTitle: '实时数据'/, 'Heat Capacity fixed panel title should not mention charts in Simplified Chinese');
assert.match(workbenchSource, /realtimePanelTitle: '即時資料'/, 'Heat Capacity fixed panel title should not mention charts in Traditional Chinese');
assert.match(workbenchSource, /realtimePanelTitle: 'Realtime Data'/, 'Heat Capacity fixed panel title should not mention charts in English');
assert.match(workbenchSource, /heatRealtimeTitle/, 'Heat Capacity left panel should have a dedicated realtime title without chart wording');
assert.match(workbenchSource, /renderScientificText\(panel\.hint\)/, 'dock headers should render U_T and U_p with real subscripts');
assert.match(workbenchSource, /renderScientificText\(heatCapacityRealtimeCopy\.realtimeSubtitle\)/, 'right Heat Capacity panel subtitle should render U_T and U_p with real subscripts');
assert.doesNotMatch(workbenchSource, /<div><span>鐞嗚 gamma<\/span>/, 'this batch must not render a gamma result field');
assert.doesNotMatch(workbenchSource, /鏃嬪瑙掑害/, 'realtime panel should not expose stopcock angle to users');
assert.doesNotMatch(workbenchSource, /stopcockAngleDeg, 1\)} deg/, 'realtime panel should not render internal stopcock degrees');
assert.match(workbenchSource, /performanceMode:\s*'standard'/, 'general settings should default performance mode to standard');
assert.match(workbenchSource, /type WorkbenchPerformanceMode = 'standard' \| 'balanced' \| 'performance'/, 'performance mode should support standard, balanced, and performance tiers');
assert.match(workbenchSource, /isWorkbenchPerformanceMode/, 'general settings should migrate legacy settings without a performance field');
assert.match(workbenchSource, /updateSettingsPerformanceMode/, 'general settings should expose a persistent performance mode updater');
assert.match(workbenchSource, /performanceModeBalanced/, 'general settings copy should include a balanced performance tier');
assert.match(workbenchSource, /performanceModeOptions\.map/, 'general settings should render performance mode as a segmented control');
assert.match(workbenchSource, /studio-settings-performance-segmented/, 'general settings should include segmented performance mode markup');
assert.doesNotMatch(workbenchSource, /role="switch"[\s\S]*aria-checked=\{settingsPerformanceMode === 'performance'\}/, 'general settings should not keep the old binary performance switch');
assert.doesNotMatch(workbenchSource, /handleAction\('Performance mode'\)/, 'top settings menu should not keep the old standalone performance action');
assert.match(workbenchSource, /performanceMode=\{settingsPerformanceMode\}/, 'Workbench should pass the selected performance mode into Heat Capacity 3D');
assert.match(workbenchSource, /settingsPerformanceMode === 'performance'\s*\?\s*240\s*:\s*settingsPerformanceMode === 'balanced'\s*\?\s*150\s*:\s*100/, 'Heat Capacity file tick should use three performance tiers');
assert.doesNotMatch(workbenchSource, /studio-settings-performance-switch/, 'general settings should remove the old performance switch markup');
assert.match(leftPanelSource, /studio-heat-processing-summary/, 'Heat Capacity data processing should use a dedicated engineering summary strip');
assert.match(leftPanelSource, /validResults\.length < 2/, 'single-trial processing should hide the gamma chart');
assert.match(leftPanelSource, /<GammaAir \/> = \{file\.theoreticalGamma\.toFixed\(2\)\}/, 'processing summary should display air theoretical gamma from the Heat Capacity file');
assert.doesNotMatch(leftPanelSource, /5\s*\/\s*3|1\.667/, 'Heat Capacity processing UI should not show hard-sphere theoretical gamma');
assert.match(leftPanelSource, /zh-CN[\s\S]*实验指引[\s\S]*数据记录[\s\S]*数据处理/, 'Heat Capacity left panel should include Simplified Chinese copy');
assert.match(leftPanelSource, /zh-TW[\s\S]*實驗指引[\s\S]*資料記錄[\s\S]*資料處理/, 'Heat Capacity left panel should include Traditional Chinese copy');
assert.match(leftPanelSource, /en[\s\S]*Experiment Guide[\s\S]*Data Recording[\s\S]*Data Processing/, 'Heat Capacity left panel should include English copy');
assert.match(leftPanelSource, /<>ΔP<sub>\{index\}<\/sub><\/>/, 'Heat Capacity formulas should render Delta P with the real delta symbol');
assert.match(leftPanelSource, /<>γ\{index !== undefined/, 'Heat Capacity formulas should render gamma with the real Greek symbol');
assert.match(leftPanelSource, /HEAT_CAPACITY_FORMULA_RESULT_PREVIEW_LIMIT\s*=\s*3/, 'formula result cards should default to showing at most three trial groups');
assert.match(leftPanelSource, /formulaResultsExpanded/, 'formula result cards should expose a local expand-collapse state');
assert.match(leftPanelSource, /slice\(0,\s*HEAT_CAPACITY_FORMULA_RESULT_PREVIEW_LIMIT\)/, 'formula result cards should collapse to the first three trial groups by default');
assert.match(leftPanelSource, /展开全部/, 'formula result cards should include Simplified Chinese show-all copy');
assert.match(leftPanelSource, /收起/, 'formula result cards should include collapse copy');
assert.match(leftPanelSource, /已显示前 \${visible} 组，共 \${total} 组/, 'formula result cards should explain the three-group preview limit');
assert.doesNotMatch(leftPanelSource, /getFormulaExample/, 'formula result cards should not rely on a single example trial');
assert.match(leftPanelSource, /本组已完成，已省略真实实验中约 5 分钟的恢复室温等待过程，可立即进入下一组实验。/, 'recording page should explain the omitted real-world recovery wait before the next trial');
assert.match(workbenchSource, /已省略真实实验中约 5 分钟的恢复室温等待过程，可立即进入下一组实验。/, 'manual U2 success guidance should explain the omitted real-world recovery wait');
assert.match(workbenchSource, /showManualHeatCapacityGuidance\(heatCapacityRealtimeCopy\.skipRecoveryWait,\s*'startNextTrial'/, 'manual U2 success should point the user to the next-trial control after the wait-skip notice');
assert.doesNotMatch(leftPanelSource, /铻東绾瑋钄殀鑴硘鐎箌鐠亅缁寍閻榺鈧琝?/, 'Heat Capacity left panel source should not contain mojibake or corrupted scientific symbols');
assert.doesNotMatch(leftPanelSource, /studio-heat-processing-intro[\s\S]{0,260}studio-analysis-cell/, 'Heat Capacity processing intro should not reuse the generic analysis cell layout');
assert.match(styleSource, /\.studio-heat-processing-summary/, 'Heat Capacity processing summary should have dedicated CSS');
assert.match(styleSource, /\.studio-theme-light \.studio-heat-panel-content/, 'light theme should cover Heat Capacity materials panel content');
assert.match(styleSource, /\.studio-theme-light \.studio-heat-thinking-trigger:hover/, 'light theme should keep Heat Capacity thinking hover states light');
assert.match(styleSource, /\.studio-theme-light \.studio-heat-trial-count button:hover/, 'light theme should cover Heat Capacity trial count button hover states');
assert.match(styleSource, /\.studio-settings-performance-segmented/, 'performance mode segmented control should have dedicated CSS');
assert.match(styleSource, /\.studio-settings-performance-thumb/, 'performance mode segmented control should have a sliding thumb');
assert.match(styleSource, /\.studio-settings-performance-option/, 'performance mode segmented control should style each tier option');
assert.match(styleSource, /\.studio-heat-hover-tooltip[\s\S]*right:\s*12px[\s\S]*bottom:\s*12px/, 'Heat Capacity hover tooltip should avoid covering the lower-left operation hints');
assert.match(styleSource, /\.studio-heat-hover-tooltip[\s\S]*z-index:\s*3/, 'Heat Capacity hover tooltip should stay below critical overlays while remaining readable');
assert.match(styleSource, /\.studio-theme-light \.studio-settings-performance-segmented/, 'light theme should style the performance segmented control');
assert.match(styleSource, /\.studio-theme-light \.studio-settings-performance-option:hover/, 'light theme performance option hover should stay light');
assert.doesNotMatch(styleSource, /\.studio-settings-performance-toggle i/, 'settings performance switch should not keep a separate thumb implementation');

console.log('workbenchHeatCapacityInstrumentUi tests passed');
