import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const componentPath = join(process.cwd(), 'components', 'heatCapacity', 'HeatCapacityInstrumentScene.tsx');
const workbenchPath = join(process.cwd(), 'components', 'WorkbenchStudioPrototype.tsx');
const stylePath = join(process.cwd(), 'components', 'WorkbenchStudioPrototype.css');

assert.equal(existsSync(componentPath), true, 'heatCapacity instrument scene component should exist');

const sceneSource = readFileSync(componentPath, 'utf8');
const styleSource = readFileSync(stylePath, 'utf8');
assert.match(sceneSource, /@react-three\/fiber/);
assert.match(sceneSource, /@react-three\/drei/);
assert.doesNotMatch(sceneSource, /<Html[\s\S]*(TemperatureDisplay|PressureDisplay|FD-NCD-C|INPUT|PRESS IN)/, 'instrument panel labels should not use camera-facing Html overlays');
assert.match(sceneSource, /CanvasTexture/, 'instrument panel labels should use 3D canvas textures attached to the instrument face');
assert.match(sceneSource, /<planeGeometry args=\{\[0\.46, 0\.115\]\}/, 'instrument panel labels should be rendered as face-mounted planes');
assert.match(sceneSource, /onPowerToggle/);
assert.match(sceneSource, /onStopcockAngleChange/);
assert.match(sceneSource, /onPressureZero/);
assert.match(sceneSource, /onPressureZeroFineAdjust/, 'instrument scene should expose pressure zero fine wheel adjustment');
assert.match(sceneSource, /onPressureZeroCoarseAdjust/, 'instrument scene should expose pressure zero coarse drag adjustment');
assert.match(sceneSource, /GLB replacement contract/i);
assert.match(sceneSource, /name="SensorStopperPort"/);
assert.match(sceneSource, /name="StopcockDownTube"/);
assert.match(sceneSource, /name="pumpAssembly"/, 'external pump assembly should have a stable GLB replacement root');
assert.match(sceneSource, /name="pumpPortOnStopper"/, 'stopper should expose an independent pump port');
assert.match(sceneSource, /name="pumpTube"/, 'pump tube should connect the stopper pump port to the external bulb');
assert.match(sceneSource, /name="pumpValve"/, 'pump valve should sit near the stopper-side pump route');
assert.match(sceneSource, /name="pumpValveHandle"/, 'pump valve should expose a handle for open/closed interaction');
assert.match(sceneSource, /name="pumpBulb"/, 'external pump bulb should exist');
assert.match(sceneSource, /name="pumpBulbHitbox"/, 'pump bulb should expose an independent click target');
assert.match(sceneSource, /name="pumpPortOnStopper" position=\{\[-1\.72, 0\.9, 0\.26\]\}/, 'pump port should move to the left side of the stopper');
assert.match(sceneSource, /name="pumpShortConnectorIn"/, 'pump route should include a short inlet connector before the inline valve body');
assert.match(sceneSource, /name="pumpShortConnectorOut"/, 'pump route should include a short outlet connector after the inline valve body');
assert.match(sceneSource, /name="pumpValveBody"/, 'pump valve body should be the fixed inline segment of the pump route');
assert.match(sceneSource, /name="pumpPortOnStopper"[\s\S]*name="pumpShortConnectorIn"[\s\S]*name="pumpValve"[\s\S]*name="pumpValveBody"[\s\S]*name="pumpShortConnectorOut"[\s\S]*name="pumpTube"/, 'pump route should read as stopper port -> inlet connector -> inline valve -> outlet connector -> tube');
assert.match(sceneSource, /name="pumpValve"[\s\S]*position=\{\[-1\.72, 0\.9, 0\.54\]\}/, 'inline valve should sit on the same local centerline as the stopper pump port and tube inlet');
assert.match(sceneSource, /name="pumpValveBody"[\s\S]*rotation=\{\[Math\.PI \/ 2, 0, 0\]\}/, 'inline valve body should be aligned with the pump tube axis rather than attached as a side decoration');
assert.match(sceneSource, /name="pumpValveHandle" position=\{\[0, 0, 0\]\} rotation=\{\[0, valveHandleAngle, 0\]\}/, 'inline valve handle should rotate around the valve body center without moving the valve body');
assert.match(sceneSource, /name="pumpTube"[\s\S]*\[-1\.72, 0\.9, 0\.74\]/, 'pump tube should start from the inline valve outlet, not bypass the valve from the stopper port');
assert.match(sceneSource, /\[-2\.18, 0\.72, 0\.92\][\s\S]*\[-2\.18, -0\.3, 1\.52\][\s\S]*\[1\.66, -0\.98, 1\.08\]/, 'pump tube should route around the outside before reaching the bulb');
assert.match(sceneSource, /name="pumpTube"[\s\S]*lineWidth=\{8\}/, 'pump tube should be visibly thicker than temperature and pressure leads');
assert.match(sceneSource, /name="pumpValveBody"/, 'pump valve should use a recognizable metal ball-valve body');
assert.match(sceneSource, /name="pumpValveWingHandle"/, 'pump valve should use a wing or lever handle instead of a plain block');
assert.match(sceneSource, /name="pumpValveStateBadge"/, 'pump valve should expose a local open-closed status badge without repainting the whole body');
assert.match(sceneSource, /setValveHandleAngle/, 'pump valve handle should animate smoothly between open and closed states');
assert.match(sceneSource, /name="pumpValveHandle" position=\{\[0, 0, 0\]\} rotation=\{\[0, valveHandleAngle, 0\]\}/, 'pump valve handle should rotate around its own vertical center axis in a horizontal plane');
assert.match(sceneSource, /name="pumpValveWingHandle" position=\{\[0, 0\.18, 0\]\}/, 'pump valve wing should sit above the fixed inline body while rotating around the valve body center axis');
assert.doesNotMatch(sceneSource, /name="pumpValveHandle"[\s\S]{0,120}rotation=\{\[0, 0, valveHandleAngle\]\}/, 'pump valve handle should not flip around the screen-facing Z axis');
assert.match(sceneSource, /onPumpValveToggle/, 'instrument scene should receive pump valve state updates from the workbench');
assert.match(sceneSource, /onPumpBulbPress/, 'instrument scene should report pump bulb presses to the workbench state');
assert.match(sceneSource, /pumpPulseId: number/, 'pump bulb visual feedback should receive a UI-only retrigger signal');
assert.match(sceneSource, /pumpPulseId=\{props\.pumpPulseId\}/, 'pump pulse signal should reach the pump assembly without being persisted in experiment state');
assert.match(sceneSource, /focusMode=\{props\.focusMode\}/, 'pump assembly should know whether it is in pump focus mode');
assert.match(sceneSource, /onPointerDown=\{focusMode === 'pump' \? handlePumpBulbPointerDown : undefined\}/, 'pump focus mode should use pointer down for rapid pump clicks');
assert.match(sceneSource, /if \(focusMode === 'pump'\) return;/, 'pump focus mode click events should not be filtered by click detail or double count after pointer down');
assert.doesNotMatch(sceneSource, /name="pumpBulb"[\s\S]*onClick=\{\(event\) => \{[\s\S]*onPumpBulbPress\(\);[\s\S]*onDoubleClick/, 'single-clicking the pump bulb outside pump focus should not trigger an effective pump stroke');
assert.match(sceneSource, /focusMode === 'pump'/, 'double-clicking the pump assembly should enter a dedicated pump focus view');
assert.match(sceneSource, /name="pumpBulb"[\s\S]*onDoubleClick/, 'double-clicking the pump bulb should enter the pump focus panel directly');
assert.doesNotMatch(sceneSource, /name="pumpBulb"[\s\S]{0,260}nativeEvent as MouseEvent\)\.detail > 1[\s\S]{0,120}onPumpBulbPress/, 'pump focus mode should not lose rapid clicks through native click-detail filtering');
assert.match(sceneSource, /onFocus\('stopcock'\)/, 'double-clicking the pump valve should enter the shared stopcock and valve focus view');
assert.match(sceneSource, /setHoveredControl\('pumpBulb'\)/, 'pump bulb should expose hover feedback');
assert.match(sceneSource, /setHoveredControl\('pumpValve'\)/, 'pump valve should expose hover feedback');
assert.match(sceneSource, /setHoveredControl\('stopcock'\)/, 'stopcock handle should expose hover feedback for dragging and wheel adjustment');
assert.match(sceneSource, /setHoveredControl\('powerSwitch'\)/, 'power switch should expose hover feedback');
assert.match(sceneSource, /setHoveredControl\('pressureZero'\)/, 'pressure zero knob should expose hover feedback');
assert.match(sceneSource, /压力调零：拖拽粗调 \/ 滚轮精调/, 'pressure zero hover tooltip should explain coarse drag and fine wheel');
assert.match(sceneSource, /handlePressureZeroWheel/, 'pressure zero knob should support wheel fine adjustment');
assert.match(sceneSource, /startPressureZeroDrag/, 'pressure zero knob should support drag coarse adjustment');
assert.match(sceneSource, /PRESSURE_ZERO_FINE_ANGLE_STEP_DEG/, 'pressure zero fine adjustment should have a tunable angle step');
assert.match(sceneSource, /PRESSURE_ZERO_DRAG_DIRECTION = -1/, 'pressure zero drag should use an explicit direction factor for the current oblique view');
assert.match(sceneSource, /pressureZeroInteractionEnabled = focusMode === 'instrument'/, 'pressure zero knob should only rotate in instrument focus mode');
assert.match(sceneSource, /onPointerDown=\{pressureZeroInteractionEnabled \? startPressureZeroDrag : undefined\}/, 'pressure zero drag should be disabled outside instrument focus mode');
assert.match(sceneSource, /onWheel=\{pressureZeroInteractionEnabled \? handlePressureZeroWheel : undefined\}/, 'pressure zero wheel adjustment should be disabled outside instrument focus mode');
assert.match(sceneSource, /name="PressureZeroDirectionMark"/, 'pressure zero knob should include a visible direction mark so rotation is readable');
assert.match(sceneSource, /name="PressureZeroIndicatorGroup" rotation=\{\[0, 0, THREE\.MathUtils\.degToRad\(pressureZeroKnobAngle\)\]\}/, 'pressure zero pointer and direction mark should rotate as one readable group');
assert.doesNotMatch(sceneSource, /pressureZeroed=\{props\.pressureZeroed\}/, '3D scene should not keep the obsolete pressureZeroed visual prop path');
assert.doesNotMatch(sceneSource, /setHoveredControl\('instrument'\)/, 'instrument front panel should not expose a hover prompt');
assert.match(sceneSource, /name="StopcockRodHandleHoverHalo"/, 'stopcock hover should use a soft halo instead of a stark white edge');
assert.match(sceneSource, /name="PowerSwitchHoverHalo"/, 'power switch hover should use a soft halo instead of a stark white edge');
assert.match(sceneSource, /name="PressureZeroHoverHalo"/, 'pressure zero hover should use a soft halo instead of a stark white edge');
assert.match(sceneSource, /NON_BULB_HOVER_EMISSIVE_INTENSITY = 0\.26/, 'non-bulb hover glow should be stronger than the first subtle pass');
assert.match(sceneSource, /NON_BULB_HOVER_HALO_OPACITY = 0\.22/, 'non-bulb hover halos should be visibly stronger than the first subtle pass');
assert.doesNotMatch(sceneSource, /name="InstrumentFaceHoverSheen"/, 'instrument front panel should not glow on hover');
assert.doesNotMatch(sceneSource, /hoveredControl === 'instrument'/, 'instrument front panel should not keep a hover state branch');
assert.doesNotMatch(sceneSource, /instrumentHovered \? <Edges color="#dbeafe"/, 'instrument hover should not rely on a stark edge outline');
assert.doesNotMatch(sceneSource, /powerSwitchHovered \? <Edges color="#ecfeff"/, 'power switch hover should not rely on a stark edge outline');
assert.doesNotMatch(sceneSource, /pressureZeroHovered \? <Edges color="#ecfeff"/, 'pressure zero hover should not rely on a stark edge outline');
assert.doesNotMatch(sceneSource, /stopcockHovered \? <Edges color="#ecfeff"/, 'stopcock hover should not rely on a stark edge outline');
assert.match(sceneSource, /getHeatCapacityInteractionHints/, '3D scene should show mode-specific interaction hints');
assert.match(sceneSource, /data-heat-capacity-interaction-hints="true"/, 'interaction hint panel should be rendered in the scene chrome');
assert.match(sceneSource, /getHeatCapacityHoverTooltip/, 'hovered controls should expose compact tooltips');
assert.match(sceneSource, /data-heat-capacity-hover-tooltip="true"/, 'hover tooltip should be rendered when an interactive control is hovered');
assert.match(sceneSource, /STOPCOCK_WHEEL_STEP_DEG/, 'stopcock wheel adjustment should use an explicit small angle step');
assert.match(sceneSource, /handleStopcockWheel/, 'stopcock handle should support wheel-based angle adjustment');
assert.match(sceneSource, /onWheel=\{handleStopcockWheel\}/, 'wheel events over the stopcock handle should adjust the valve instead of zooming the model');
assert.match(sceneSource, /onStopcockAngleChange\(normalizeHeatCapacityStopcockAngle/, 'wheel adjustment should update the same snapped stopcock angle state used by dragging and slider controls');
assert.match(sceneSource, /HOVER_CLEAR_DELAY_MS = 220/, 'hover state should use a short grace period to avoid cursor flicker on projected 3D boundaries');
assert.match(sceneSource, /hoverClearTimerRef/, 'hover state should cancel pending hover clears when entering adjacent meshes');
assert.match(sceneSource, /setStableHoveredControl/, 'hover updates should go through a stable boundary helper');
assert.match(sceneSource, /raycast=\{DISABLE_RAYCAST\}/, 'decorative hover halos should not compete with interaction hitboxes');
assert.doesNotMatch(sceneSource, /name="HitboxStopcockHandle" visible=\{false\}/, 'stopcock hitbox should remain raycastable instead of being invisible to raycaster');
assert.match(sceneSource, /name="HitboxStopcockHandle"[\s\S]*<boxGeometry args=\{\[1\.62, 1\.04, 0\.64\]\}/, 'stopcock hitbox should include a projected-screen buffer around the thin handle geometry');
assert.doesNotMatch(sceneSource, /name="HitboxPowerSwitch" visible=\{false\}/, 'power switch hitbox should remain raycastable instead of being invisible to raycaster');
assert.doesNotMatch(sceneSource, /name="HitboxPressureZeroKnob" visible=\{false\}/, 'pressure zero hitbox should remain raycastable instead of being invisible to raycaster');
assert.doesNotMatch(sceneSource, /name="pumpValveHitbox" visible=\{false\}/, 'pump valve hitbox should remain raycastable instead of being invisible to raycaster');
assert.doesNotMatch(sceneSource, /name="pumpBulbHitbox" visible=\{false\}/, 'pump bulb hitbox should remain raycastable instead of being invisible to raycaster');
assert.match(sceneSource, /pumpBulbScale/, 'pump bulb should animate through compression and release scale changes');
assert.match(sceneSource, /\? \[1\.08, 0\.7, 1\.06\][\s\S]*\? \[1\.02, 0\.92, 1\.01\]/, 'pump bulb should compress and reinflate without jelly-like overshoot');
assert.match(sceneSource, /name="pumpBulbStatusHalo"/, 'pump bulb active feedback should be an added halo, not a flat color replacement');
assert.doesNotMatch(sceneSource, /tooFast/, 'pump feedback must not introduce a too-fast state');
assert.match(
  sceneSource,
  /name="AnalogPressureGauge"[\s\S]*name="AnalogPressureGaugeDial"[\s\S]*rotation=\{\[Math\.PI \/ 2, 0, 0\]\}/,
  'analog pressure gauge dial should be vertical on the instrument face',
);
assert.match(sceneSource, /PRESSURE_GAUGE_TICKS/, 'analog pressure gauge should expose visible dial ticks');
assert.match(sceneSource, /getPressureGaugeNeedleRotation/, 'analog pressure gauge should derive needle rotation from pressure data');
assert.match(sceneSource, /pressureKPa: number \| null/, 'instrument scene should receive pressureKPa for gauge data binding');
assert.match(sceneSource, /pressureLimitKPa: number/, 'instrument scene should receive pressureLimitKPa for gauge data binding');
assert.match(sceneSource, /name="TemperaturePositiveInputTerminal"/, 'instrument host should show the red temperature input terminal below the left display');
assert.match(sceneSource, /name="TemperatureNegativeInputTerminal"/, 'instrument host should show the black temperature input terminal below the left display');
assert.match(sceneSource, /name="PressureSensorInputPort"/, 'instrument host should show one central metal pressure sensor input below the pressure display');
assert.match(sceneSource, /name="TemperaturePositiveLead"/, 'temperature positive lead should connect the sensor area to the red terminal');
assert.match(sceneSource, /name="TemperatureNegativeLead"/, 'temperature negative lead should connect the sensor area to the black terminal');
assert.match(sceneSource, /name="PressureSensorLead"/, 'pressure sensor lead should connect the side gas/pressure area to the central pressure port');
assert.match(sceneSource, /name="ExternalTemperatureLeadAnchor"/, 'temperature leads should route outside the glass vessel before entering the stopper');
assert.match(sceneSource, /name="ExternalPressureLeadAnchor"/, 'pressure lead should route outside the glass vessel before reaching the side pressure pickup');
assert.match(sceneSource, /name="SharedServiceCablePort" position=\{\[0\.2, 1\.17, 0\.36\]\}/, 'temperature and pressure connections should share one small rear-right cable/service port on top of the stopper');
assert.match(sceneSource, /name="ServicePortBundleAnchor" position=\{\[-1\.1, 0\.92, 1\.1\]\}/, 'all external leads should first leave the bottle assembly through a shared rear route');
assert.doesNotMatch(sceneSource, /name="SensorRearCableOutlet"/, 'old dedicated sensor wire outlet should be replaced by the shared service port');
assert.doesNotMatch(sceneSource, /name="SensorSurfaceLeadGroove"/, 'old dedicated sensor surface groove should be replaced by the shared service port');
assert.match(sceneSource, /name="TemperaturePositiveLead"[\s\S]*\[-1\.1, 0\.89, 0\.36\][\s\S]*\[-1\.1, 0\.92, 1\.1\][\s\S]*\[1\.12, -0\.62, 0\.51\]/, 'positive temperature lead should run from the shared service port to the red host input');
assert.match(sceneSource, /name="TemperatureNegativeLead"[\s\S]*\[-1\.08, 0\.885, 0\.38\][\s\S]*\[-1\.1, 0\.92, 1\.1\][\s\S]*\[1\.3, -0\.62, 0\.51\]/, 'negative temperature lead should run from the shared service port to the black host input');
assert.match(sceneSource, /name="PressureSensorLead"[\s\S]*\[-1\.12, 0\.88, 0\.34\][\s\S]*\[-1\.1, 0\.92, 1\.1\][\s\S]*\[1\.77, -0\.63, 0\.51\]/, 'pressure tube should run from the shared service port to the central pressure input');
assert.match(sceneSource, /name="PressureSensorLead"[\s\S]*color="#cbd5e1"[\s\S]*lineWidth=\{4\}/, 'pressure tube should be lighter and thicker than the temperature wires');
assert.doesNotMatch(sceneSource, /clampStopcockAngle/, 'stopcock drag should no longer be clamped to a 0-90 degree range');
assert.match(
  sceneSource,
  /name="AnalogPressureGauge"[\s\S]*position=\{\[0\.58, 0\.05, 0\.52\]\}/,
  'pressure gauge should stay right-of-center instead of colliding with the far-right power switch',
);
assert.match(
  sceneSource,
  /name="PowerSwitch"[\s\S]*position=\{\[0\.98, -0\.14, 0\.56\]\}/,
  'power switch should be on the far right and separated from the circular pressure gauge',
);
assert.match(sceneSource, /name="CentralSensorStopperHole" position=\{\[0\.16, 1\.16, 0\.24\]\}/, 'sensor top hole should be offset toward the shared service port instead of being locked to the absolute center axis');
assert.match(sceneSource, /name="SensorStopperPort" position=\{\[0\.16, 0\.96, 0\.24\]\}/, 'sensor stopper port should follow the offset sensor axis while staying inside the bottle mouth area');
assert.match(sceneSource, /name="SensorRod" position=\{\[0\.16, 0\.52, 0\.24\]\}/, 'sensor rod should remain vertical but shift toward the shared service port');
assert.match(sceneSource, /name="SensorToServicePortTrace" position=\{\[0\.18, 1\.176, 0\.3\]\}/, 'a short top trace should clarify the sensor signal path into the shared service port');
assert.doesNotMatch(sceneSource, /name="SensorRod" position=\{\[0, 0\.52, 0\]\}/, 'sensor rod should no longer be forced onto the old central stopcock axis');
assert.match(sceneSource, /<cylinderGeometry args=\{\[0\.035, 0\.035, 0\.875, 16\]\}/, 'sensor rod length should be half of the 1.75-high vessel');
assert.match(sceneSource, /name="RubberStopper" position=\{\[0, 1\.02, 0\]\}[\s\S]*<cylinderGeometry args=\{\[0\.54, 0\.42, 0\.24, 40\]\}/, 'rubber stopper should be a frustum with the larger end on top and smaller end inserted into the bottle mouth');
assert.match(sceneSource, /name="BottleMouthNeck"/, 'glass vessel should include a bottle mouth neck that carries the stopper');
assert.match(sceneSource, /name="BottleMouthRim"/, 'glass vessel should include a visible mouth rim around the stopper');
assert.match(sceneSource, /name="StopcockBody"[\s\S]*<cylinderGeometry args=\{\[0\.16, 0\.16, 0\.76, 32\]\}/, 'horizontal stopcock body should be shorter and more compact');
assert.match(sceneSource, /name="StopcockSidePort"/, 'stopcock assembly should expose a side handle/end cap distinct from the vertical gas path');
assert.match(sceneSource, /name="StopcockTopVentOutlet"/, 'stopcock assembly should expose a top vent outlet to atmosphere');
assert.match(sceneSource, /name="StopcockTopVentOutlet" position=\{\[0, 0\.25, 0\]\}[\s\S]*<cylinderGeometry args=\{\[0\.043, 0\.048, 0\.36, 24\]\}/, 'top vent outlet should be half as long and half as thick as the previous skeleton');
assert.match(sceneSource, /name="StopcockRotatingCore"[\s\S]*rotation=\{\[angleRad, 0, 0\]\}/, 'stopcock rotating core should pivot around the horizontal stopcock body axis');
assert.match(sceneSource, /name="StopcockRotatingCore"[\s\S]*name="StopcockRotatingFlowChannel"[\s\S]*name="StopcockRodHandle"/, 'rotating flow channel and rod handle should be rigidly attached in the rotating core group');
assert.match(sceneSource, /name="StopcockRotatingFlowChannel" position=\{\[0, 0, 0\]\} rotation=\{\[Math\.PI \/ 2, 0, 0\]\}[\s\S]*<cylinderGeometry args=\{\[0\.026, 0\.026, 0\.24, 16\]\}/, 'rotating gas channel should remain constrained inside the horizontal stopcock core');
assert.match(sceneSource, /state === 'open' \? '#22c55e' : '#334155'/, 'stopcock rotating channel should visibly distinguish open and closed states');
assert.match(sceneSource, /new THREE\.Plane\(\)/, 'stopcock drag should use a 3D interaction plane');
assert.match(sceneSource, /new THREE\.Raycaster\(\)/, 'stopcock drag should cast the pointer ray into the interaction plane');
assert.match(sceneSource, /setFromCamera/, 'stopcock drag should derive angle from pointer ray and camera projection');
assert.match(sceneSource, /Math\.atan2/, 'stopcock drag should compute a stable signed angle on the rotation plane');
assert.match(sceneSource, /angleOffsetRef/, 'stopcock drag should preserve pointer-to-valve angle offset during dragging');
assert.doesNotMatch(sceneSource, /clientX - startX/, 'stopcock drag should not use screen-space mouse delta to accumulate angle');
assert.match(sceneSource, /depthTest=\{false\}/, 'internal rotating tube should remain visible through the transparent stopcock shell');
assert.match(sceneSource, /name="StopcockVentFlowArrow"/, 'open stopcock state should show a green vent flow arrow');
assert.doesNotMatch(sceneSource, /name="StopcockCoaxialFlowChannel"/, 'controlled gas path should not be a fixed coaxial channel in the stopper or vent outlet');
assert.doesNotMatch(sceneSource, /name="StopcockFlowSlot"/, 'stopcock should not use the old offset rotating slot as the internal gas path');
assert.match(sceneSource, /name="StopcockRodHandle"/, 'stopcock control should be a rod-shaped glass handle');
assert.doesNotMatch(sceneSource, /name="StopcockRotatingCore"[\s\S]*name="StopcockTopVentOutlet"/, 'top vent outlet should remain fixed and outside the rotating core');
assert.doesNotMatch(sceneSource, /name="StopcockRotatingCore"[\s\S]*name="StopcockDownTube"/, 'down tube should remain fixed and outside the rotating core');
assert.doesNotMatch(sceneSource, /name="SideGasStopperHole"/, 'stopper should not reserve a separate offset side gas hole for the stopcock path');
assert.match(sceneSource, /name="StopcockDownTube" position=\{\[0, -0\.36, 0\]\}/, 'glass stopcock down tube should align with the central bottle-mouth axis');
assert.match(sceneSource, /const controlsRef = useRef<.*OrbitControls/, '3D preview should keep a control ref so the view can be reset');
assert.match(sceneSource, /enablePan=\{true\}/, '3D preview should allow moving the model view');
assert.match(sceneSource, /enableZoom=\{true\}/, '3D preview should allow scaling the model view with zoom');
assert.match(sceneSource, /focusMode/, '3D preview should track focused operation mode');
assert.match(sceneSource, /onFocus\('stopcock'\)/, 'double-clicking the stopcock should enter stopcock focus mode');
assert.match(sceneSource, /onFocus\('instrument'\)/, 'double-clicking the host should enter instrument focus mode');
assert.match(sceneSource, /focusMode === 'stopcock'[\s\S]*nextPosition\.set\(1\.02, 2\.04, 2\.64\);[\s\S]*nextTarget\.set\(-1\.27, 0\.79, 0\.07\);/, 'stopcock and pump-valve focus view should keep the corrected angle while shifting the projected model left and down so the green vent arrow remains fully visible');
assert.doesNotMatch(sceneSource, /className="studio-heat-focus-exit"/, 'focused modes should not use a separate top-right exit button');
assert.match(sceneSource, /data-heat-capacity-focus-panel="stopcock"/, 'stopcock focus mode should expose a compact lower-right focus panel');
assert.match(sceneSource, /data-heat-capacity-focus-panel="pump"/, 'pump focus mode should expose its own lower-right focus panel');
assert.match(sceneSource, /data-heat-capacity-focus-panel="instrument"/, 'instrument focus mode should expose its own lower-right focus panel');
assert.match(sceneSource, /data-heat-capacity-focus-exit="true"/, 'each focus panel should include the unified exit focus control');
assert.match(sceneSource, /getPumpBulbDisplayLabel/, 'pump bulb display state should be mapped for user-facing UI');
assert.match(sceneSource, /pumpValveOpen \? '已打开' : '已关闭'/, 'shared stopcock focus panel should show pump valve open-closed state');
assert.match(sceneSource, /data-heat-capacity-stopcock-slider="true"/, 'stopcock focus mode should include a continuous backup angle slider');
assert.match(sceneSource, /data-open-angle="90"/, 'stopcock slider should mark the first open angle');
assert.match(sceneSource, /data-open-angle="270"/, 'stopcock slider should mark the second open angle');
assert.match(sceneSource, /angleToSliderPercent\(90\)/, 'first open-angle marker should use the shared angle-to-track mapping');
assert.match(sceneSource, /angleToSliderPercent\(270\)/, 'second open-angle marker should use the shared angle-to-track mapping');
assert.match(sceneSource, /--heat-stopcock-angle-percent/, 'slider thumb, fill, and markers should share one percent coordinate system');
assert.match(sceneSource, /吸附到最近接通角/, 'stopcock focus panel should include a snap-to-nearest-open-angle action');
assert.match(sceneSource, /enabled=\{focusMode === 'none'\}/, 'orbit controls should lock while focusing an instrument control area');
assert.match(sceneSource, /data-heat-capacity-view-reset="true"/, '3D preview should expose a reset-default-view control');
assert.match(styleSource, /\.studio-heat-focus-panel \{[\s\S]*right: 14px;[\s\S]*bottom: 14px;/, 'focus panels should sit in the lower-right corner');
assert.doesNotMatch(styleSource, /\.studio-heat-stopcock-panel \{[\s\S]*left: 14px;/, 'stopcock focus panel should no longer sit in the lower-left corner');
assert.match(styleSource, /\.studio-heat-focus-panel \{[\s\S]*padding: 9px;/, 'focus panel should be compacted by reducing padding rather than dropping font sizes');
assert.match(styleSource, /\.studio-heat-focus-panel-pump \{[\s\S]*pointer-events: none;/, 'pump focus panel should not steal rapid pump clicks from the bulb behind non-control panel areas');
assert.match(styleSource, /\.studio-heat-focus-panel-pump \.studio-heat-focus-panel-actions button \{[\s\S]*pointer-events: auto;/, 'pump focus panel exit button should remain clickable when the panel body passes pointer events through');
assert.match(styleSource, /\.studio-heat-focus-panel-instrument \{[\s\S]*width: min\(338px, calc\(100% - 28px\)\);/, 'instrument focus panel should be slightly wider to keep value and units on one line');
assert.match(styleSource, /\.studio-heat-focus-panel-instrument \.studio-heat-focus-panel-row \{[\s\S]*display: grid;[\s\S]*grid-template-columns: minmax\(58px, 0\.86fr\) minmax\(108px, 1\.14fr\);/, 'instrument focus rows should use stable columns instead of flex wrapping values');
assert.match(styleSource, /\.studio-heat-focus-panel-instrument \.studio-heat-focus-panel-row strong \{[\s\S]*white-space: nowrap;/, 'instrument focus values should keep number and unit on one line');
assert.match(styleSource, /\.studio-heat-interaction-hints \{[\s\S]*position: absolute;[\s\S]*left: 12px;[\s\S]*bottom: 12px;/, 'interaction hints should sit in a low-interference corner');
assert.match(styleSource, /\.studio-heat-hover-tooltip \{[\s\S]*pointer-events: none;/, 'hover tooltip should not steal canvas interactions');

const workbenchSource = readFileSync(workbenchPath, 'utf8');
assert.match(workbenchSource, /HeatCapacityInstrumentScene/);
assert.match(workbenchSource, /adjustHeatCapacityPressureZeroFine/, 'workbench should route pressure zero wheel changes to heatCapacity state');
assert.match(workbenchSource, /adjustHeatCapacityPressureZeroCoarse/, 'workbench should route pressure zero drag changes to heatCapacity state');
assert.match(workbenchSource, /const \[heatCapacityPumpPulseId, setHeatCapacityPumpPulseId\]/, 'workbench should keep pump pulse as local UI-only state');
assert.match(workbenchSource, /setHeatCapacityPumpPulseId\(\(pulseId\) => pulseId \+ 1\)/, 'each pump press should retrigger local visual feedback');
assert.match(workbenchSource, /pumpPulseId=\{heatCapacityPumpPulseId\}/, 'workbench should pass local pump pulse signal into the 3D scene');
assert.match(workbenchSource, /pressureKPa={activeFile\.pressureKPa}/, 'workbench should pass current pressureKPa into the 3D gauge');
assert.match(workbenchSource, /pressureLimitKPa={activeFile\.pressureLimitKPa}/, 'workbench should pass pressureLimitKPa into the 3D gauge');
assert.match(workbenchSource, /updateHeatCapacityPower/);
assert.match(workbenchSource, /updateHeatCapacityStopcockAngle/);
assert.match(workbenchSource, /zeroHeatCapacityPressure/);
assert.match(workbenchSource, /updateHeatCapacityPumpValve/);
assert.match(workbenchSource, /pressHeatCapacityPumpBulb/);
assert.match(workbenchSource, /pumpFrequencyStatus/);
assert.match(workbenchSource, /heatCapacityPumpAnimationRef/, 'pump bulb animation should be retriggerable instead of locked by old timers');
assert.match(workbenchSource, /clearHeatCapacityPumpAnimationTimers/, 'new pump clicks should clear stale release and idle timers before scheduling fresh feedback');
assert.doesNotMatch(workbenchSource, /pumpBulbState === 'compressing'[\s\S]{0,80}return/, 'rapid pump clicks should not be ignored while the bulb is compressing');
assert.doesNotMatch(workbenchSource, /pumpBulbState === 'releasing'[\s\S]{0,80}return/, 'rapid pump clicks should not be ignored while the bulb is releasing');
assert.match(workbenchSource, /setInterval[\s\S]*refreshHeatCapacityPumpFrequency/, 'pump frequency should refresh on a sliding window even after clicking stops');
assert.match(workbenchSource, /getHeatCapacityPumpBulbDisplayLabel/, 'right realtime panel should map pump animation phases to user-facing labels');
assert.match(workbenchSource, /activeFile\.pumpBulbState === 'idle' \? '待机' : '打气中'/, 'right realtime panel should only show idle or pumping for pump bulb state');
assert.doesNotMatch(workbenchSource, /压缩中|回弹中|恢复中/, 'right realtime panel should not expose internal pump bulb animation phases');
assert.match(workbenchSource, /打气阀门/);
assert.match(workbenchSource, /打气频率/);
assert.match(workbenchSource, /占位压强/);
assert.match(workbenchSource, /占位温度/);
assert.doesNotMatch(workbenchSource, /打气过快|tooFast|频率偏高/, 'workbench should not show or calculate a too-fast pump state');
assert.match(workbenchSource, /压力调零/);
assert.match(workbenchSource, /温度信号/);
assert.match(workbenchSource, /压力信号/);
assert.doesNotMatch(workbenchSource, /旋塞角度/, 'realtime panel should not expose stopcock angle to users');
assert.doesNotMatch(workbenchSource, /stopcockAngleDeg, 1\)} deg/, 'realtime panel should not render internal stopcock degrees');

console.log('workbenchHeatCapacityInstrumentUi tests passed');
