import { HEAT_CAPACITY_TOAST_DISPLAY_DURATION_MS } from '../heatCapacity/heatCapacityToastController.ts';
export const GUIDE_HEAT_CAPACITY_STRONG_REMINDER_DELAY_MS = 10_000;
export const GUIDE_HEAT_CAPACITY_GUIDANCE_PULSE_INTERVAL_MS = 4000;
export const PISTON_OSCILLATION_GUIDE_HEIGHT_CONFIRM_PULSE_DELAY_MS = 3000;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_SNAP_MS = 120;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_RETURN_MS = 5000;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_WHEEL_SCALE = 0.72;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_MAX_FRAME_STEPS = 2;
export const PISTON_OSCILLATION_GUIDE_CHECKLIST_ROW_HEIGHT_PX = 64;
export const PISTON_OSCILLATION_GUIDE_CHECKLIST_CENTER_OFFSET_PX = 52;
export const PISTON_OSCILLATION_GUIDE_STRONG_REMINDER_DELAY_MS =
  GUIDE_HEAT_CAPACITY_STRONG_REMINDER_DELAY_MS;
export const PISTON_OSCILLATION_GUIDE_CLOCK_INTERVAL_MS = 250;
export const PISTON_OSCILLATION_GUIDE_ORDINARY_REMINDER_DURATION_MS =
  HEAT_CAPACITY_TOAST_DISPLAY_DURATION_MS;
export const HEAT_CAPACITY_LESSON_DIALOG_ANIMATION_MS = 180 as const;
