import { HEAT_CAPACITY_TOAST_DISPLAY_DURATION_MS } from '../heatCapacity/heatCapacityToastController.ts';
export const GUIDE_HEAT_CAPACITY_STRONG_REMINDER_DELAY_MS = 10_000;
export const GUIDE_HEAT_CAPACITY_GUIDANCE_PULSE_INTERVAL_MS = 4000;
export const PISTON_OSCILLATION_GUIDE_HEIGHT_CONFIRM_PULSE_DELAY_MS = 3000;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_SNAP_MS = 120;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_RETURN_MS = 5000;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_WHEEL_SCALE = 0.72;
export const HEAT_CAPACITY_GUIDE_CHECKLIST_MAX_FRAME_STEPS = 2;
export const PISTON_OSCILLATION_GUIDE_CHECKLIST_ROW_HEIGHT_PX = 64;
export const PISTON_OSCILLATION_GUIDE_CHECKLIST_CENTER_OFFSET_PX = 52;
export const PISTON_OSCILLATION_GUIDE_STRONG_REMINDER_DELAY_MS =
  GUIDE_HEAT_CAPACITY_STRONG_REMINDER_DELAY_MS;
export const PISTON_OSCILLATION_GUIDE_CLOCK_INTERVAL_MS = 250;
export const PISTON_OSCILLATION_GUIDE_ORDINARY_REMINDER_DURATION_MS =
  HEAT_CAPACITY_TOAST_DISPLAY_DURATION_MS;
export const HEAT_CAPACITY_LESSON_DIALOG_ANIMATION_MS = 180 as const;

export const HEAT_CAPACITY_AUTO_DEMO_LOCKED_TOAST_DEDUPE_MS = 250;
export const HEAT_CAPACITY_AUTO_DEMO_LOCKED_POINTER_FALLBACK_MS = 320;
export const HEAT_CAPACITY_GUIDE_START_NOTICE_MS = 1000;
export const HEAT_CAPACITY_PRESSURE_ALARM_DURATION_MS = 2000;
export const HEAT_CAPACITY_CLOSE_PUMP_VALVE_REMINDER_AFTER_ALARM_MS = 220;
export const HEAT_CAPACITY_RESET_FEEDBACK_MS = 650;
export const HEAT_CAPACITY_MODE_TRANSITION_VISUAL_MS = 380;
export const HEAT_CAPACITY_MODE_TRANSITION_SETTLE_DEADLINE_MS = 250;
export const HEAT_CAPACITY_AUTO_DEMO_RESET_MS = 1_800;
export const HEAT_CAPACITY_AUTO_DEMO_STEP_PANEL_EXIT_MS = 560;
