import type { HeatCapacityFreeRecordRejectReason } from '../../domain/heatCapacity/heatCapacityFreeRecordModel.ts';
import type { HeatCapacityGuideRecordKind } from '../../domain/heatCapacity/heatCapacityGuideTrialModel.ts';
import { createWorkbenchConsoleMessageTranslations, type WorkbenchConsoleMessageFactory } from './workbenchConsoleLocalization.ts';
import type { WorkbenchLanguagePreference } from './workbenchGeneralSettings.ts';
import type { WorkbenchHeatCapacityState } from './workbenchHeatCapacityStateTypes.ts';
import { workbenchCopies } from './workbenchStudioCopy.ts';

export const heatCapacityRealtimeCopies = {
  'zh-CN': {
    guideTitle: '实验指引',
    guideHint: '空气比热容比实验步骤与说明',
    recordsTitle: '数据与结果',
    recordsHint: 'U₀ / U₁ / U₂ 与空气比热容比计算',
    dataResultsTitle: '数据与结果',
    dataResultsHint: '记录值、单组 γ 与平均结果',
    reviewTitle: '过程回顾',
    reviewHint: '自由模式 trace 与操作诊断',
    materialsTitle: '实验资料与结果',
    materialsHint: 'U₁ / U₂ 与空气比热容比计算',
    closeMaterialsAria: '关闭实验资料与结果',
    materialsGroupAria: '展开或收起实验资料与结果',
    materialsFolderTitle: '点击文件夹展开/收起；单击文字选中；双击文字打开全部子标签页',
    materialsTabTitle: '单击选中；双击打开标签页',
    materialsTabsAria: '空气比热容比实验资料分页',
    previewMountAria: '空气比热容比视图预览区域',
    realtimePanelTitle: '实时数据',
    realtimeKicker: '实时数据',
    realtimeSubtitle: 'Uₜ / Uₚ、压强和过程采样',
    realtimeTitle: '空气比热容比实验',
    stagePrefix: '阶段：',
    demoPaused: '自动演示暂停',
    demoRunning: '自动演示',
    demoReady: '自动演示准备',
    autoDemoStart: '自动演示',
    autoDemoPause: '暂停演示',
    autoDemoResume: '继续演示',
    autoDemoStop: '终止演示',
    modeDemo: '演示',
    modeGuide: '引导',
    modeFree: '自由',
    guideLessonButtonLabel: '实验说明',
    guideLessonDialogAria: '热容比实验说明',
    guideLessonContinueHint: '点击空白区域来继续',
    guideChecklistLabel: '引导清单',
    guideStepLabel: '步骤',
    guideLessonIntroPages: [
      {
        title: '实验目标',
        body: '本实验通过一次“加压、快速放气、回温”的过程，记录 U₀、U₁、U₂，并换算为对应的压强状态，用来计算气体比热容比 γ。后续每一步操作都服务于获得可靠的这三个读数。',
      },
      {
        title: '压强与电压',
        body: 'Uₚ 是压强传感器输出的电压信号，不是压强本身。调零后，Uₚ 的变化代表瓶内外压强差。默认换算系数为 20 mV/kPa，所以 Uₚ = 120 mV 约对应 6 kPa 压强差，瓶内绝对压强约为大气压加 6 kPa。',
      },
      {
        title: '重新查看',
        body: '如果后续忘记这些内容，可以点击右上角、演示 / 引导 / 自由模式按钮右侧的扳手图标，重新查看刚刚的实验说明。',
      },
    ],
    guideLessonStepExplanations: {
      pressureZeroBaseline: {
        title: '压强差基准',
        body: '气瓶与外界连通时，瓶内压强与大气压相同，真实压强差应为 0。此时进行压强差调零才有明确基准；把传感器读数校正到这个状态，后面的 Uₚ 变化才代表瓶内相对外界的压强差，而不是仪器本身的零点偏移。',
      },
      sealedInitialState: {
        title: '封闭气瓶',
        body: '玻璃旋塞关闭后，气瓶与外界隔离，打入的气体会保留在瓶内，使瓶内绝对压强升高。这个封闭状态是形成放气前稳定高压状态的基础。',
      },
      pressureTarget: {
        title: '加压范围',
        body: 'Uₚ 约 120 mV 对应约 6 kPa 压强差，既能让后续放气造成足够明显的读数变化，也不会让压差过大。压差太小时，信号变化容易被波动、噪声和传感器响应影响；压差过高时，阀口流动更剧烈，过程更难接近理想的短促绝热放气，同时也更接近安全预警范围。',
      },
      preReleaseStability: {
        title: '放气前稳定',
        body: '打气后瓶内气体被压缩，压强和温度都会经历短时间变化，传感器显示也需要回稳。等待 5 min 是把这一状态视为接近热平衡，使 U₁ 代表放气前稳定高压状态，而不是刚打气后的瞬态读数。',
      },
      quickReleaseState: {
        title: '快速放气状态',
        body: '真实实验中，主要通过放气声音判断玻璃旋塞的关闭时机。听到“咻”的一声后，应等待这声“咻”完整结束；此时气体快速释放完毕，请立即点击玻璃旋塞将其关闭。关闭过早或过晚，都会成为比热容比测量的重要误差来源。软件左上角设有“微观可视化”开关，开启后可观察瓶内分子动画：当分子不再持续朝瓶口定向运动并出现大量反弹时，说明内外压强已经趋于平衡，可用来辅助判断关闭时机。微观可视化仅作为辅助，实际操作仍应以“咻”声结束作为主要判断依据。短时间放气使瓶内气体迅速膨胀并降温，这一阶段近似绝热过程；关闭旋塞后，瓶内保留下放气后的低温、低压状态。',
      },
      thermalRecovery: {
        title: '回温后的读数',
        body: '放气后瓶内气体温度低于环境。关闭旋塞后，气瓶近似保持定容，气体从环境吸热回温。等待 5 min 后记录 U₂，取的是回温稳定后的压强状态；刚放气瞬间的最低读数属于快速过程，不作为最终计算读数。',
      },
    },
    resetGuideMode: '重置引导模式',
    freeSpeedLabelCode: 'WAIT RATE',
    freeSpeedLabel: '等待倍速',
    freeSpeedAria: '等待倍速',
    freeWaitTimerLabel: { u1: 'U₁ 等待', u2: 'U₂ 等待' },
    freeWaitRecordStatus: { pending: '未记录', rerecord: '可重记' },
    exitGuideMode: '退出引导',
    exitTeachingMode: '退出教学模式',
    singleTrialBadge: '本次实验',
    trialBadge: (trialIndex: number) => `第 ${trialIndex} 次实验`,
    autoDemoFinishedLabel: '演示完成',
    demoPausedLabel: '已暂停',
    demoDoneLabel: '已完成',
    demoTargetLabel: '目标控件',
    demoProgressLabel: '推进标准',
    demoObservationLabel: '观察要点',
    autoDemoFinishedTitle: '演示完成',
    autoDemoFinishedDescription: '演示完成，可重新开始或进入引导 / 自由操作。',
    demoFallbackNote: '过程采样已保留。',
    startGuideExperiment: '引导模式',
    skipRecoveryWait: '真实实验中需要等待系统稳定；程序已省略该等待过程。',
    recordU0: '记录 U₀',
    recordU1: '记录 U₁ / Uₜ₁',
    recordU2: '记录 U₂ / Uₜ₂',
    recordDialogConfirm: '确认记录',
    recordDialogCancel: '取消',
    recordDialogCurrentPhase: '当前阶段',
    recordDialogPressure: '当前 Uₚ',
    recordDialogTemperature: '当前 Uₜ',
    recordDialogStopcock: '玻璃旋塞',
    recordDialogPumpValve: '打气阀门',
    recordDialogReady: '当前状态适合记录。',
    recordU0Warning: '请先完成压强差调零，使 Uₚ 接近 0。',
    recordU1Warning: '当前尚未达到放气前稳定状态，不建议记录 U₁。',
    recordU2Warning: '当前尚未完成回温稳定，不建议记录 U₂。',
    guideStrongReminder: '请点击目标控件，继续实验。',
    guideStrongReminderPressureZero: '请调节压强调零旋钮，继续实验。',
    guidePumpInsufficientReminder: 'Uₚ 未达到 120 mV，请继续打气。',
    guideRecordBlockedMessages: {
      u0NeedPower: '当前还不能记录 U₀。请先打开电源。',
      u0NeedStopcock: '当前还不能记录 U₀。请先打开玻璃旋塞。',
      u0NeedZero: '当前还不能记录 U₀。请先完成压力调零。',
      u0NeedCurrentStep: '当前还不能记录 U₀。请按当前步骤继续。',
      u1NeedPump: '当前还不能记录 U₁。请先完成打气。',
      u1NeedClosePumpValve: '当前还不能记录 U₁。请先关闭打气阀门。',
      u1NeedWait: '当前还不能记录 U₁。请等待计时达到 5 min。',
      u1NeedCurrentStep: '当前还不能记录 U₁。请按当前步骤继续。',
      u2NeedRelease: '当前还不能记录 U₂。请先完成快速放气。',
      u2NeedCloseStopcock: '当前还不能记录 U₂。请先关闭玻璃旋塞。',
      u2NeedWait: '当前还不能记录 U₂。请等待计时达到 5 min。',
      u2NeedCurrentStep: '当前还不能记录 U₂。请按当前步骤继续。',
    },
    guideUsageHints: {
      zeroFocus: '请双击仪表进入聚焦模式，开始压力调零。',
      zeroAdjust: '拖拽旋钮进行粗调，使用滚轮进行细调。',
      pumpValve: '请打开打气阀门。',
      pumpFocus: '请双击打气球进入聚焦模式。',
      pumpAction: '双击聚焦打气球，快速点按打气球，按压至 Uₚ ≥ 120 mV 后自动退出。',
      waitU1Ready: '5 min 到了，记录 U₁ / Uₜ₁。',
      releaseReady: '等待“咻”声结束，气体释放完毕，请立即关闭玻璃旋塞。',
      waitU2Ready: '5 min 到了，记录 U₂ / Uₜ₂。',
    },
    recordU0Success: 'U₀ 已记录。',
    recordU0SuccessToast: 'U₀ 记录成功。',
    recordU1SuccessToast: 'U₁ 和 Uₜ 记录成功。',
    recordU2SuccessToast: 'U₂ 和 Uₜ 记录成功。',
    finalTrialCompleteToast: '本次实验已完成。',
    freeGroupCompleteToast: '本次实验完成。',
    freePowerOffBeforeNextGroup: '请先关闭电源，完成本次实验后再调整参数。',
    freeRecordSuccessLog: {
      u0: '自由模式已记录 U₀ 显示值。',
      u1: '自由模式已记录 U₁ 显示值。',
      u2: '自由模式已记录 U₂ 显示值。',
    },
    freeModeActiveLog: (name: string) => `${name}：自由模式已启用。`,
    freeRecordRejectMessages: {
      'zero-not-ready': '请先打开电源并打开玻璃旋塞，再记录 U₀。',
      'calibration-changed': '调零状态已改变，请重新记录 U₀ 后再继续。',
      'unstable-pressure': '压强读数仍在变化，请等待稳定后再记录。',
      'unstable-temperature': '温度读数仍在变化，请等待回到稳定环境值后再记录。',
      'insufficient-u1': 'U₁ 压强差不足，请关闭旋塞并继续打气到有效范围。',
      'release-not-started': '请先完成快速放气并关闭旋塞，再记录 U₂。',
      'over-vented': '放气过度，U₂ 已低于有效范围；请重新开始本次实验。',
      'pressure-danger': '压强已超过安全阈值，瓶塞可能被顶开，请立即停止打气。',
      'invalid-sequence': '当前操作顺序不能记录该数据点，请按 U₀、U₁、U₂ 的顺序进行。',
    } satisfies Record<HeatCapacityFreeRecordRejectReason, string>,
    pumpFrequencySlowToast: '打气太慢，请加快打气频率。',
    pressureWarningMessage: '压强已达到建议打气范围，请停止打气并等待回温。',
    pressureAlarmMessage: '压强已超过安全阈值，瓶塞可能被顶开，请立即停止打气。',
    closePumpValveReminder: '请关闭打气阀门。',
    pumpHints: {
      idle: '未打气',
      pumpValveOpen: '打气阀门已打开',
      pumpValveClosed: '打气阀门已关闭',
      needPower: '请先打开电源，再执行有效打气',
      stopcockOpenBlocksPump: '玻璃旋塞已打开，无法形成有效加压',
      needPumpValve: '打气阀门未打开，无法有效打气',
      pressureDanger: '压强已超过安全阈值，瓶塞可能被顶开，请立即停止打气。',
      pressureWarning: '压强已达到建议打气范围，请停止打气并等待回温。',
      pumpTargetReached: '已达到打气标准，请关闭打气阀门。',
      pumpRateGood: '打气频率合适，可以继续观察压强变化',
      pumpRateSlow: '打气速率偏低，实验效果可能不明显',
      teachingComplete: '教学流程已完成',
      autoDemoStarted: '自动演示已启动',
      observeInitialPressure: '观察初始压强差示数是否为零',
    },
    pressureAlarmLog: (name: string) => `${name}：压强已超过安全阈值，瓶塞可能被顶开，请立即停止打气。`,
    toastSystemKicker: '系统',
    autoDemoLockedToast: '演示中无法操作',
    autoDemoCompletedLockedToast: '演示已完成，请退出后进入自由模式操作。',
    guideCompletedLockedToast: '引导内容已完成，请退出后进入自由模式操作。',
    autoDemoCompletionToast: '演示完成',
    guideModeStartingToast: '正在启动引导模式',
    guideModeExitedToast: '引导模式已终止',
    teachingModeExitedToast: '已退出教学模式',
    guideModeExitedLog: (name: string) => `${name}：引导模式已终止。`,
    autoDemoPreparingHint: '系统正在自动恢复默认状态，稍后开始演示',
    autoDemoReadyToCompleteHint: '自动演示即将完成，过程采样已保留',
    autoDemoImportedCompleteLog: (name: string) => `${name}：自动演示数据已导入并完成计算。`,
    autoDemoResumedLog: (name: string) => `${name}：自动演示已继续。`,
    autoDemoRunningLog: (name: string) => `${name}：自动演示正在运行。`,
    autoDemoPreparingTitle: '准备演示',
    autoDemoInitializingDescription: '正在初始化自动演示',
    autoDemoPreparingTarget: '自动演示准备',
    autoDemoPreparingProgress: '完成复位后从开启电源步骤开始。',
    autoDemoPreparingNote: '系统正在自动复位控件、视角和演示数据；完成后将从开启电源步骤开始。',
    autoDemoInitializingToast: '正在初始化自动演示',
    autoDemoStartedLog: (name: string) => `${name}：自动演示已启动。`,
    autoDemoPausedHint: '自动演示已暂停',
    autoDemoPausedLog: (name: string) => `${name}：自动演示已暂停。`,
    autoDemoTerminatedHint: '自动演示已终止',
    autoDemoTerminatedTitle: '演示已终止',
    autoDemoTerminatedDescription: '自动演示已停止，当前曲线和读数保留。',
    autoDemoTerminatedTarget: '自动演示流程',
    autoDemoTerminatedProgress: '演示已停止，用户可重新选择模式。',
    autoDemoTerminatedNote: '用户交互已恢复，可重新开始或进入引导 / 自由操作。',
    autoDemoTerminatedToast: '演示已终止',
    autoDemoTerminatedLog: (name: string) => `${name}：自动演示已终止。`,
    safetyLimit: '安全上限',
    safetyActive: '激活',
    pressureAlarmTitle: '报警',
    pressureWarningFallback: '压强已超过安全阈值，瓶塞可能被顶开，请立即停止打气。',
    pressureWarningObserve: '聚焦模式已退出，请立即停止打气。',
    operationLocked: '操作锁定',
    phaseLabels: {
      powerOff: '未开机',
      readyToZero: '等待调零',
      zeroed: '已调零',
      readyToPump: '准备打气',
      pumping: '打气中',
      sealedStabilizing: '封闭等待稳定',
      releasing: '快速放气',
      recovering: '等待回温',
      fallback: '实验准备',
    },
    stopcock: { open: '打开', closed: '关闭' },
    safety: {
      danger: '危险',
      warning: '建议停止',
      normal: '安全',
      dangerNote: '停止打气',
      warningNote: '等待回温',
      normalNote: '可继续观察',
    },
    zeroStatus: {
      completed: '已完成',
      adjustable: '可调零',
      notReady: '未就绪',
    },
    hints: {
      powerOff: '请先打开电源。',
      readyToZero: '请观察 Uₚ，并进行压强调零。',
      readyToPump: '请关闭玻璃旋塞并准备打气。',
      pumping: '连续打气至 Uₚ ≥ 120 mV，达到后停止加压。',
      sealedStabilizing: '真实实验需封闭等待 5 min，稳定后记录 U₁。',
      releasing: '关闭玻璃旋塞，并等待回温稳定。',
      recovering: '关闭玻璃旋塞后等待 5 min，回温稳定后记录 U₂。',
      fallback: '观察实时读数变化。',
    },
    readings: {
      temperature: '温度信号',
      pressure: '压强差电压',
      delta: '由当前 Uₚ 换算',
      safety: '压力状态',
      pumpValve: '打气阀门',
      stopcock: '玻璃旋塞',
      zero: '压强调零',
      currentHint: '当前提示',
      opened: '已打开',
      closed: '已关闭',
    },
  },
  'zh-TW': {
    guideTitle: '實驗指引',
    guideHint: '空氣比熱容比實驗步驟與說明',
    recordsTitle: '資料與結果',
    recordsHint: 'U₀ / U₁ / U₂ 與空氣比熱容比計算',
    dataResultsTitle: '資料與結果',
    dataResultsHint: '記錄值、單組 γ 與平均結果',
    reviewTitle: '過程回顧',
    reviewHint: '自由模式 trace 與操作診斷',
    materialsTitle: '實驗資料與結果',
    materialsHint: 'U₁ / U₂ 與空氣比熱容比計算',
    closeMaterialsAria: '關閉實驗資料與結果',
    materialsGroupAria: '展開或收起實驗資料與結果',
    materialsFolderTitle: '點擊資料夾展開/收起；單擊文字選取；雙擊文字開啟全部子分頁',
    materialsTabTitle: '單擊選取；雙擊開啟分頁',
    materialsTabsAria: '空氣比熱容比實驗資料分頁',
    previewMountAria: '空氣比熱容比視圖預覽區域',
    realtimePanelTitle: '即時資料',
    realtimeKicker: '即時資料',
    realtimeSubtitle: 'Uₜ / Uₚ、壓強和過程採樣',
    realtimeTitle: '空氣比熱容比實驗',
    stagePrefix: '階段：',
    demoPaused: '自動演示暫停',
    demoRunning: '自動演示',
    demoReady: '自動演示準備',
    autoDemoStart: '自動演示',
    autoDemoPause: '暫停演示',
    autoDemoResume: '繼續演示',
    autoDemoStop: '終止演示',
    modeDemo: '演示',
    modeGuide: '引導',
    modeFree: '自由',
    guideLessonButtonLabel: '實驗說明',
    guideLessonDialogAria: '熱容比實驗說明',
    guideLessonContinueHint: '點擊空白區域繼續',
    guideChecklistLabel: '引導清單',
    guideStepLabel: '步驟',
    guideLessonIntroPages: [
      {
        title: '實驗目標',
        body: '本實驗通過一次「加壓、快速放氣、回溫」的過程，記錄 U₀、U₁、U₂，並換算為對應的壓強狀態，用來計算氣體比熱容比 γ。後續每一步操作都服務於獲得可靠的這三個讀數。',
      },
      {
        title: '壓強與電壓',
        body: 'Uₚ 是壓強感測器輸出的電壓信號，不是壓強本身。調零後，Uₚ 的變化代表瓶內外壓強差。預設換算係數為 20 mV/kPa，所以 Uₚ = 120 mV 約對應 6 kPa 壓強差，瓶內絕對壓強約為大氣壓加 6 kPa。',
      },
      {
        title: '重新查看',
        body: '如果後續忘記這些內容，可以點擊右上角、演示 / 引導 / 自由模式按鈕右側的扳手圖標，重新查看剛剛的實驗說明。',
      },
    ],
    guideLessonStepExplanations: {
      pressureZeroBaseline: {
        title: '壓強差基準',
        body: '氣瓶與外界連通時，瓶內壓強與大氣壓相同，真實壓強差應為 0。把感測器讀數校正到這個狀態，後面的 Uₚ 變化才代表瓶內相對外界的壓強差，而不是儀器本身的零點偏移。',
      },
      sealedInitialState: {
        title: '封閉氣瓶',
        body: '玻璃旋塞關閉後，氣瓶與外界隔離，打入的氣體會保留在瓶內，使瓶內絕對壓強升高。這個封閉狀態是形成放氣前穩定高壓狀態的基礎。',
      },
      pressureTarget: {
        title: '加壓範圍',
        body: 'Uₚ 約 120 mV 對應約 6 kPa 壓強差，既能讓後續放氣造成足夠明顯的讀數變化，也不會讓壓差過大。壓差太小時，信號變化容易被波動、噪聲和感測器響應影響；壓差過高時，閥口流動更劇烈，過程更難接近理想的短促絕熱放氣，同時也更接近安全預警範圍。',
      },
      preReleaseStability: {
        title: '放氣前穩定',
        body: '打氣後瓶內氣體被壓縮，壓強和溫度都會經歷短時間變化，感測器顯示也需要回穩。等待 5 min 是把這一狀態視為接近熱平衡，使 U₁ 代表放氣前穩定高壓狀態，而不是剛打氣後的瞬態讀數。',
      },
      quickReleaseState: {
        title: '快速放氣狀態',
        body: '真實實驗中，主要通過放氣聲音判斷玻璃旋塞的關閉時機。聽到「咻」的一聲後，應等待這聲「咻」完整結束；此時氣體快速釋放完畢，請立即點擊玻璃旋塞將其關閉。關閉過早或過晚，都會成為比熱容比測量的重要誤差來源。軟件左上角設有「微觀可視化」開關，開啟後可觀察瓶內分子動畫：當分子不再持續朝瓶口定向運動並出現大量反彈時，說明內外壓強已經趨於平衡，可用來輔助判斷關閉時機。微觀可視化僅作為輔助，實際操作仍應以「咻」聲結束作為主要判斷依據。短時間放氣使瓶內氣體迅速膨脹並降溫，這一階段近似絕熱過程；關閉旋塞後，瓶內保留下放氣後的低溫、低壓狀態。',
      },
      thermalRecovery: {
        title: '回溫後的讀數',
        body: '放氣後瓶內氣體溫度低於環境。關閉旋塞後，氣瓶近似保持定容，氣體從環境吸熱回溫。等待 5 min 後記錄 U₂，取的是回溫穩定後的壓強狀態；剛放氣瞬間的最低讀數屬於快速過程，不作為最終計算讀數。',
      },
    },
    resetGuideMode: '重置引導模式',
    freeSpeedLabelCode: 'WAIT RATE',
    freeSpeedLabel: '等待倍速',
    freeSpeedAria: '等待倍速',
    freeWaitTimerLabel: { u1: 'U₁ 等待', u2: 'U₂ 等待' },
    freeWaitRecordStatus: { pending: '未記錄', rerecord: '可重記' },
    exitGuideMode: '退出引導',
    exitTeachingMode: '退出教學模式',
    singleTrialBadge: '本次實驗',
    trialBadge: (trialIndex: number) => `第 ${trialIndex} 次實驗`,
    autoDemoFinishedLabel: '演示完成',
    demoPausedLabel: '已暫停',
    demoDoneLabel: '已完成',
    demoTargetLabel: '目標控件',
    demoProgressLabel: '推進標準',
    demoObservationLabel: '觀察要點',
    autoDemoFinishedTitle: '演示完成',
    autoDemoFinishedDescription: '演示完成，可重新開始或進入引導 / 自由操作。',
    demoFallbackNote: '過程採樣已保留。',
    startGuideExperiment: '引導模式',
    skipRecoveryWait: '真實實驗中需要等待系統穩定；程序已省略該等待過程。',
    recordU0: '記錄 U₀',
    recordU1: '記錄 U₁ / Uₜ₁',
    recordU2: '記錄 U₂ / Uₜ₂',
    recordDialogConfirm: '確認記錄',
    recordDialogCancel: '取消',
    recordDialogCurrentPhase: '目前階段',
    recordDialogPressure: '目前 Uₚ',
    recordDialogTemperature: '目前 Uₜ',
    recordDialogStopcock: '玻璃旋塞',
    recordDialogPumpValve: '打氣閥門',
    recordDialogReady: '目前狀態適合記錄。',
    recordU0Warning: '請先完成壓強差調零，使 Uₚ 接近 0。',
    recordU1Warning: '目前尚未達到放氣前穩定狀態，不建議記錄 U₁。',
    recordU2Warning: '目前尚未完成回溫穩定，不建議記錄 U₂。',
    guideStrongReminder: '請點擊目標控件，繼續實驗。',
    guideStrongReminderPressureZero: '請調節壓強調零旋鈕，繼續實驗。',
    guidePumpInsufficientReminder: 'Uₚ 未達到 120 mV，請繼續打氣。',
    guideRecordBlockedMessages: {
      u0NeedPower: '目前還不能記錄 U₀。請先打開電源。',
      u0NeedStopcock: '目前還不能記錄 U₀。請先打開玻璃旋塞。',
      u0NeedZero: '目前還不能記錄 U₀。請先完成壓強調零。',
      u0NeedCurrentStep: '目前還不能記錄 U₀。請按目前步驟繼續。',
      u1NeedPump: '目前還不能記錄 U₁。請先完成打氣。',
      u1NeedClosePumpValve: '目前還不能記錄 U₁。請先關閉打氣閥門。',
      u1NeedWait: '目前還不能記錄 U₁。請等待計時達到 5 min。',
      u1NeedCurrentStep: '目前還不能記錄 U₁。請按目前步驟繼續。',
      u2NeedRelease: '目前還不能記錄 U₂。請先完成快速放氣。',
      u2NeedCloseStopcock: '目前還不能記錄 U₂。請先關閉玻璃旋塞。',
      u2NeedWait: '目前還不能記錄 U₂。請等待計時達到 5 min。',
      u2NeedCurrentStep: '目前還不能記錄 U₂。請按目前步驟繼續。',
    },
    guideUsageHints: {
      zeroFocus: '請雙擊儀表進入聚焦模式，開始壓強調零。',
      zeroAdjust: '拖曳旋鈕進行粗調，使用滾輪進行細調。',
      pumpValve: '請打開打氣閥門。',
      pumpFocus: '請雙擊打氣球進入聚焦模式。',
      pumpAction: '雙擊聚焦打氣球，快速點按打氣球，按壓至 Uₚ ≥ 120 mV 後自動退出。',
      waitU1Ready: '5 min 到了，記錄 U₁ / Uₜ₁。',
      releaseReady: '等待「咻」聲結束，氣體釋放完畢，請立即關閉玻璃旋塞。',
      waitU2Ready: '5 min 到了，記錄 U₂ / Uₜ₂。',
    },
    recordU0Success: 'U₀ 已記錄。',
    recordU0SuccessToast: 'U₀ 記錄成功。',
    recordU1SuccessToast: 'U₁ 和 Uₜ 記錄成功。',
    recordU2SuccessToast: 'U₂ 和 Uₜ 記錄成功。',
    finalTrialCompleteToast: '本次實驗已完成。',
    freeGroupCompleteToast: '本次實驗完成。',
    freePowerOffBeforeNextGroup: '請先關閉電源，完成本次實驗後再調整參數。',
    freeRecordSuccessLog: {
      u0: '自由模式已記錄 U₀ 顯示值。',
      u1: '自由模式已記錄 U₁ 顯示值。',
      u2: '自由模式已記錄 U₂ 顯示值。',
    },
    freeModeActiveLog: (name: string) => `${name}：自由模式已啟用。`,
    freeRecordRejectMessages: {
      'zero-not-ready': '請先打開電源並打開玻璃旋塞，再記錄 U₀。',
      'calibration-changed': '調零狀態已改變，請重新記錄 U₀ 後再繼續。',
      'unstable-pressure': '壓強讀數仍在變化，請等待穩定後再記錄。',
      'unstable-temperature': '溫度讀數仍在變化，請等待回到穩定環境值後再記錄。',
      'insufficient-u1': 'U₁ 壓強差不足，請關閉旋塞並繼續打氣到有效範圍。',
      'release-not-started': '請先完成快速放氣並關閉旋塞，再記錄 U₂。',
      'over-vented': '放氣過度，U₂ 已低於有效範圍；請重新開始本次實驗。',
      'pressure-danger': '壓強已超過安全閾值，瓶塞可能被頂開，請立即停止打氣。',
      'invalid-sequence': '目前操作順序不能記錄該資料點，請按 U₀、U₁、U₂ 的順序進行。',
    } satisfies Record<HeatCapacityFreeRecordRejectReason, string>,
    pumpFrequencySlowToast: '打氣太慢，請加快打氣頻率。',
    pressureWarningMessage: '壓強已達到建議打氣範圍，請停止打氣並等待回溫。',
    pressureAlarmMessage: '壓強已超過安全閾值，瓶塞可能被頂開，請立即停止打氣。',
    closePumpValveReminder: '請關閉打氣閥門。',
    pumpHints: {
      idle: '未打氣',
      pumpValveOpen: '打氣閥門已打開',
      pumpValveClosed: '打氣閥門已關閉',
      needPower: '請先打開電源，再執行有效打氣',
      stopcockOpenBlocksPump: '玻璃旋塞已打開，無法形成有效加壓',
      needPumpValve: '打氣閥門未打開，無法有效打氣',
      pressureDanger: '壓強已超過安全閾值，瓶塞可能被頂開，請立即停止打氣。',
      pressureWarning: '壓強已達到建議打氣範圍，請停止打氣並等待回溫。',
      pumpTargetReached: '已達到打氣標準，請關閉打氣閥門。',
      pumpRateGood: '打氣頻率合適，可以繼續觀察壓強變化',
      pumpRateSlow: '打氣速率偏低，實驗效果可能不明顯',
      teachingComplete: '教學流程已完成',
      autoDemoStarted: '自動演示已啟動',
      observeInitialPressure: '觀察初始壓強差示數是否為零',
    },
    pressureAlarmLog: (name: string) => `${name}：壓強已超過安全閾值，瓶塞可能被頂開，請立即停止打氣。`,
    toastSystemKicker: '系統',
    autoDemoLockedToast: '演示中無法操作',
    autoDemoCompletedLockedToast: '演示已完成，請退出後進入自由模式操作。',
    guideCompletedLockedToast: '引導內容已完成，請退出後進入自由模式操作。',
    autoDemoCompletionToast: '演示完成',
    guideModeStartingToast: '正在啟動引導模式',
    guideModeExitedToast: '引導模式已終止',
    teachingModeExitedToast: '已退出教學模式',
    guideModeExitedLog: (name: string) => `${name}：引導模式已終止。`,
    autoDemoPreparingHint: '系統正在自動恢復預設狀態，稍後開始演示',
    autoDemoReadyToCompleteHint: '自動演示即將完成，過程採樣已保留',
    autoDemoImportedCompleteLog: (name: string) => `${name}：自動演示資料已匯入並完成計算。`,
    autoDemoResumedLog: (name: string) => `${name}：自動演示已繼續。`,
    autoDemoRunningLog: (name: string) => `${name}：自動演示正在執行。`,
    autoDemoPreparingTitle: '準備演示',
    autoDemoInitializingDescription: '正在初始化自動演示',
    autoDemoPreparingTarget: '自動演示準備',
    autoDemoPreparingProgress: '完成復位後從開啟電源步驟開始。',
    autoDemoPreparingNote: '系統正在自動復位控件、視角和演示資料；完成後將從開啟電源步驟開始。',
    autoDemoInitializingToast: '正在初始化自動演示',
    autoDemoStartedLog: (name: string) => `${name}：自動演示已啟動。`,
    autoDemoPausedHint: '自動演示已暫停',
    autoDemoPausedLog: (name: string) => `${name}：自動演示已暫停。`,
    autoDemoTerminatedHint: '自動演示已終止',
    autoDemoTerminatedTitle: '演示已終止',
    autoDemoTerminatedDescription: '自動演示已停止，目前曲線和讀數保留。',
    autoDemoTerminatedTarget: '自動演示流程',
    autoDemoTerminatedProgress: '演示已停止，使用者可重新選擇模式。',
    autoDemoTerminatedNote: '使用者互動已恢復，可重新開始或進入引導 / 自由操作。',
    autoDemoTerminatedToast: '演示已終止',
    autoDemoTerminatedLog: (name: string) => `${name}：自動演示已終止。`,
    safetyLimit: '安全上限',
    safetyActive: '啟用',
    pressureAlarmTitle: '警報',
    pressureWarningFallback: '壓強已超過安全閾值，瓶塞可能被頂開，請立即停止打氣。',
    pressureWarningObserve: '聚焦模式已退出，請立即停止打氣。',
    operationLocked: '操作鎖定',
    phaseLabels: {
      powerOff: '未開機',
      readyToZero: '等待調零',
      zeroed: '已調零',
      readyToPump: '準備打氣',
      pumping: '打氣中',
      sealedStabilizing: '封閉等待穩定',
      releasing: '快速放氣',
      recovering: '等待回溫',
      fallback: '實驗準備',
    },
    stopcock: { open: '打開', closed: '關閉' },
    safety: {
      danger: '危險',
      warning: '接近閾值',
      normal: '安全',
      dangerNote: '停止打氣',
      warningNote: '準備停止打氣',
      normalNote: '可繼續觀察',
    },
    zeroStatus: {
      completed: '已完成',
      adjustable: '可調零',
      notReady: '未就緒',
    },
    hints: {
      powerOff: '請先打開電源。',
      readyToZero: '請觀察 Uₚ，並進行壓強調零。',
      readyToPump: '請關閉玻璃旋塞並準備打氣。',
      pumping: '連續打氣至 Uₚ ≥ 120 mV，達到後停止加壓。',
      sealedStabilizing: '真實實驗需封閉等待 5 min，穩定後記錄 U₁。',
      releasing: '關閉玻璃旋塞，並等待回溫穩定。',
      recovering: '關閉玻璃旋塞後等待 5 min，回溫穩定後記錄 U₂。',
      fallback: '觀察即時讀數變化。',
    },
    readings: {
      temperature: '溫度信號',
      pressure: '壓強差電壓',
      delta: '由目前 Uₚ 換算',
      safety: '壓力狀態',
      pumpValve: '打氣閥門',
      stopcock: '玻璃旋塞',
      zero: '壓強調零',
      currentHint: '目前提示',
      opened: '已打開',
      closed: '已關閉',
    },
  },
  en: {
    guideTitle: 'Experiment Guide',
    guideHint: 'Procedure and notes for the air heat capacity ratio experiment',
    recordsTitle: 'Data & Results',
    recordsHint: 'U₀ / U₁ / U₂ and heat capacity ratio calculation',
    dataResultsTitle: 'Data & Results',
    dataResultsHint: 'Recorded values, trial γ, and mean result',
    reviewTitle: 'Process Review',
    reviewHint: 'Free Mode trace and operation diagnosis',
    materialsTitle: 'Experiment Notes & Results',
    materialsHint: 'U₁ / U₂ and air heat capacity ratio calculation',
    closeMaterialsAria: 'Close experiment notes and results',
    materialsGroupAria: 'Expand or collapse experiment notes and results',
    materialsFolderTitle: 'Click the folder to expand or collapse; click text to select; double-click text to open all child tabs',
    materialsTabTitle: 'Click to select; double-click to open the tab',
    materialsTabsAria: 'Heat Capacity experiment notes tabs',
    previewMountAria: 'Heat capacity ratio view preview mount',
    realtimePanelTitle: 'Realtime Data',
    realtimeKicker: 'Realtime Data',
    realtimeSubtitle: 'Uₜ / Uₚ, pressure, and process samples',
    realtimeTitle: 'Air Heat Capacity Ratio Experiment',
    stagePrefix: 'Stage: ',
    demoPaused: 'Auto demo paused',
    demoRunning: 'Auto demo',
    demoReady: 'Auto demo ready',
    autoDemoStart: 'Auto demo',
    autoDemoPause: 'Pause demo',
    autoDemoResume: 'Resume demo',
    autoDemoStop: 'Stop demo',
    modeDemo: 'Demo',
    modeGuide: 'Guide',
    modeFree: 'Free',
    guideLessonButtonLabel: 'Experiment notes',
    guideLessonDialogAria: 'Heat capacity experiment notes',
    guideLessonContinueHint: 'Click blank area to continue',
    guideChecklistLabel: 'Guide checklist',
    guideStepLabel: 'Step',
    guideLessonIntroPages: [
      {
        title: 'Experiment goal',
        body: 'This experiment records U₀, U₁, and U₂ through one pressurizing, quick-release, and thermal-recovery sequence. Those readings are converted into pressure states and used to calculate the gas heat capacity ratio γ. Each experiment step supports reliable values for these three readings.',
      },
      {
        title: 'Pressure and voltage',
        body: 'Uₚ is the pressure-sensor voltage signal, not pressure itself. After zeroing, changes in Uₚ represent the pressure difference between the vessel and the outside air. The default conversion is 20 mV/kPa, so Uₚ = 120 mV corresponds to about 6 kPa pressure difference, and the vessel absolute pressure is roughly atmospheric pressure plus 6 kPa.',
      },
      {
        title: 'Review later',
        body: 'If you forget this explanation later, click the wrench in the upper-right corner, just to the right of the Demo / Guide / Free mode buttons, to rewatch these experiment notes.',
      },
    ],
    guideLessonStepExplanations: {
      pressureZeroBaseline: {
        title: 'Pressure-difference baseline',
        body: 'When the vessel is connected to the outside air, the internal pressure matches atmospheric pressure, so the true pressure difference is 0. Calibrating the sensor at this state makes later Uₚ changes represent the vessel pressure difference instead of the instrument zero offset.',
      },
      sealedInitialState: {
        title: 'Sealed vessel',
        body: 'After the glass stopcock closes, the vessel is isolated from the outside air. Pumped gas remains in the vessel and raises its absolute pressure. This sealed state is the basis for the stable high-pressure state before release.',
      },
      pressureTarget: {
        title: 'Pressurizing range',
        body: 'Uₚ around 120 mV corresponds to about 6 kPa pressure difference. That range gives the quick release a clear signal change without making the pressure difference too large. If the pressure difference is too small, noise, fluctuation, and sensor response dominate the data; if it is too high, the valve flow becomes more violent, the short adiabatic-release approximation is harder to keep, and the system approaches the safety-warning region.',
      },
      preReleaseStability: {
        title: 'Stable state before release',
        body: 'After pumping, the gas has been compressed, and both pressure and temperature go through a short transient while the sensor display also settles. The 5 min wait treats this state as near thermal equilibrium, so U₁ represents the stable high-pressure state before release rather than the immediate transient after pumping.',
      },
      quickReleaseState: {
        title: 'Quick-release state',
        body: 'In the real experiment, the release sound is the primary cue for closing the glass stopcock. After you hear the “whoosh,” wait for that sound to finish completely; the rapid gas release is then complete, so click the glass stopcock immediately to close it. Closing too early or too late is an important source of error in the measured heat-capacity ratio. A “Microscopic visualization” switch is available in the upper-left corner. When enabled, its molecular animation can assist your judgment: the internal and external pressures are approaching balance when molecules stop moving persistently toward the bottle opening and many of them rebound. This visualization is only an auxiliary cue; the end of the “whoosh” remains the primary operating criterion. The short release makes the gas expand and cool rapidly in an approximately adiabatic process, leaving a low-temperature, lower-pressure state after the stopcock closes.',
      },
      thermalRecovery: {
        title: 'Recovered U₂ reading',
        body: 'After release, the gas temperature in the vessel is lower than the environment. With the stopcock closed, the vessel is treated as nearly constant-volume while the gas absorbs heat and recovers. U₂ is recorded after the 5 min recovery wait; the minimum reading immediately after release belongs to the fast transient and is not used as the final calculation reading.',
      },
    },
    resetGuideMode: 'Reset Guide mode',
    freeSpeedLabelCode: 'WAIT RATE',
    freeSpeedLabel: 'Wait speed',
    freeSpeedAria: 'Wait speed multiplier',
    freeWaitTimerLabel: { u1: 'U1 wait', u2: 'U2 wait' },
    freeWaitRecordStatus: { pending: 'Not recorded', rerecord: 'Can re-record' },
    exitGuideMode: 'Exit guide',
    exitTeachingMode: 'Exit teaching mode',
    singleTrialBadge: 'This experiment',
    trialBadge: (trialIndex: number) => `Trial ${trialIndex}`,
    autoDemoFinishedLabel: 'Demo complete',
    demoPausedLabel: 'Paused',
    demoDoneLabel: 'Complete',
    demoTargetLabel: 'Target control',
    demoProgressLabel: 'Standard',
    demoObservationLabel: 'Observation',
    autoDemoFinishedTitle: 'Demo complete',
    autoDemoFinishedDescription: 'Demo complete. You can restart or use guide / free mode.',
    demoFallbackNote: 'Process samples are retained.',
    startGuideExperiment: 'Guide mode',
    skipRecoveryWait: 'The real experiment would wait for the system to stabilize; this program omits that wait.',
    recordU0: 'Record U₀',
    recordU1: 'Record U₁ / Uₜ₁',
    recordU2: 'Record U₂ / Uₜ₂',
    recordDialogConfirm: 'Confirm record',
    recordDialogCancel: 'Cancel',
    recordDialogCurrentPhase: 'Current phase',
    recordDialogPressure: 'Current Uₚ',
    recordDialogTemperature: 'Current Uₜ',
    recordDialogStopcock: 'Glass stopcock',
    recordDialogPumpValve: 'Pump valve',
    recordDialogReady: 'Current state is suitable for recording.',
    recordU0Warning: 'Complete pressure zeroing first so Uₚ is close to 0.',
    recordU1Warning: 'The pre-release stable state has not been reached. U₁ recording is not recommended.',
    recordU2Warning: 'Thermal recovery is not complete. U₂ recording is not recommended.',
    guideStrongReminder: 'Click the target control to continue the experiment.',
    guideStrongReminderPressureZero: 'Adjust the pressure-zero knob to continue the experiment.',
    guidePumpInsufficientReminder: 'Uₚ has not reached 120 mV. Continue pumping.',
    guideRecordBlockedMessages: {
      u0NeedPower: 'U₀ cannot be recorded yet. Turn on the power first.',
      u0NeedStopcock: 'U₀ cannot be recorded yet. Open the glass stopcock first.',
      u0NeedZero: 'U₀ cannot be recorded yet. Complete pressure zeroing first.',
      u0NeedCurrentStep: 'U₀ cannot be recorded yet. Continue the current step.',
      u1NeedPump: 'U₁ cannot be recorded yet. Complete pumping first.',
      u1NeedClosePumpValve: 'U₁ cannot be recorded yet. Close the pump valve first.',
      u1NeedWait: 'U₁ cannot be recorded yet. Wait until the timer reaches 5 min.',
      u1NeedCurrentStep: 'U₁ cannot be recorded yet. Continue the current step.',
      u2NeedRelease: 'U₂ cannot be recorded yet. Complete quick release first.',
      u2NeedCloseStopcock: 'U₂ cannot be recorded yet. Close the glass stopcock first.',
      u2NeedWait: 'U₂ cannot be recorded yet. Wait until the timer reaches 5 min.',
      u2NeedCurrentStep: 'U₂ cannot be recorded yet. Continue the current step.',
    },
    guideUsageHints: {
      zeroFocus: 'Double-click the instrument to enter focus mode and start pressure zeroing.',
      zeroAdjust: 'Drag the knob for coarse adjustment and use the wheel for fine adjustment.',
      pumpValve: 'Open the pump valve.',
      pumpFocus: 'Double-click the pump bulb to enter focus mode.',
      pumpAction: 'Double-click the pump bulb to focus, then click rapidly until Uₚ ≥ 120 mV; focus exits automatically.',
      waitU1Ready: '5 min has elapsed. Record U₁ / Uₜ₁.',
      releaseReady: 'Wait for the “whoosh” to end; once the gas release is complete, close the glass stopcock immediately.',
      waitU2Ready: '5 min has elapsed. Record U₂ / Uₜ₂.',
    },
    recordU0Success: 'U₀ recorded.',
    recordU0SuccessToast: 'U₀ recorded successfully.',
    recordU1SuccessToast: 'U₁ and Uₜ recorded successfully.',
    recordU2SuccessToast: 'U₂ and Uₜ recorded successfully.',
    finalTrialCompleteToast: 'The experiment is complete.',
    freeGroupCompleteToast: 'This experiment is complete.',
    freePowerOffBeforeNextGroup: 'Turn off the power to complete this trial before adjusting parameters.',
    freeRecordSuccessLog: {
      u0: 'Free Mode recorded the U₀ display value.',
      u1: 'Free Mode recorded the U₁ display value.',
      u2: 'Free Mode recorded the U₂ display value.',
    },
    freeModeActiveLog: (name: string) => `${name}: Free Mode active.`,
    freeRecordRejectMessages: {
      'zero-not-ready': 'Turn on power and open the glass stopcock before recording U₀.',
      'calibration-changed': 'The zeroing state changed. Record U₀ again before continuing.',
      'unstable-pressure': 'The pressure reading is still changing. Wait until it is stable.',
      'unstable-temperature': 'The temperature reading is still changing. Wait until it returns to a stable ambient value.',
      'insufficient-u1': 'U₁ pressure difference is too small. Close the stopcock and keep pumping into the effective range.',
      'release-not-started': 'Complete the quick release and close the stopcock before recording U₂.',
      'over-vented': 'The release was excessive and U₂ is below the effective range. Restart this experiment.',
      'pressure-danger': 'Pressure exceeds the safety threshold. The stopper may be forced open. Stop pumping immediately.',
      'invalid-sequence': 'This point cannot be recorded in the current sequence. Record in U₀, U₁, U₂ order.',
    } satisfies Record<HeatCapacityFreeRecordRejectReason, string>,
    pumpFrequencySlowToast: 'Pumping is too slow. Increase the pumping rate.',
    pressureWarningMessage: 'Pressure has reached the recommended pumping range. Stop pumping and wait for thermal recovery.',
    pressureAlarmMessage: 'Pressure exceeds the safety threshold. The stopper may be forced open. Stop pumping immediately.',
    closePumpValveReminder: 'Close the pump valve.',
    pumpHints: {
      idle: 'Not pumped',
      pumpValveOpen: 'Pump valve is open',
      pumpValveClosed: 'Pump valve is closed',
      needPower: 'Turn on the power before effective pumping',
      stopcockOpenBlocksPump: 'The glass stopcock is open, so pressure cannot build effectively',
      needPumpValve: 'Open the pump valve before effective pumping',
      pressureDanger: 'Pressure exceeds the safety threshold. The stopper may be forced open. Stop pumping immediately.',
      pressureWarning: 'Pressure has reached the recommended pumping range. Stop pumping and wait for thermal recovery.',
      pumpTargetReached: 'Pumping target reached. Close the pump valve.',
      pumpRateGood: 'Pumping rate is suitable. Continue watching the pressure change',
      pumpRateSlow: 'Pumping rate is low, so the experiment may be less visible',
      teachingComplete: 'Teaching flow complete',
      autoDemoStarted: 'Auto demo started',
      observeInitialPressure: 'Observe whether the initial pressure-difference reading is zero',
    },
    pressureAlarmLog: (name: string) => `${name}: Pressure exceeds the safety threshold. The stopper may be forced open. Stop pumping immediately.`,
    toastSystemKicker: 'SYSTEM',
    autoDemoLockedToast: 'Cannot operate during the demo',
    autoDemoCompletedLockedToast: 'Demo is complete. Exit before operating in Free Mode.',
    guideCompletedLockedToast: 'Guide is complete. Exit before operating in Free Mode.',
    autoDemoCompletionToast: 'Demo complete',
    guideModeStartingToast: 'Starting guide mode',
    guideModeExitedToast: 'Guide mode stopped',
    teachingModeExitedToast: 'Teaching mode exited',
    guideModeExitedLog: (name: string) => `${name}: guide mode stopped.`,
    autoDemoPreparingHint: 'The system is restoring default state and will start the demo shortly',
    autoDemoReadyToCompleteHint: 'Auto demo is about to finish; process samples are retained',
    autoDemoImportedCompleteLog: (name: string) => `${name}: auto-demo data imported and calculated.`,
    autoDemoResumedLog: (name: string) => `${name}: auto demo resumed.`,
    autoDemoRunningLog: (name: string) => `${name}: auto demo is already running.`,
    autoDemoPreparingTitle: 'Preparing demo',
    autoDemoInitializingDescription: 'Initializing auto demo',
    autoDemoPreparingTarget: 'Auto demo setup',
    autoDemoPreparingProgress: 'After reset, the demo starts from power-on.',
    autoDemoPreparingNote: 'The system is resetting controls, view, and demo data. After that it starts from power on.',
    autoDemoInitializingToast: 'Initializing auto demo',
    autoDemoStartedLog: (name: string) => `${name}: auto demo started.`,
    autoDemoPausedHint: 'Auto demo paused',
    autoDemoPausedLog: (name: string) => `${name}: auto demo paused.`,
    autoDemoTerminatedHint: 'Auto demo stopped',
    autoDemoTerminatedTitle: 'Demo stopped',
    autoDemoTerminatedDescription: 'Auto demo has stopped. Current curves and readings are retained.',
    autoDemoTerminatedTarget: 'Auto demo flow',
    autoDemoTerminatedProgress: 'The demo is stopped. Choose a mode to continue.',
    autoDemoTerminatedNote: 'User interaction is restored. You can restart or enter guide / free mode.',
    autoDemoTerminatedToast: 'Demo stopped',
    autoDemoTerminatedLog: (name: string) => `${name}: auto demo stopped.`,
    safetyLimit: 'Safety limit',
    safetyActive: 'Active',
    pressureAlarmTitle: 'Alarm',
    pressureWarningFallback: 'Pressure exceeds the safety threshold. The stopper may be forced open. Stop pumping immediately.',
    pressureWarningObserve: 'Focus mode has exited. Stop pumping immediately.',
    operationLocked: 'Operation locked',
    phaseLabels: {
      powerOff: 'Power off',
      readyToZero: 'Waiting to zero',
      zeroed: 'Zeroed',
      readyToPump: 'Ready to pump',
      pumping: 'Pumping',
      sealedStabilizing: 'Sealed stabilization',
      releasing: 'Quick release',
      recovering: 'Thermal recovery',
      fallback: 'Experiment ready',
    },
    stopcock: { open: 'Open', closed: 'Closed' },
    safety: {
      danger: 'Danger',
      warning: 'Approaching threshold',
      normal: 'Safe',
      dangerNote: 'Stop pumping',
      warningNote: 'Prepare to stop',
      normalNote: 'Continue observing',
    },
    zeroStatus: {
      completed: 'Complete',
      adjustable: 'Adjustable',
      notReady: 'Not ready',
    },
    hints: {
      powerOff: 'Turn on the power first.',
      readyToZero: 'Observe Uₚ and zero the pressure signal.',
      readyToPump: 'Close the glass stopcock and prepare to pump.',
      pumping: 'Pump continuously until Uₚ ≥ 120 mV, then stop pressurizing.',
      sealedStabilizing: 'In the real procedure, wait sealed for 5 min, then record U₁.',
      releasing: 'Close the glass stopcock and wait for thermal recovery.',
      recovering: 'After closing the stopcock, wait 5 min and record U₂ after recovery.',
      fallback: 'Observe live readings.',
    },
    readings: {
      temperature: 'Temperature signal',
      pressure: 'Pressure-difference voltage',
      delta: 'Converted from current Uₚ',
      safety: 'Pressure status',
      pumpValve: 'Pump valve',
      stopcock: 'Glass stopcock',
      zero: 'Pressure zero',
      currentHint: 'Current hint',
      opened: 'Open',
      closed: 'Closed',
    },
  },
} as const;

export const getHeatCapacityRealtimeCopy = (language: WorkbenchLanguagePreference) => (
  heatCapacityRealtimeCopies[language] ?? heatCapacityRealtimeCopies['zh-CN']
);

export type HeatCapacityRealtimeCopy = (typeof heatCapacityRealtimeCopies)[WorkbenchLanguagePreference];

export const getLocalizedHeatCapacityGuideRecordFailure = (
  file: WorkbenchHeatCapacityState,
  kind: HeatCapacityGuideRecordKind,
  language: WorkbenchLanguagePreference,
  fallback: string,
) => {
  if (file.heatCapacityMode !== 'guide') return fallback;
  const messages = getHeatCapacityRealtimeCopy(language).guideRecordBlockedMessages;
  const step = file.heatCapacityGuideWorkflow.step;
  if (kind === 'u0') {
    if (step === 'powerRequired') return messages.u0NeedPower;
    if (step === 'openStopcockForZeroRequired') return messages.u0NeedStopcock;
    if (step === 'zeroRequired') return messages.u0NeedZero;
    return messages.u0NeedCurrentStep;
  }
  if (kind === 'u1') {
    if (step === 'closePumpValveRequired') return messages.u1NeedClosePumpValve;
    if (step === 'u1Waiting') return messages.u1NeedWait;
    if (step === 'closeStopcockBeforePumpRequired' || step === 'openPumpValveRequired' || step === 'pumpRequired') {
      return messages.u1NeedPump;
    }
    return messages.u1NeedCurrentStep;
  }
  if (step === 'closeStopcockAfterReleaseRequired') return messages.u2NeedCloseStopcock;
  if (step === 'u2Waiting') return messages.u2NeedWait;
  if (step === 'openStopcockForReleaseRequired') return messages.u2NeedRelease;
  return messages.u2NeedCurrentStep;
};

const knownLocalizedConsoleMessageFactories: WorkbenchConsoleMessageFactory[] = [
  (language) => workbenchCopies[language].logs.initialized,
  (language) => workbenchCopies[language].logs.defaultLayout,
  (language) => workbenchCopies[language].logs.standardConnected,
  (language) => workbenchCopies[language].logs.exportBridgeRequired,
  (language) => workbenchCopies[language].logs.editHistoryCleared,
  (language) => workbenchCopies[language].logs.layoutSaveNeedsFile,
  (language) => workbenchCopies[language].logs.fileNameCannotBeEmpty,
  ...(['checking', 'available-system', 'available-bundled', 'unavailable', 'error'] as const).map(
    (status): WorkbenchConsoleMessageFactory => (
      (language) => workbenchCopies[language].exportEnvironment[status].detail
    ),
  ),
  (language) => getHeatCapacityRealtimeCopy(language).recordU0SuccessToast,
  (language) => getHeatCapacityRealtimeCopy(language).recordU1SuccessToast,
  (language) => getHeatCapacityRealtimeCopy(language).recordU2SuccessToast,
  (language) => getHeatCapacityRealtimeCopy(language).finalTrialCompleteToast,
  (language) => getHeatCapacityRealtimeCopy(language).freeGroupCompleteToast,
  (language) => getHeatCapacityRealtimeCopy(language).freeRecordSuccessLog.u0,
  (language) => getHeatCapacityRealtimeCopy(language).freeRecordSuccessLog.u1,
  (language) => getHeatCapacityRealtimeCopy(language).freeRecordSuccessLog.u2,
];

export const findKnownConsoleMessageTranslations = (message: string) => {
  for (const factory of knownLocalizedConsoleMessageFactories) {
    const messages = createWorkbenchConsoleMessageTranslations(factory);
    if (Object.values(messages).includes(message)) return messages;
  }
  return null;
};
type HeatCapacityPumpHintKey = keyof HeatCapacityRealtimeCopy['pumpHints'];

const HEAT_CAPACITY_REALTIME_STATE_HINT_FIELDS = [
  'autoDemoPreparingHint',
  'autoDemoReadyToCompleteHint',
  'autoDemoPausedHint',
  'autoDemoTerminatedHint',
] as const satisfies readonly (keyof HeatCapacityRealtimeCopy)[];

export const getLocalizedHeatCapacityPumpHint = (
  value: string | null | undefined,
  language: WorkbenchLanguagePreference,
) => {
  if (!value) return '';
  const targetCopy = getHeatCapacityRealtimeCopy(language);
  const allCopies = Object.values(heatCapacityRealtimeCopies) as HeatCapacityRealtimeCopy[];
  for (const sourceCopy of allCopies) {
    for (const key of Object.keys(sourceCopy.pumpHints) as HeatCapacityPumpHintKey[]) {
      if (sourceCopy.pumpHints[key] === value) return targetCopy.pumpHints[key];
    }
    for (const key of HEAT_CAPACITY_REALTIME_STATE_HINT_FIELDS) {
      if (sourceCopy[key] === value) return targetCopy[key];
    }
  }
  return value;
};

export const getHeatCapacityFreeRecordRejectMessage = (
  reason: HeatCapacityFreeRecordRejectReason,
  copy: ReturnType<typeof getHeatCapacityRealtimeCopy>,
) => copy.freeRecordRejectMessages[reason];
