

export const SHARED_EXPERIMENT_PROGRESS_COPY = {
  'zh-CN': {
    heatProgress: (current: number, total: number) => `第 ${current} / ${total} 次实验`,
    heatMenu: '本组实验操作',
    heatRestartRun: (current: number) => `重新开始第 ${current} 次实验`,
    heatRestartGroup: '重新开始本组实验',
    heatAbandon: '放弃本组草稿',
    heatNext: '开始下一组实验',
    heatFirst: '开始第一组实验',
    pistonProgress: (ordinal: number, total: number, heightMm: number) => (
      `第 ${ordinal} / ${total} 次 · 目标 ${heightMm} mm`
    ),
    pistonCompleted: (total: number) => `已完成 ${total} / ${total} 次`,
    pistonMenu: '管理本轮自由实验',
    pistonOpenMenu: '打开自由模式实验管理菜单',
    pistonPlan: '本轮实验计划',
    pistonSaved: '已保存',
    pistonCurrent: '当前目标',
    pistonPending: '待完成',
    pistonDelete: (heightMm: number) => `删除 ${heightMm} mm 的已保存实验`,
    pistonConfirmDelete: '确认删除',
    cancel: '取消',
    pistonReset: '重置自由模式',
    pistonSetup: '设置新实验计划',
  },
  'zh-TW': {
    heatProgress: (current: number, total: number) => `第 ${current} / ${total} 次實驗`,
    heatMenu: '本組實驗操作',
    heatRestartRun: (current: number) => `重新開始第 ${current} 次實驗`,
    heatRestartGroup: '重新開始本組實驗',
    heatAbandon: '放棄本組草稿',
    heatNext: '開始下一組實驗',
    heatFirst: '開始第一組實驗',
    pistonProgress: (ordinal: number, total: number, heightMm: number) => (
      `第 ${ordinal} / ${total} 次 · 目標 ${heightMm} mm`
    ),
    pistonCompleted: (total: number) => `已完成 ${total} / ${total} 次`,
    pistonMenu: '管理本輪自由實驗',
    pistonOpenMenu: '開啟自由模式實驗管理選單',
    pistonPlan: '本輪實驗計畫',
    pistonSaved: '已儲存',
    pistonCurrent: '目前目標',
    pistonPending: '待完成',
    pistonDelete: (heightMm: number) => `刪除 ${heightMm} mm 的已儲存實驗`,
    pistonConfirmDelete: '確認刪除',
    cancel: '取消',
    pistonReset: '重設自由模式',
    pistonSetup: '設定新實驗計畫',
  },
  en: {
    heatProgress: (current: number, total: number) => `Experiment ${current} / ${total}`,
    heatMenu: 'Experiment group actions',
    heatRestartRun: (current: number) => `Restart experiment ${current}`,
    heatRestartGroup: 'Restart experiment group',
    heatAbandon: 'Abandon group draft',
    heatNext: 'Start next group',
    heatFirst: 'Start first group',
    pistonProgress: (ordinal: number, total: number, heightMm: number) => (
      `Run ${ordinal} / ${total} · Target ${heightMm} mm`
    ),
    pistonCompleted: (total: number) => `Completed ${total} / ${total} runs`,
    pistonMenu: 'Manage this Free-mode plan',
    pistonOpenMenu: 'Open Free-mode experiment management',
    pistonPlan: 'Experiment plan',
    pistonSaved: 'Saved',
    pistonCurrent: 'Current target',
    pistonPending: 'Pending',
    pistonDelete: (heightMm: number) => `Delete the saved ${heightMm} mm run`,
    pistonConfirmDelete: 'Confirm delete',
    cancel: 'Cancel',
    pistonReset: 'Reset Free mode',
    pistonSetup: 'Set up a new experiment plan',
  },
} as const;
